### ISSUE TITLE
no mbl_dir in config

### ISSUE THREAD

**Issue by sthen** [extremeshok/clamav-unofficial-sigs#1]
MalwareBytes was reinstated after being removed, but mbl_dir wasn't readded to the config file.

**Comment by sthen** [comment]
This was also removed from the mkdir line.

**Comment by sthen** [comment]
...though should it really have been reinstated?

"# WARNING: this block list was discontinued on Oct/07/2013
# according to our previous announcements.
# Users are advised to visit https://www.malwarepatrol.net/
# for information on how to continue using our data feed."

**Comment by extremeshok** [comment]
Fixed with 7e93a995dc56ded846ccb93c0709ae6c04042ce9
