### ISSUE TITLE
man_dir must include man8

### ISSUE THREAD

**Issue by smwardle** [extremeshok/clamav-unofficial-sigs#100]
--install-man requires man8 in man_dir

eg man_dir="/usr/local/share/man/man8"

I would expect man_dir="/usr/local/share/man"

**Comment by extremeshok** [comment]
Set the following in your user.conf or os.conf to change the location.
#man_dir="" #default: /etc/man.d
#man_filename="" #default: clamav-unofficial-sigs

Pretty much, ill add them to each os.xxx.conf once i have a list of locations

The way I code, virtually everything can be overridden, so check the master.conf for all the options.

**Comment by extremeshok** [comment]
ls /usr/share/man/man8 | grep clam
clamav-unofficial-sigs.8
clamd.8.gz

**Comment by smwardle** [comment]
But shouldn't man_dir point to the man root rather than .../man/man8 ?

**Comment by extremeshok** [comment]
/usr/share/man/man8 is correct

````
ls /usr/share/man/
cs/    de/    fi/    gl/    id/    ja/    man1/  man3/  man5/  man7/  nl/    pt/    ru/    sv/    zh_CN/
da/    es/    fr/    hu/    it/    ko/    man2/  man4/  man6/  man8/  pl/    pt_BR/ sl/    tr/    zh_TW/
````
