### ISSUE TITLE
--remove-script isn't removing cron, logrotate and man file

### ISSUE THREAD

**Issue by reneschuster** [extremeshok/clamav-unofficial-sigs#102]
Here the error:

```
     ....
     Removed file: /var/lib/clamav-unofficial-sigs/gpg-key/ss-keyring.gpg
     Removed file: /var/lib/clamav-unofficial-sigs/gpg-key/ss-keyring.gpg~
     Removed file: /var/lib/clamav-unofficial-sigs/gpg-key/trustdb.gpg
     Removed file: /var/log/clamav-unofficial-sigs/clamav-unofficial-sigs.log
     Removed file: /var/lib/clamav-unofficial-sigs/configs/purge.txt
rm: cannot remove ‘/’: Is a directory
     Removed file: /
rm: cannot remove ‘/’: Is a directory
     Removed file: /
rm: cannot remove ‘/’: Is a directory
     Removed file: /
     Removed script working directories: /var/lib/clamav-unofficial-sigs
     ....
```
The variables are not available when running --remove-script:
```
$cron_dir
$cron_filename
$logrotate_dir
$logrotate_filename
$man_dir
$man_filename
```

**Comment by marcin-github** [comment]
Installing and uninstalling should be done by package manager. Do one thing and do it well. 
https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123
https://github.com/valvesoftware/steam-for-linux/issues/3671

**Comment by nerijus** [comment]
http://www.telegraph.co.uk/technology/2016/04/14/man-deletes-his-whole-company-after-typing-wrong-bit-of-code/

**Comment by extremeshok** [comment]
I only run -rf for the workdir, which should be assigned correctly, or the script wont function.

I will add some extra noob protections to make sure the path is more than 1 layer deep and contains something specific to the workdir.

**Comment by IdahoPL** [comment]
+1 to what @marcin-github said. Leave installing and uninstalling to package managers, they will do it properly and with tracking all files.

**Comment by extremeshok** [comment]
Added some changes in 5.2.2.

Agree with management either via packages or configuration management. 

Unfortunately some users still want the legacy --remove_script option. If the pgk_ options are defined the remove_script is disabled.
