### ISSUE TITLE
issue #88 present in v5.2.1

### ISSUE THREAD

**Issue by stewardle** [extremeshok/clamav-unofficial-sigs#103]
Version: v5.2.1 (16 April 2016)
Problem with databases being removed (#88) has reappeared in latest version.

**Comment by extremeshok** [comment]
Should be fixed with d39e2125e5f7fa8a50cd5b4909552286393e371d

**Comment by stewardle** [comment]
#88 and "$yararulesproject_enabledd" fixed but now get:

Loading config: /etc/clamav-unofficial-sigs/user.conf
=====================================================
Force Updates: enabled
cp: cannot stat `/var/lib/clamav-unofficial-sigs/configs/current-dbs.txt': No such file or directory

Steve

**Comment by extremeshok** [comment]
I know, I need to commit for it to test on my build vm.

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by stewardle** [comment]
#88 and "$yararulesproject_enabledd" fixed but now get:

Loading config: /etc/clamav-unofficial-sigs/user.conf
=====================================================
Force Updates: enabled
cp: cannot stat `/var/lib/clamav-unofficial-sigs/configs/current-dbs.txt': No such file or directory

current-dbs.txt only generated if "$remove_disabled_databases" == "yes"

# Remove 3rd-party databases and/or backup files that are no longer being used.
if [ "$remove_disabled_databases" == "yes" ] ; then
	sort "$current_tmp" > "$current_dbs" 2>/dev/null
	rm -f "$current_tmp"

Steve

**Comment by extremeshok** [comment]
should be fixed in b0a74d3968a8e46b491541e118278d7623557a3c

**Comment by stewardle** [comment]
New typo "$|yararulesproject_enabled" lines 1527 an 2232.

Loading config: /etc/clamav-unofficial-sigs/user.conf
=====================================================
Force Updates: enabled
cp: cannot stat `': No such file or directory

Line 1574 uses $current_dbs but it's not assigned unless "$remove_disabled_databases" == "yes"

**Comment by extremeshok** [comment]
yup, testing https://codeclimate.com/github/extremeshok/clamav-unofficial-sigs/compare/dev#bugrisk

**Comment by extremeshok** [comment]
it should do shellcheck and linting

**Comment by stewardle** [comment]
691fe588ced76fafc3bb2d8b417b96708bff0385 tests OK here.

**Comment by extremeshok** [comment]
What you using for testing ? Maybe I can replicate it with my Travis-ci checks

Codeclimate .. Not sure it's worth the effort.

**Comment by stewardle** [comment]
Just testing the functionality in terms of downloading what I expect, not deleting disabled signs and not throwing any error messages.

Steve

**Comment by extremeshok** [comment]
thanks for your help
