### ISSUE TITLE
Bug with remove_disabled_databases

### ISSUE THREAD

**Issue by reneschuster** [extremeshok/clamav-unofficial-sigs#105]
When `remove_disabled_databases=yes` ([L1552](https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/clamav-unofficial-sigs.sh#L1552)) then the `current_dbs.txt` will be deleted ([L1555](https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/clamav-unofficial-sigs.sh#L1555)) and thus the `purge.txt` file ([L1575](https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/clamav-unofficial-sigs.sh#L1575)) does only have the config and gpg files included.

On a `--remove-script` only the config and gpg files will be deleted and all signature database files in `/var/lib/clamav` remain in the directory.

**Comment by extremeshok** [comment]
I plan on rewriting the remove_disabled and remove-script code, they are pretty much still using the legacy logic.

On remove-script with remove_disabled_databases=yes, can I assume it needs to remove the 3rd party databases from var/lib/clamav

On remove-script with remove_disabled_databases=NO, can I assume it needs leave the 3rd party databases from var/lib/clamav untouched ?

**Comment by extremeshok** [comment]
a fix is currently in progress

**Comment by extremeshok** [comment]
Please can you test with the latest dev

**Comment by reneschuster** [comment]
I got some time for testing today.
On `--remove-script` with `remove_disabled_databases=yes`, the 3rd party databases are removed.

But when a database will be disabled after it was enabled for some time e.g. `sanesecurity_enabled=no` and `remove_disabled_databases=yes` then it will not be removed from /var/lib/clamav after a new invocation of the scriupt. 
Even worse when you use `--remove-script` these databases will again not be removed and you have to remove them manually.

**Comment by extremeshok** [comment]
> But when a database will be disabled after it was enabled for some time e.g. sanesecurity_enabled=no and remove_disabled_databases=yes then it will not be removed from /var/lib/clamav after a new invocation of the script. 

This is a bug, so I need to figure out why this is not working.

I think the fix for the first bug, will fix the second issue

**Comment by extremeshok** [comment]
in the code approx line 1800
````
  #do not remove the current_dbs
  #rm -f "$current_dbs"
````
uncomment the rm -f line.

**Comment by reneschuster** [comment]
No, that is not working and I get the following:

`cp: cannot stat ‘/var/lib/clamav-unofficial-sigs/configs/current-dbs.txt’: No such file or directory`

**Comment by Bakaras** [comment]
Hi,
here a patch for version 5.4

[remove_disabled_databases.patch.txt](https://github.com/extremeshok/clamav-unofficial-sigs/files/376142/remove_disabled_databases.patch.txt)

works for me.

**Comment by extremeshok** [comment]
Added to dev : 2fb8263d93fa382c6dbfbeff793c728aefd911e5 
Thanks
