### ISSUE TITLE
Anyone hit by Malware patrol MBL_3361776

### ISSUE THREAD

**Issue by olivier2557** [extremeshok/clamav-unofficial-sigs#106]
This is not directly linked to clamav-unoffcial but...

Between April 20th around 17:00 UTC and April 21th around 01:00 UTC, the rule MBL_3361776 of MalwarePatrol was classifying all my email as a virus. The rule was not there anymore in the 01:00 update.

I wonder if I was the only one affected.

**Comment by DavidGoodwin** [comment]
No. It hit me too ... :-(

**Comment by DavidGoodwin** [comment]
https://twitter.com/search?q=MBL_3361776%20&src=typd

**Comment by olivier2557** [comment]
Thanks. I am kind of angry at Malware Patrol, I emailed them and they did not even acknowledge their mistake.

**Comment by extremeshok** [comment]
alas, accidents do happen.
