### ISSUE TITLE
Problem with GPG Key after upgrading to 5.2.2

### ISSUE THREAD

**Issue by themaninspain** [extremeshok/clamav-unofficial-sigs#107]
HI,

Just upgraded to 5.2.2 and I get the following error message when the cron command runs:

> find: `/var/lib/clamav/gpg-key': Permission denied

These are the permissions on /var/lib/clamav/gpg-key

> ls -la /var/lib/clamav/gpg-key/
total 20
drwx------ 2 amavis amavis 4096 Jul 12  2015 .
drwxr-xr-x 6 amavis amavis 4096 Apr 27 17:43 ..
-rw-r--r-- 1 amavis amavis 1762 Jan 21  2009 publickey.gpg
-rw-r--r-- 1 amavis amavis    0 Jun  8  2010 secring.gpg
-rw-r--r-- 1 amavis amavis 1205 Jun  8  2010 ss-keyring.gpg
-rw-r--r-- 1 amavis amavis    0 Jun  8  2010 ss-keyring.gpg~
-rw-r--r-- 1 amavis amavis 1200 Jun  8  2010 trustdb.gpg

Googled the problem but did not find anything useful.

Any suggestions?

Thx

Alan

**Comment by extremeshok** [comment]
whats the full cron command ?

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by themaninspain** [comment]
Hi,

this is the command from the cron.d file

> 11 * * * * clamav /bin/bash /usr/local/bin/clamav-unofficial-sigs.sh > /dev/null

**Comment by nerijus** [comment]
So it is expected - you run your cron command as "clamav" user, while /var/lib/clamav/gpg-key directory has owner "amavis" and permissions "drwx------". Everything is correct, as clamav user has no access to /var/lib/clamav/gpg-key directory.

**Comment by extremeshok** [comment]
run the script with the --install-cron option on the command line and it
will generate a new cron for you.

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by themaninspain** [comment]
It gives the same result. I deleted the cron file and ran the command again. No change.
I put the following into the user.conf

> clam_user="amavis"
clam_group="amavis"

and ran the script with --install-cron option, now it works.
Strange how I didn't have this problem until now.

**Comment by extremeshok** [comment]
What OS ? or is this a pre-configured  mailserver setup ?

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by themaninspain** [comment]
Debian 7

**Comment by extremeshok** [comment]
if the user amavis is being used, then the default clamav and freshclam packages are not installed/used.

according to my debian 7 vm, the clamav database owner is "clamav" which is identical to the one specified in the os.debian.conf. If yours differs you will need to set the user and group

I have added checks to warn the user if the user and group does not exist.

ae069b2b313db3d4c0bd6634e145fc27baa8ecee
