### ISSUE TITLE
iptables

### ISSUE THREAD

**Issue by Spectrik** [extremeshok/clamav-unofficial-sigs#109]
I have set up firewall on our MX server. It allows common traffic like HTTP(S), DNS, ICMP, ... and of course all e-mail ports(POP(S), IMAS, SMTP,...). But i could not get database update...connections issues. So i tried to delete the rules and it worked. So i ask which ports do i need to allow to make the updates work?

**Comment by reneschuster** [comment]
For rsync you need to open TCP port 873

**Comment by Spectrik** [comment]
Thank you very much for such a quick answer. I'll try it.

**Comment by extremeshok** [comment]
Added to readme in 7023c92b06bb9f87a67f2954b848bb5b052c5d0b 
@reneschuster thank you.
