### ISSUE TITLE
Are antidebug_antivm.yar & malicious_document.yar usable at all?

### ISSUE THREAD

**Issue by mailjol** [extremeshok/clamav-unofficial-sigs#112]
Hi,

From what I could read on Google, ClamAV has limitations in processing yara rules and I see these errors everytime I run clamscan:

LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 497 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 512 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 528 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 544 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 557 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 603 undefined identifier "pe"
LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 614 undefined identifier "pe"
LibClamAV Error: cli_loadyara: failed to parse rules file /var/lib/clamav/antidebug_antivm.yar, error count 7
LibClamAV Error: yyerror(): /var/lib/clamav/malicious_document.yar line 245 undefined identifier "uint32be"
LibClamAV Error: cli_loadyara: failed to parse rules file /var/lib/clamav/malicious_document.yar, error count 1

Is this a local issue or there is no point in fetching antidebug_antivm.yar & malicious_document.yar when ClamAV cannot use them? Can't find much help on web.

**Comment by donmichelangelo** [comment]
They are usable but I do not recommend them to use.
Especially malicious_documents produced false-positives.

If you are unsure, then check the rule files yourself since most yar rules are easy to interpret.

**Comment by mailjol** [comment]
Thanks for your response. But doesn't the error mean that ClamAV is unable to load the yar files? So how come they are usable in ClamAV?

**Comment by extremeshok** [comment]
What's your exact clamav version ?

**Comment by mailjol** [comment]
Hi.

I have tried with both the official repo version on Debian wheezy:

root@dev:~# dpkg -l | grep clamav
ii  clamav                               0.99+dfsg-0+deb7u2                i386         anti-virus utility for Unix

and a self compiled one from the latest source:

root@dev:~/clamav-0.99.2/clamscan# ./clamscan -V
ClamAV 0.99.2

Both show the same errors in loading antidebug_antivm.yar & malicious_document.yar.

https://github.com/Yara-Rules/rules/issues/105

says its not supported?

**Comment by donmichelangelo** [comment]
Looks like as this is the case.

However, certain Yara Rules are usable via Clam 0.99 but just those, that are affected by such yet unsupported modules like PE will most likely NOT work.

**Comment by mailjol** [comment]
So the error isn't a indication that entire yar files are being skipped from loading? In which case its better to disable them in config.

**Comment by donmichelangelo** [comment]
Afaik the rules are still being loaded from the Yar file as long they are fully supported by ClamAV, but those that need the PE module won't work yet.

**Comment by donmichelangelo** [comment]
You can close this issue here.

Have the issue reported at ClamAV's Bugzilla:
https://bugzilla.clamav.net/show_bug.cgi?id=11567

> This was a design decision, that it was better to load as many rules as possible for the initial yara rollout in ClamAV.

**Comment by extremeshok** [comment]
So to summarize, do I need to remove or add any yara rules from the default configs ?

Or change any of the false positive ratings ?

Thanks

**Comment by donmichelangelo** [comment]
No, you don't need to remove the Yara files.

They are all being loaded, except Rules from a rule file, that use modules that ClamAV doesn't currently supports.

**Comment by mailjol** [comment]
Which brings us to the original question:

Shouldn't antidebug_antivm.yar & malicious_document.yar be removed? Are they being loaded at all?

**Comment by extremeshok** [comment]
From my understanding: 

antidebug_antivm.yar contains 12 rules which uses the pe module (pe.imports), so only these 12 rules will be skipped/ignored, the rest of the rules will be loaded (113 loaded rules)

contains 5 rules which uses uint32be, so only these 5 rules will be skipped/ignored, the rest of the rules will be loaded (15 loaded rules)

So to answer the original question.

The rules are used and are loaded, even though a few of them fail due to no support.

**Comment by RobbieTheK** [comment]
Looks like there's a fix in https://bugzilla.clamav.net/show_bug.cgi?id=11567#c3 are any other changes needed?
