### ISSUE TITLE
Sanesecurity GPG Signature test FAILED

### ISSUE THREAD

**Issue by DamianoBianchi** [extremeshok/clamav-unofficial-sigs#114]
After some debug due to "GPG Signature test FAILED" error on every sanesecurity db I noticed that the exit code from gpg check is not correctly evaluated.

I applied the following patch:
```
1857c1857,1859
<             fi
---
> 	    else
> 	      ret="0"  
> 	    fi
```

**Comment by extremeshok** [comment]
@DamianoBianchi can you create a pull request to the dev branch ?

**Comment by extremeshok** [comment]
thanks 232f4fcea8474f62ad3ec0e83cf62fd6cf65a3c7
