### ISSUE TITLE
OSX user

### ISSUE THREAD

**Issue by agucova** [extremeshok/clamav-unofficial-sigs#116]
I can't seem to install the signatures on osx, I have to following error:
`ERROR: Either the user: clamav and/or group: virusgroup does not exist on the system.`
The default osx, config dictates:
`clam_user="clamav"
clam_group="virusgroup`
But an id of the user "clamav", gives:
`uid=82(_clamav) gid=82(_clamav) groups=82(_clamav),12(everyone),61(localaccounts),701(com.apple.sharepoint.group.2),401(com.apple.sharepoint.group.1),100(_lpoperator)
`
I tried again, with the group, "clamav", and it worked.

This is on a clean homebrew install (including gpg)

**Comment by agucova** [comment]
Now, I have another problem, the cron is running, but it is normal that the script has a line:
`50 * * * * clamav [ -x /usr/local/bin/clamav-unofficial-sigs.sh ] && /bin/bash /usr/local/bin/clamav-unofficial-sigs.sh > /dev/null`
Given, that at least for what I know, there is no such command as "clamav".

**Comment by extremeshok** [comment]
the clamav for the cron is the user the cron will run under.
ie run the command as the clamav user ;-P

**Comment by extremeshok** [comment]
will update the os x config

**Comment by extremeshok** [comment]
7621360597e94ac101091a3696e6e799d9dd0621
