### ISSUE TITLE
Ongoing integrity tested BAD - SKIPPING errors reported by clamscan 3.7.2-2 (ubuntu trusty lts)

### ISSUE THREAD

**Issue by Thorsten1976** [extremeshok/clamav-unofficial-sigs#12]
Clamscan reports SecuriteInfo honeynet.hdb database integrity tested BAD - SKIPPING
rsync: link_stat "/var/cache/clamav-unofficial-sigs/si-dbs/honeynet.hdb" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
Failed to successfully update SecuriteInfo production database file: honeynet.hdb - SKIPPING
Clamscan reports SecuriteInfo securiteinfobat.hdb database integrity tested BAD - SKIPPING
rsync: link_stat "/var/cache/clamav-unofficial-sigs/si-dbs/securiteinfobat.hdb" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
Failed to successfully update SecuriteInfo production database file: securiteinfobat.hdb - SKIPPING
Clamscan reports SecuriteInfo securiteinfodos.hdb database integrity tested BAD - SKIPPING
rsync: link_stat "/var/cache/clamav-unofficial-sigs/si-dbs/securiteinfodos.hdb" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
Failed to successfully update SecuriteInfo production database file: securiteinfodos.hdb - SKIPPING
Clamscan reports SecuriteInfo securiteinfoelf.hdb database integrity tested BAD - SKIPPING
rsync: link_stat "/var/cache/clamav-unofficial-sigs/si-dbs/securiteinfoelf.hdb" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
Failed to successfully update SecuriteInfo production database file: securiteinfoelf.hdb - SKIPPING
Clamscan reports SecuriteInfo securiteinfooffice.hdb database integrity tested BAD - SKIPPING
rsync: link_stat "/var/cache/clamav-unofficial-sigs/si-dbs/securiteinfooffice.hdb" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
Failed to successfully update SecuriteInfo production database file: securiteinfooffice.hdb - SKIPPING
Clamscan reports SecuriteInfo securiteinfopdf.hdb database integrity tested BAD - SKIPPING
rsync: link_stat "/var/cache/clamav-unofficial-sigs/si-dbs/securiteinfopdf.hdb" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
Failed to successfully update SecuriteInfo production database file: securiteinfopdf.hdb - SKIPPING
Clamscan reports SecuriteInfo securiteinfosh.hdb database integrity tested BAD - SKIPPING
rsync: link_stat "/var/cache/clamav-unofficial-sigs/si-dbs/securiteinfosh.hdb" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
Failed to successfully update SecuriteInfo production database file: securiteinfosh.hdb - SKIPPING

**Comment by extremeshok** [comment]
Is this with the latest version and source ?

**Comment by Thorsten1976** [comment]
The latests stable from Ubuntu trusty (14.04.2 LTS / Server): 
clamav-unofficial-sigs (3.7.2-2)

**Comment by extremeshok** [comment]
Your not using our version.. Version 4.5.0 (updated 2015-06-23)

Remove the broken and out of date ubuntu ones and download the ones here.
