### ISSUE TITLE
winnow_phish_complete_url comment misleading?

### ISSUE THREAD

**Issue by IdahoPL** [extremeshok/clamav-unofficial-sigs#120]
There are two active entries in master.conf:

 # HIGH
winnow_phish_complete.ndb|HIGH  # Phishing and other malicious urls and compromised hosts **DO NOT USE WITH winnow_phish_complete_url**

and

winnow_phish_complete_url.ndb|LOWMEDIUMONLY  # Similar to winnow_phish_complete.ndb except that entire urls are used

Either comment on winnow_phish_complete.ndb is wrong or enabling both of them simultaneously is an error.

**Comment by extremeshok** [comment]
Why do you think that ?

**Comment by IdahoPL** [comment]
The comment on winnow_phish_complete.ndb suggest that this entry SHOULD NOT BE USED (with capital letters ;) together with winnow_phish_complete_url.ndb.

Both winnow_phish_complete.ndb and winnow_phish_complete_url.ndb are active. So either comment is misleading or one of those entries should not be enabled by default.

**Comment by dmb-ts** [comment]
Everything is as it should be.
winnow_phish_complete_url has LOWMEDIUMONLY and winnow_phish_complete has HIGH.

So on low and medium winnow_phish_complete_url is used and on high winnow_phish_complete.
