### ISSUE TITLE
rsync for additional databases broken 

### ISSUE THREAD

**Issue by xorpierre** [extremeshok/clamav-unofficial-sigs#122]
Rsync for additional databases does not work because of "--files from="$sanesecurity_include_dbs". Needs to be removed in Line 2685 to work for all custom databases

**Comment by extremeshok** [comment]
Will push a fix.

What additional databases are you using ?

**Comment by xorpierre** [comment]
custom/own ones

**Comment by extremeshok** [comment]
thanks, fixed in 63fbf3ed6e9b26786d5065f664c8e154ef0bd5ff
