### ISSUE TITLE
CRDF removal

### ISSUE THREAD

**Issue by Sanesecurity** [extremeshok/clamav-unofficial-sigs#124]
CRDF signatures should now be removed from the config file etc. as they are no longer
distributed.

I'll keep the database on the mirrors (but blank) for older scripts.

Cheers,

Steve
Sanesecurity.com

**Comment by extremeshok** [comment]
will have this update done shortly. Want to roll it out with Solaris support.

**Comment by extremeshok** [comment]
Seems to the me the CRDF https://threatcenter.crdf.fr/ has gone commercial only. 

Will see if I can add commercial support for it.

**Comment by extremeshok** [comment]
Removed in d5a31abe5c65dd5df387554627ed0bcce449601b

**Comment by Sanesecurity** [comment]
Thanks... 

>Will see if I can add commercial support for it.

CDRF sigs are now being put into daily.cvd automatically now, so we don't need to do anything
else.

Thanks,

Steve
Sanesecurity.com
