### ISSUE TITLE
version 4.5 clamav-unofficial-sigs.sh error

### ISSUE THREAD

**Issue by stewardle** [extremeshok/clamav-unofficial-sigs#13]
Hi,
clamav-unofficial-sigs.sh line 1093
if [ "securiteinfo_enabled" == "yes" ] ; then
should be
if [ "$securiteinfo_enabled" == "yes" ] ; then
Steve

**Comment by extremeshok** [comment]
Thank you.

## Version 4.5.1 (updated 2015-07-16)
eXtremeSHOK.com Maintenance
Beta YARA rule support for sanesecurity
Config updated to 4.8 due to changes
Bugfix "securiteinfo_enabled" should be "$securiteinfo_enabled"
