### ISSUE TITLE
os.debian7.conf contains incorrect defaults

### ISSUE THREAD

**Issue by thctlo** [extremeshok/clamav-unofficial-sigs#130]
Hai,  file os.debian7.conf contains 
clam_user="clamscan"
clam_group="clamscan"

which is not the debian default for clamav. 
please change it to : 

clam_user="clamav"
clam_group="clamav"

**Comment by extremeshok** [comment]
thanks, fixed 40725a69de6761fa2db54d2e06fd08166d7972ca
