### ISSUE TITLE
installer bug (cron) debian7

### ISSUE THREAD

**Issue by thctlo** [extremeshok/clamav-unofficial-sigs#132]
Hai, 

I installed as on : https://github.com/extremeshok/clamav-unofficial-sigs says. 
•Copy clamav-unofficial-sigs.sh to /usr/local/bin/
•Set 755 permissions on /usr/local/bin/clamav-unofficial-sigs.sh

( debian 7) 
the cron file  points to : /usr/local/sbin/clamav-unofficial-sigs.sh
( sbin ) which is in my opinion correct since this must be run by root. 

please adjust the main page of the site. : https://github.com/extremeshok/clamav-unofficial-sigs

**Comment by extremeshok** [comment]
the cron file detects the location of the script and will use this as the full path for the command.

As per the instructions, yes sbin is technically slightly more correct than bin, updated in : 513a8cf8a1223f35349b6e1805a4f60991c0fcc0
