### ISSUE TITLE
Additional yara rules in 2-nd level subdir download problem

### ISSUE THREAD

**Issue by c904370** [extremeshok/clamav-unofficial-sigs#133]
Hi,

There is a problem downloading additional yara rules when the rules are in the 2nd level of subdir (e.g.: https://github.com/Yara-Rules/rules/tree/master/malware/Operation_Blockbuster).

Regards

**Comment by extremeshok** [comment]
will code a fix

**Comment by stuartmarshallsmith** [comment]
If you don't mind a suggestion, the rules seem to have an index file, which can be pulled via

_wget https://github.com/Yara-Rules/rules/raw/master/index.yar_

The file format seems to be
`include "./malware/MALW_Andromeda.yar"`
`include "./malware/POS_LogPOS.yar"`
`include "./malware/APT_APT3102.yar"`
`include "./malware/MALW_Olyx.yar"`

Maybe that can be parsed?

I'm using an older version v5.4.1 ( 20 July 2016 ) so it doesn't look like any of the Yara rules are working for me.

**Comment by stuartmarshallsmith** [comment]
I'm considering just being super lazy and using git clone https://github.com/yara-rules/rules /var/lib/clamav to try and pull all the rules down at once and then including "rules/index.yar" in the master.conf file...  I'm not sure whether or not that would work, but it's certainly a "least-effort" attempt.

**Comment by extremeshok** [comment]
@stuartmarshallsmith I have an idea.. which im testing locally ;P
