### ISSUE TITLE
Add Shellcheck to Travis

### ISSUE THREAD

**Issue by szepeviktor** [extremeshok/clamav-unofficial-sigs#135]
Good afternoon!

Would you welcome some SC and POSIX and Bash related PR-s?

**Comment by szepeviktor** [comment]
E.g. `function xshok_array_count()` equlas `echo "$#"`

**Comment by szepeviktor** [comment]
`man_dir=$(echo "$man_dir" | sed 's:/*$::')` equals `man_dir="${man_dir%%/}"`

**Comment by szepeviktor** [comment]
`$rsync_bin --help | $grep_bin 'contimeout' > /dev/null` -> `$rsync_bin --help | $grep_bin -q 'contimeout'`

**Comment by FreeK** [comment]
I'd love to see some improvements regarding security, if the maintainer won't accept your PR, just let me know where I can find your repo.

Thanks!

**Comment by szepeviktor** [comment]
Please cherrypick from my fork
https://github.com/szepeviktor/clamav-unofficial-sigs/commits/master

**Comment by extremeshok** [comment]
@szepeviktor  Yes, thanks this has been on my todo list.

Pull requests/forks need to be of the dev version, I don't commit/pr to the master untill it passes all the tests.

master is kept as a stable release.

Dev is for development and testing

Please remember a few work arounds are needed to be complaint with solaris, freeebsd/openbsd, ubuntu/debian, centos, etc

**Comment by szepeviktor** [comment]
@extremeshok Could you [cherrypick](https://git-scm.com/docs/git-cherry-pick) or should I group my commit to PR-s?

**Comment by extremeshok** [comment]
Doesn't matter to me, I will take a look at the changes once I complete my work

Smaller commits and PR's are generally better as they pass build/tests, I accept them.

**Comment by szepeviktor** [comment]
Thanks. Actually it is hard for to group them.
I try 1 feature/commit or 1 feature/1-2 commits.

**Comment by szepeviktor** [comment]
Please consider adding SC to Travis after solving #136

**Comment by szepeviktor** [comment]
@extremeshok I finish with this comment
https://github.com/szepeviktor/clamav-unofficial-sigs/commit/c2db006119381778a5e521b20a356961e96f5d79

Proceeding after you reviewed them.
https://github.com/szepeviktor/clamav-unofficial-sigs/commits/master (this is your dev branch)

**Comment by extremeshok** [comment]
Merged the PR.

note: shellcheck is not always correct as there are certain instances where one needs to use a non recommended method. I will update travis to issue a warn but not a complete fail for shellcheck.

as to security fixes and ideas, always welcome

**Comment by extremeshok** [comment]
shellcheck added and shellcheck errors fixed 110c13b
