### ISSUE TITLE
What does xshok_array_count()?

### ISSUE THREAD

**Issue by szepeviktor** [extremeshok/clamav-unofficial-sigs#136]
Should the config variables be arrays?

```bash
linuxmalwaredetect_dbs="
### Linux Malware Detect https://www.rfxn.com/projects/linux-malware-detect/
# LOW
rfxn.ndb|LOW # HEX Malware detection signatures
rfxn.hdb|LOW # MD5 malware detection signatures
" #END LINUXMALWAREDETECT DATABASES

function xshok_array_count () { # array
  k_array=( "$@" )
  if [ -n "${k_array[*]}" ] ; then
    i="0"
    for k in "${k_array[@]}" ; do
      let i=$i+1;
    done
    echo "$i"
  else
    echo "0"
  fi
}

count() {
  echo "$#"
}

count "$linuxmalwaredetect_dbs"
xshok_array_count "$linuxmalwaredetect_dbs"
```

output: 1 and 1

**Comment by szepeviktor** [comment]
Or should we convert multiline variables to arrays? One element per array.

**Comment by extremeshok** [comment]
As per the code comment:

# Count array elements and output the total element count
# required due to compound array assignment
# Usage:
# array=( "one" "two" "three" )
# xshok_array_count $array
# 3

**Comment by extremeshok** [comment]
echo "$#" will not work on compound array assignment

**Comment by extremeshok** [comment]
Redone the code, busy updating the logic to work with declared arrays

**Comment by extremeshok** [comment]
I will upload it once I am done

**Comment by extremeshok** [comment]
completed 110c13b
