### ISSUE TITLE
default_dbs_rating is not chekced

### ISSUE THREAD

**Issue by szepeviktor** [extremeshok/clamav-unofficial-sigs#137]
Maybe `default_dbs_rating="${default_dbs_rating:-LOW}"`

**Comment by szepeviktor** [comment]
Also: clam_user, clam_group

**Comment by extremeshok** [comment]
It assumes the master.conf is always present and correct to add/initialise system defaults and varibles..
The os.conf and user.conf are the only files which should be modified and these values override the defaults.
