### ISSUE TITLE
Feature request: suppress banner when output silenced

### ISSUE THREAD

**Issue by orlitzky** [extremeshok/clamav-unofficial-sigs#14]
We run this in a cron job, so I have all of the output silenced:

```bash
silence_ssl="yes"
curl_silence="yes"
rsync_silence="yes"
gpg_silence="yes"
comment_silence="yes"
```

But, I still get this email every hour:

<pre>
======================================================================
 eXtremeSHOk.com ClamAV Unofficial Signature Updater
 Version: v4.5.3 (12 August 2015)
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
======================================================================
</pre>

Would it be possible to hide the banner if all of the "silence" variables are `true`? Thanks!

(I did try `exec 1 > /dev/null` but that caused another problem.)

**Comment by extremeshok** [comment]
add the following to the end of your cron command              
2&1> /dev/null

**Comment by orlitzky** [comment]
I didn't think that would work since I was running the command as an argument to `su -c ...`. Well it works fine, duh. Thanks.
