### ISSUE TITLE
Make CI work

### ISSUE THREAD

**Issue by szepeviktor** [extremeshok/clamav-unofficial-sigs#143]
As trusty's clamav version is less than 0.99:
Please add https://launchpad.net/~teward/+archive/ubuntu/clamav

`LC_ALL=en_US.UTF-8 sudo add-apt-repository ppa:teward/clamav -y`
https://docs.travis-ci.com/user/installing-dependencies/

**Comment by szepeviktor** [comment]
And please consider cleaning up commented code in `.travis.yml`.

**Comment by szepeviktor** [comment]
In #144 I use clamav 0.99 from wheezy-updates.

**Comment by extremeshok** [comment]
#150
