### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by szepeviktor** [extremeshok/clamav-unofficial-sigs#147]
I am willing to contribute a shell script that puts together a lintian warning free .deb package.

**Comment by SaiGonSeamus** [comment]
That would be great.

**Comment by rimas-kudelis** [comment]
@szepeviktor do you have any updates?

**Comment by szepeviktor** [comment]
No but it would take 20 minutes by following https://github.com/extremeshok/clamav-unofficial-sigs#quick-install-guide

**Comment by extremeshok** [comment]
If you would like to, I could add it to the travis to automatically build and upload the .deb
