### ISSUE TITLE
Pfsense

### ISSUE THREAD

**Issue by SaiGonSeamus** [extremeshok/clamav-unofficial-sigs#153]
This thread on the Pfsense forum seems to have gone dead.

https://forum.pfsense.org/index.php?topic=115194.0

I would be very interested in getting the best clamav implemention, (yara rules, diverse sigs, etc) working on Pfsense. Any idea how we could advance this.

Best regards

S

**Comment by extremeshok** [comment]
Will add pfsense support in the next version
