### ISSUE TITLE
problem with cron job 

### ISSUE THREAD

**Issue by themaninspain** [extremeshok/clamav-unofficial-sigs#154]
I am getting an email message with an error on my server when the cron job runs:
Cron clamav@mail [ -x /usr/local/bin/clamav-unofficial-sigs.sh ] && /bin/bash /usr/local/bin/clamav-unofficial-sigs.sh > /dev/null

This is the message content:
/usr/local/bin/clamav-unofficial-sigs.sh: line 1057: service: command not found

The clamav-unoffical-sigs.log:
Aug 23 12:25:01 Preparing Databases
Aug 23 12:25:02 Tue Aug 23 12:25:02 CEST 2016 - Pausing database file updates for 249 seconds...
Aug 23 12:29:11 Tue Aug 23 12:29:11 CEST 2016 - Pause complete, checking for new database files...
Aug 23 12:29:11 Sanesecurity Database & GPG Signature File Updates
Aug 23 12:29:11 Checking for Sanesecurity updates...
Aug 23 12:29:12 Sanesecurity mirror site used: bart.sas-systems.net 144.76.210.133
Aug 23 12:29:13 Testing updated Sanesecurity database file: junk.ndb
Aug 23 12:29:15 Clamscan reports Sanesecurity junk.ndb database integrity tested good
Aug 23 12:29:15 Successfully updated Sanesecurity production database file: junk.ndb
Aug 23 12:29:15 Testing updated Sanesecurity database file: phish.ndb
Aug 23 12:29:20 Clamscan reports Sanesecurity phish.ndb database integrity tested good
Aug 23 12:29:20 Successfully updated Sanesecurity production database file: phish.ndb
Aug 23 12:29:20 Testing updated Sanesecurity database file: rogue.hdb
Aug 23 12:29:21 Clamscan reports Sanesecurity rogue.hdb database integrity tested good
Aug 23 12:29:21 Successfully updated Sanesecurity production database file: rogue.hdb
Aug 23 12:29:21 Testing updated Sanesecurity database file: blurl.ndb
Aug 23 12:29:21 Clamscan reports Sanesecurity blurl.ndb database integrity tested good
Aug 23 12:29:21 Successfully updated Sanesecurity production database file: blurl.ndb
Aug 23 12:29:21 Testing updated Sanesecurity database file: foxhole_filename.cdb
Aug 23 12:29:21 Clamscan reports Sanesecurity foxhole_filename.cdb database integrity tested good
Aug 23 12:29:21 Successfully updated Sanesecurity production database file: foxhole_filename.cdb
Aug 23 12:29:21 Testing updated Sanesecurity database file: bofhland_cracked_URL.ndb
Aug 23 12:29:21 Clamscan reports Sanesecurity bofhland_cracked_URL.ndb database integrity tested good
Aug 23 12:29:21 Successfully updated Sanesecurity production database file: bofhland_cracked_URL.ndb
Aug 23 12:29:21 Testing updated Sanesecurity database file: phishtank.ndb
Aug 23 12:29:22 Clamscan reports Sanesecurity phishtank.ndb database integrity tested good
Aug 23 12:29:22 Successfully updated Sanesecurity production database file: phishtank.ndb
Aug 23 12:29:22 Testing updated Sanesecurity database file: porcupine.hsb
Aug 23 12:29:22 Clamscan reports Sanesecurity porcupine.hsb database integrity tested good
Aug 23 12:29:22 Successfully updated Sanesecurity production database file: porcupine.hsb
Aug 23 12:29:22 SecuriteInfo Database File Updates
Aug 23 12:29:22 Checking for SecuriteInfo updates...
Aug 23 12:29:22 Checking for updated SecuriteInfo database file: securiteinfo.ign2
Aug 23 12:29:23 No updated SecuriteInfo securiteinfo.ign2 database file found
Aug 23 12:29:23 ---
Aug 23 12:29:23 Checking for updated SecuriteInfo database file: securiteinfo.hdb
Aug 23 12:29:51 No updated SecuriteInfo securiteinfo.hdb database file found
Aug 23 12:29:51 ---
Aug 23 12:29:51 Checking for updated SecuriteInfo database file: javascript.ndb
Aug 23 12:29:53 No updated SecuriteInfo javascript.ndb database file found
Aug 23 12:29:53 ---
Aug 23 12:29:53 Checking for updated SecuriteInfo database file: securiteinfohtml.hdb
Aug 23 12:29:53 No updated SecuriteInfo securiteinfohtml.hdb database file found
Aug 23 12:29:53 ---
Aug 23 12:29:53 Checking for updated SecuriteInfo database file: securiteinfoascii.hdb
Aug 23 12:29:55 No updated SecuriteInfo securiteinfoascii.hdb database file found
Aug 23 12:29:55 ---
Aug 23 12:29:55 Checking for updated SecuriteInfo database file: securiteinfopdf.hdb
Aug 23 12:29:55 No updated SecuriteInfo securiteinfopdf.hdb database file found
Aug 23 12:29:55 ---
Aug 23 12:29:55 Checking for updated SecuriteInfo database file: securiteinfoandroid.hdb
Aug 23 12:29:56 No updated SecuriteInfo securiteinfoandroid.hdb database file found
Aug 23 12:29:56 No SecuriteInfo database file updates found
Aug 23 12:29:56 linuxmalwaredetect Database File Updates
Aug 23 12:29:56 Checking for linuxmalwaredetect updates...
Aug 23 12:29:56 Checking for updated linuxmalwaredetect database file: rfxn.ndb
Aug 23 12:29:57 No updated linuxmalwaredetect rfxn.ndb database file found
Aug 23 12:29:57 ---
Aug 23 12:29:57 Checking for updated linuxmalwaredetect database file: rfxn.hdb
Aug 23 12:29:59 No updated linuxmalwaredetect rfxn.hdb database file found
Aug 23 12:29:59 No linuxmalwaredetect database file updates found
Aug 23 12:29:59 Checking for MalwarePatrol updates...
Aug 23 12:29:59 MalwarePatrol  Database File Update
Aug 23 12:30:02 MalwarePatrol signature database (malwarepatrol.db) did not change - skipping
Aug 23 12:30:02 Yara-Rules Database File Updates
Aug 23 12:30:02 Checking for yararulesproject updates...
Aug 23 12:30:02 Checking for updated yararulesproject database file: EMAIL_Cryptowall.yar
Aug 23 12:30:02 No updated yararulesproject EMAIL_Cryptowall.yar database file found
Aug 23 12:30:02 ---
Aug 23 12:30:02 Checking for updated yararulesproject database file: antidebug_antivm.yar
Aug 23 12:30:03 No updated yararulesproject antidebug_antivm.yar database file found
Aug 23 12:30:03 ---
Aug 23 12:30:03 Checking for updated yararulesproject database file: EK_Angler.yar
Aug 23 12:30:03 No updated yararulesproject EK_Angler.yar database file found
Aug 23 12:30:03 ---
Aug 23 12:30:03 Checking for updated yararulesproject database file: EK_Blackhole.yar
Aug 23 12:30:03 No updated yararulesproject EK_Blackhole.yar database file found
Aug 23 12:30:03 ---
Aug 23 12:30:03 Checking for updated yararulesproject database file: EK_BleedingLife.yar
Aug 23 12:30:03 No updated yararulesproject EK_BleedingLife.yar database file found
Aug 23 12:30:03 ---
Aug 23 12:30:03 Checking for updated yararulesproject database file: EK_Crimepack.yar
Aug 23 12:30:04 No updated yararulesproject EK_Crimepack.yar database file found
Aug 23 12:30:04 ---
Aug 23 12:30:04 Checking for updated yararulesproject database file: EK_Eleonore.yar
Aug 23 12:30:04 No updated yararulesproject EK_Eleonore.yar database file found
Aug 23 12:30:04 ---
Aug 23 12:30:04 Checking for updated yararulesproject database file: EK_Fragus.yar
Aug 23 12:30:04 No updated yararulesproject EK_Fragus.yar database file found
Aug 23 12:30:04 ---
Aug 23 12:30:04 Checking for updated yararulesproject database file: EK_Phoenix.yar
Aug 23 12:30:05 No updated yararulesproject EK_Phoenix.yar database file found
Aug 23 12:30:05 ---
Aug 23 12:30:05 Checking for updated yararulesproject database file: EK_Sakura.yar
Aug 23 12:30:05 No updated yararulesproject EK_Sakura.yar database file found
Aug 23 12:30:05 ---
Aug 23 12:30:05 Checking for updated yararulesproject database file: EK_ZeroAcces.yar
Aug 23 12:30:05 No updated yararulesproject EK_ZeroAcces.yar database file found
Aug 23 12:30:05 ---
Aug 23 12:30:05 Checking for updated yararulesproject database file: EK_Zerox88.yar
Aug 23 12:30:05 No updated yararulesproject EK_Zerox88.yar database file found
Aug 23 12:30:05 ---
Aug 23 12:30:05 Checking for updated yararulesproject database file: EK_Zeus.yar
Aug 23 12:30:06 No updated yararulesproject EK_Zeus.yar database file found
Aug 23 12:30:06 No yararulesproject database file updates found
Aug 23 12:30:06 Update(s) detected, reloading ClamAV databases
Aug 23 12:30:06 ERROR: Failed to reload, trying again
Aug 23 12:30:06 ERROR: Failed to reload, forcing clamd to restart
Aug 23 12:30:06 ClamAV Restarted
Aug 23 12:30:06 Issue tracker : https://github.com/extremeshok/clamav-unofficial-sigs/issues
Aug 23 12:30:06       Powered By https://eXtremeSHOK.com 

Everything seems to be working.

Installed OS is Debian 8, clamav 0.99.2, systemd in use

**Comment by jectnet007** [comment]
pls where can i download crimepack that is not encrypted?

**Comment by adyspeed** [comment]
I got the same error with cron:
/usr/local/bin/clamav-unofficial-sigs.sh: line 1057: service: command not found

I think the error pop up when clamd service is not running but clam listen as daemon for amavis.
But it seems to update fine, although I am not very sure of it.

**Comment by extremeshok** [comment]
its because your using systemd, use the debian8.systemd.conf
