### ISSUE TITLE
Presence of dig command not checked

### ISSUE THREAD

**Issue by vits** [extremeshok/clamav-unofficial-sigs#157]
Hi, downloading of Sanesecurity rules requires dig command to be available, but script does not check its presence and gives incorrect error message - No Sanesecurity mirror sites found - Check for dns/connectivity issues

It would be nice to inform, that dig is required, or at least add this requirement to readme.

**Comment by extremeshok** [comment]
Script should fall back to host command if dig is not present.

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by vits** [comment]
Maybe it should, but I had problem on Ubuntu 16.04 without dig installed. I got above mentioned message in log file and no sanesecurity signatures downloaded. Looked into script source, found usage of dig command, installed it, and problem disappeared. So there is some problem with fallback, I guess.

**Comment by vits** [comment]
Ok, maybe problem is not dig, but host command script uses as fallback. What exactly is host command params? Or which line in script? I can check it to see results.

**Comment by vits** [comment]
Had more time to look into the issue. If dig is not available, fall back host command is used, no problem there. However host also is not installed by default on my minimal ubuntu distro. Maybe this is unique case and most distros have at least host installed. However it would be nice to add note in readme to check availability of dig or host before installing.

Thanks for great script, btw!

**Comment by extremeshok** [comment]
I will code a fail/check if as i assumed either dig or host is always
available.

What flavour of minimal ubuntu are you running ?

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by vits** [comment]
We have self-made ubuntu image for virtual containers.

**Comment by Geisterfahrer** [comment]
Hello,
same thing here on Debian 8.3 Vanilla. 
When installing on a minimum Debian-install both "dig" and "host"-command are missing. The script states that correctly during the databases' download process, but it would be nice to check the presence of the dnsbind-package (on Debian-based systems) during the install or as vits already stated at least list it as a prerequesite in the INSTALL-file.

And thank you for the great project, I really appreciate your work!

**Comment by extremeshok** [comment]
added checking for dig or host and wget or curl
