### ISSUE TITLE
SecuriteInfo 2015 free clamav signatures timeout 

### ISSUE THREAD

**Issue by Gazoo** [extremeshok/clamav-unofficial-sigs#16]
The default max_times in the config should be raised as the signatures for SecuriteInfo 2015 free clamav signatures will always timeout before completing because of the slowness of their servers and the size of some of their signature files (62.6M securiteinfo.hdb).

Speed times for reference:
Checking for updated SecuriteInfo database file: securiteinfo.hdb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 62.6M    0 62.6M    0     0   315k      0 --:--:--  0:03:23 --:--:--  410k
Testing updated SecuriteInfo database file: securiteinfo.hdb
Clamscan reports SecuriteInfo securiteinfo.hdb database integrity tested good
Successfully updated SecuriteInfo production database file: securiteinfo.hdb

**Comment by Gazoo** [comment]
Also it looks like there is no integrity checking on the signature database as I had a server timeout and the securiteinfo.hdb database was only 52M when the full complete database was supposed to be 62.6M?

I had to remove the incomplete databases from the locations below or else the incomplete database was always copied back to the /var/lib/clamav directory:
/usr/unofficial-dbs/si-dbs/securiteinfo.hdb
/var/lib/clamav-unofficial-sigs/dbs-si/securiteinfo.hdb

**Comment by extremeshok** [comment]
Have not had any issues with downloading, will look at adding some sort of resiliency and/or download validations.

**Comment by Gazoo** [comment]
Just did a fresh install on another server with the latest master (March 28th 2016). The SecuriteInfo rules still never get downloaded by default because they timeout because SecuriteInfo is too slow. I think we should adjust the default timeouts so that these will download:

Checking for updated SecuriteInfo database file: securiteinfo.hdb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.8M    0 28.8M    0     0   328k      0 --:--:--  0:01:29 --:--:--  357k
curl: (28) Operation timed out after 90000 milliseconds with 30302208 out of -1 bytes received
Failed curl connection to https://www.securiteinfo.com/get/signatures/ - SKIPPED SecuriteInfo securiteinfo.hdb update
------------------------------------------------------------
No updated SecuriteInfo securiteinfo.hdb database file found
------------------------------------------------------------

**Comment by Gazoo** [comment]
Also note that running clamav-unofficial-sigs.sh again results in No Sanesecurity database file updates found even though the securiteinfo.hdb file is missing? I guess the download validation still isn't added ?

**Comment by extremeshok** [comment]
Any ideas which curl options and their values work for you ?

**Comment by Gazoo** [comment]
Checking my other server configs it looks like I had set rsync_max_time="800" and curl_max_time="800". The full securiteinfo.hdb is 153 MB and it looks like their servers are pretty bogged down depending on which mirror you get.

From the master.conf it looks you have options like "remove_bad_database="yes" and keep_db_backup="no". Do you know why a timeout doesn't get flagged as a bad download ?

**Comment by extremeshok** [comment]
usually with a timeout the database would be ignored/skipped.

**Comment by extremeshok** [comment]
this should be fixed in 5.0.5

Open if there are issues.
