### ISSUE TITLE
Cant download junk.ndb

### ISSUE THREAD

**Issue by jbsky** [extremeshok/clamav-unofficial-sigs#161]
I use your script, but arrived to Junk.ndb, nothing happend and script switch to next Mirror.
But, I need Junk.ndb because clamav scan only mail....

😢

**Comment by jbsky** [comment]
Access to all Sanesecurity mirror sites failed - Check for connectivity issues
or signature database name(s) misspelled in the script's configuration file.

**Comment by extremeshok** [comment]
re-download and check your configs
