### ISSUE TITLE
id -g doesn't do what you think it does

### ISSUE THREAD

**Issue by cluesch** [extremeshok/clamav-unofficial-sigs#163]
In function `xshok_user_group_exists`, the script checks for the existence of the group with `id -g <groupname>`, but that is not what `id -g` does. This just works because most setups have the groupname the same as the username. 

When invoking `id -g` you still have to give it a user name, but it will return the gid of that user.

```ShellSession
[cluesch@localhost]~% id -g wheel
id: wheel: No such user
[cluesch@localhost]~% uname -a
Linux localhost 2.6.32-042stab116.2 #1 SMP Fri Jun 24 15:33:57 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux
[cluesch@localhost]~% 
```

A replacement would be
```Shell
grep -q "^$2:" /etc/group
```
This of course doesn't work if people have NIS or LDAP in use, but is otherwise portable.

**Comment by jpenney** [comment]
if `getent` is available it will check whatever is configured in `nsswitch.conf` and returns non-zero if the key doesn't exist.  

User:
```
getent passwd "$1" >/dev/null
```

Group:
```
getent group "$2" >/dev/null
```

**Comment by extremeshok** [comment]
replaced the group checking function @jpenney
