### ISSUE TITLE
MiscreantPunch099-Low

### ISSUE THREAD

**Issue by falon** [extremeshok/clamav-unofficial-sigs#165]
Hello,

 you could add this db:

`MiscreantPunch099-Low.ldb|MEDIUM # Detect dangerous macros`

 in **master.conf** (**sanesecurity_dbs** value).
See at [Sanesecurity News](http://sanesecurity.com/news/)

**Comment by extremeshok** [comment]
Done 2abf7e99299515ec32cf173c25c3ba27bdcfcf24
