### ISSUE TITLE
Errors starting Clamav

### ISSUE THREAD

**Issue by rlucassen2** [extremeshok/clamav-unofficial-sigs#166]
I installed CUS yesterday, I'm a CUS newbie, and this morning I got an update for clamav under Debian testing. This resulted in errors like these [error messages](http://tmp.xaq.nl/clamav-err.txt):

    [....] Starting ClamAV daemon: clamd LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 497 undefined identifier "pe"
    LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 512 undefined identifier "pe"
    LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 528 undefined identifier "pe"
    LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 544 undefined identifier "pe"
    LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 557 undefined identifier "pe"
    LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 603 undefined identifier "pe"
    LibClamAV Error: yyerror(): /var/lib/clamav/antidebug_antivm.yar line 614 undefined identifier "pe"
    LibClamAV Error: cli_loadyara: failed to parse rules file /var/lib/clamav/antidebug_antivm.yar, error count 7
    LibClamAV Error: yyerror(): /var/lib/clamav/winnow_malware.yara line 65 duplicate identifier "CryptoWall_Resume_phish"
    LibClamAV Error: yyerror(): /var/lib/clamav/winnow_malware.yara line 83 duplicate identifier "docx_macro"
    LibClamAV Error: cli_loadyara: failed to parse rules file /var/lib/clamav/winnow_malware.yara, error count 2

    version installed:

    dpkg -l | awk '/clamav/ {print $2"\t"$3}'
    clamav  0.99.2+dfsg-6
    clamav-base     0.99.2+dfsg-6
    clamav-daemon   0.99.2+dfsg-6
    clamav-freshclam        0.99.2+dfsg-6
    libclamav7:i386 0.99.2+dfsg-6

I have no idea if this error occured in the previous version, there's nothing I can find in the logs about this issue. Everything seems to work fine, there are no error messages in the clamav logs or mail logs. Anyone a hint?

Richard.

**Comment by nerijus** [comment]
Please paste error messages in the issue instead of linking to external site.

**Comment by rlucassen2** [comment]
Done

**Comment by nerijus** [comment]
According to https://github.com/Yara-Rules/rules/issues/79 , "modules" are not supported by ClamAV.

**Comment by rlucassen2** [comment]
According to master.conf, it should be enabled:

    yararulesproject_enabled="yes"   # Yara-Rule Project, automatically disabled if clamav is older than 0.99

Note: I user debian8.conf as os.conf, but AFAICS everything mentioned there is the same in Debian9 (Stretch)

But when I disable the

    yararulesproject_enabled="no"
    enable_yararules="no"

I still get the same errors.

R.

**Comment by rlucassen2** [comment]
I removed the antidebug_antivm.yar file and the EMAIL_Cryptowall.yar file and commented these out in master.conf. Amavis restarts without any errors. Is this the right thing to do at the moment? Or should I do away with the winnow_malware.yara file instead of EMAIL_Cryptowall.yar?

BTW, these are the two files with the same stanza names:

    13:rule CryptoWall_Resume_phish : mail
    ./EMAIL_Cryptowall.yar
    47:rule CryptoWall_Resume_phish
    ./winnow_malware.yara
    
    44:rule docx_macro : mail
    ./EMAIL_Cryptowall.yar
    75:rule docx_macro
    ./winnow_malware.yara

R.

**Comment by nerijus** [comment]
As I wrote, apparently yara modules are unsupported. Other yara rules are supported.
http://blog.clamav.net/2015/06/clamav-099b-meets-yara.html:
YARA rules using any of the following features will be flagged in error, and the respective rules will be disabled:
...
Modules – A YARA feature intended to provide modular extensions to the YARA core. Modules are normally activated using the import keyword. 

So you don't have to do anything, unsupported rules are disabled and unused.

**Comment by rlucassen2** [comment]
Ok, thnx! I'll re-enable them!

R.

**Comment by szepeviktor** [comment]
Recent Travis result also shows: https://travis-ci.org/extremeshok/clamav-unofficial-sigs/builds/211193992#L1123

**Comment by extremeshok** [comment]
Busy with a fix, just sorting out the general travis issues. Then ill move to the fix

**Comment by RobbieTheK** [comment]
Does this fix take care of the issue? https://bugzilla.clamav.net/show_bug.cgi?id=11567#c3
