### ISSUE TITLE
WARNING: SCRIPT CONFIGURATION HAS NOT BEEN COMPLETED

### ISSUE THREAD

**Issue by jmfoleyjr** [extremeshok/clamav-unofficial-sigs#167]
This is probably silly/simple, but I can't figure it out. I've downloaded clamav-unofficial-sigs-master.zip from sanesecurity and am attempting to install. I've followed the README.md instructions (I believe) and ran the various:

  clamav-unofficial-sigs.sh --install-cron
  clamav-unofficial-sigs.sh --install-logrotate
  clamav-unofficial-sigs.sh --install-man

scripts as specified, but I get:

$ clamav-unofficial-sigs.sh --install-cron
################################################################################
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v5.4.1 (20 July 2016)
 Required Configuration Version: v65
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
=======================================================
Loading config: /etc/clamav-unofficial-sigs/master.conf
=======================================================
===================================================
Loading config: /etc/clamav-unofficial-sigs/os.conf
===================================================
=====================================================
Loading config: /etc/clamav-unofficial-sigs/user.conf
=====================================================
****************************************************
WARNING: SCRIPT CONFIGURATION HAS NOT BEEN COMPLETED
****************************************************

Can someone point in the right direction? If this is not the proper place to post this, can you redirect me thither?

**Comment by freeblue** [comment]
When you finish to configure clamav-unofficial-sigs to your taste, uncomment the following line in user.conf file
#user_configuration_complete="yes"

Regards,
Alex

**Comment by extremeshok** [comment]
@freeblue thanks and 100% correct
