### ISSUE TITLE
rsync /var/lib/clamav*

### ISSUE THREAD

**Issue by rlucassen2** [extremeshok/clamav-unofficial-sigs#168]
I once read somewhere that the downloaded signature files could be rsynced to another instance but I can't find it anymore. On a server that downloads the files using the clamav-unofficial-sigs.sh script, I see that AFAIK these two dirs are being used:

    /var/lib/clamav
    /var/lib/clamav-unofficial-sigs/

In the first directory, there are also clamav files which are downloaded by the freshclam util. The second dir is used by clamav-unofficial-sigs. Although quite a lot of files seem to be the same on different servers, there are also some differences between files, e.g. the /var/lib/clamav-unofficial-sigs/ dir.

Is there a document somewhere that tells me how to rsync a slave from a master? Can anyone shine a light on this matter. I think it is A Good Thing to minimize the load on the appropiate servers when things can be distributed internally.

Richard.

**Comment by extremeshok** [comment]
Rsync the /var/lib/clamav if you will be using the same signatures accross all yourservers.
