### ISSUE TITLE
FIXME in  the code

### ISSUE THREAD

**Issue by szepeviktor** [extremeshok/clamav-unofficial-sigs#169]
Lot of project maintainers [open tickets themselves](https://github.com/extremeshok/clamav-unofficial-sigs/issues/created_by/extremeshok).

```bash
# TO FIX:
$(echo "$db_name" | cut -d "|" -f2) ---> ${db_name#*|}
man_dir=$(echo "$man_dir" | sed 's:/*$::') ---> shopt -s extglob; man_dir="${man_dir%%+(/)}" 
````

**Comment by extremeshok** [comment]
+1 ;P

**Comment by szepeviktor** [comment]
Is it OK for you to close this issue before fixing those two thing?

**Comment by extremeshok** [comment]
They are already done (ie line 364 and 1569 )
