### ISSUE TITLE
GPG verification is always disabled

### ISSUE THREAD

**Issue by orlitzky** [extremeshok/clamav-unofficial-sigs#180]
Hello =)

In commit f36e3bf467, you introduced some additional checks for GPG. Sadly there is a typo:

```bash
  if [ -x "$gpg_bin" ] ; then
    enable_gpg="no"
  fi
```

If the gpg binary is executable, GPG is disabled. There should be a "!" in there somewhere.

**Comment by extremeshok** [comment]
thanks. released 5.6.2 with the fix
