### ISSUE TITLE
Logging and Logrotate

### ISSUE THREAD

**Issue by sackofspuds** [extremeshok/clamav-unofficial-sigs#19]
Hi

I found that in version 4.7 I had to do the following a few days after install because I was getting no logging:
mkdir /var/log/clamav-unofficial-sigs
chown -R clam:clam /var/log/clamav-unofficial-sigs/

I also had to make a change to /etc/logrotate.d/clamav-unofficial-sigs-logrotate
This:
     create 0600 root root
is now:
     create 0644 clam clam
because the /var/log/clamav-unofficial-sigs/clamav-unofficial-sigs.log file ended up being owned by root.

This was on CentOS 6.6 x64.

**Comment by extremeshok** [comment]
Thanks updated: 5489dac
