### ISSUE TITLE
clamd.scan.service:  Service lacks both ExecStart= and ExecStop= setting. Refusing.

### ISSUE THREAD

**Issue by stueja** [extremeshok/clamav-unofficial-sigs#190]
Arch Linux / systemd: the journal reports
```clamd.scan.service:  Service lacks both ExecStart= and ExecStop= setting. Refusing.```

The mentioned service file:
```
###################
# This is property of eXtremeSHOK.com
# You are free to use, modify and distribute, however you may not remove this notice.
# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
# License: BSD (Berkeley Software Distribution)
##################
#
# Script updates can be found at: https://github.com/extremeshok/clamav-unofficial-sigs
#
##################
.include /lib/systemd/system/clamd@.service

[Unit]
Description = Generic clamav scanner daemon
Wants=clamav-unofficial-sigs.timer

[Install]
WantedBy = multi-user.target

```

Also, there is neither `/lib/systemd/system/clamd@.service` nor any `clamd@.service` file anywhere else on my system.

How come?

**Comment by stueja** [comment]
Where was that fixed?

**Comment by stueja** [comment]
Not fixed until now but still closed?

**Comment by amishmm** [comment]
Archlinux (AUR) no more ships clamd.scan.service

https://aur.archlinux.org/cgit/aur.git/commit/?h=clamav-unofficial-sigs&id=e2a85a976b8fb719b03ef910f2499160ddb555a3

But ofcourse the file should either be removed or fixed. (its not required on Arch Linux)
