### ISSUE TITLE
Very bandwidth inefficient downloading

### ISSUE THREAD

**Issue by BondiChris** [extremeshok/clamav-unofficial-sigs#191]
The http/https downloader downloads all pattern files and then compares them with existing ones before deciding on an update. The total size of the securite downloads alone is now over 330MB, and the default configuration downloads them every 4 hours, for a total of 2.5GB per day or 77GB per month of downloaded data. I could configure to download only once a day, but then I will wait a lot longer for each update to be installed (on average).

I have done some checking which shows that the HTTP modified date header value can be used to decide if  the file has been updated and needs downloading. No data need be downloaded until the web server has a new modify date for the file.

I have partially implemented a fix which uses the --timestamping option for wget and the equivalent for curl. Are you interested in a patch?

**Comment by bytesplit** [comment]
Hi @BondiChris 

I've seen the same on my server. Took a while to find what is making all this traffic. I tried contacting Securite if they can supply rsync. They haven't answered at all. Your suggestion sounds interesting. Would you mind sharing your fix?

**Comment by BondiChris** [comment]
@bytesplit - I'm a bit snowed under at present, but I'll try to get a patch file as an attachment here as soon as I can. It's certainly reduced the impact on my download quota a lot.

**Comment by bytesplit** [comment]
@BondiChris - Thanks, really appreciated! I think many others will feel the same... at least whoever has the Securite list enabled.

**Comment by extremeshok** [comment]
I'm hoping to push some updates out this weekend, which will address the issues.

**Comment by BondiChris** [comment]
[clamav-unofficial-sigs-master-v5.6.2-timestamping.zip](https://github.com/extremeshok/clamav-unofficial-sigs/files/1241989/clamav-unofficial-sigs-master-v5.6.2-timestamping.zip)

A patch file is attached (v5.6.2) that has three intermingled components. Sorry it's a bit of a hack and hasn't been fully checked for portability. The basic ideas are portable.

1) use of the wget "-N" (--timestamping) argument or curl "--time-cond" to only fetch files with a more recent modify time than the installed copy - also requires "cp -p" to preserve timestamps when updating after download. May not be 100% portable to BSD systems, but fine with Linux I think.

2) extra logging of downloaded file sizes - works with Linux wget and curl at least

3) added a multihome host config option to choose for wget which local IP ($wget_bind_addr) or curl which local interface name ($curl_interface) to bind to.

Enjoy.

**Comment by securiteinfo** [comment]
Will we get a new version of the script to solve this issue ?

**Comment by chrcoluk** [comment]
I will test this patch on BSD to give peace of mind if anything breaks.

**Comment by nerijus** [comment]
I tried this patch, but it breaks Sanesecurity. With patch:
Sanesecurity Database & GPG Signature File Updates
Checking for Sanesecurity updates...
Sanesecurity mirror site used: web.virusfree.cz 212.24.139.164
Connection to web.virusfree.cz 212.24.139.164 failed - Trying next mirror site...
Sanesecurity mirror site used: sanesecurity.cl.cam.ac.uk 128.232.98.11
Connection to sanesecurity.cl.cam.ac.uk 128.232.98.11 failed - Trying next mirror site...
...
Sanesecurity mirror site used: resolv3.vianetworks.de 194.77.111.24
Connection to resolv3.vianetworks.de 194.77.111.24 failed - Trying next mirror site...
Access to all Sanesecurity mirror sites failed - Check for connectivity issues
or signature database name(s) misspelled in the script's configuration file.

Without patch:
Sanesecurity Database & GPG Signature File Updates
Checking for Sanesecurity updates...
Sanesecurity mirror site used: www.nethserver.org 188.226.251.154
Testing updated Sanesecurity database file: jurlbl.ndb
Clamscan reports Sanesecurity jurlbl.ndb database integrity tested good
Successfully updated Sanesecurity production database file: jurlbl.ndb
...

**Comment by BondiChris** [comment]
[nerijus](https://github.com/nerijus) said:
> I tried this patch, but it breaks Sanesecurity.

Hi nerijus,
I've been using it with Sanesecurity for 6 months now without any problems. It looks to me that you had some sort of downstream network issue when you tested it.

Can you repeat the problem, and can you post any log extract with more details of the failure reason.
Chris

**Comment by nerijus** [comment]
clamav-unofficial-sigs.log - https://paste.fedoraproject.org/paste/gH~l0CGE1idgQyrg9nGedg/
I patched yesterday 18:33 and unpatched today 11:29. As you can see, before patching and after unpatching it works, it does not work from yesterday 20:08:53 until today 10:04:50.
Just tried to patch again - the same problem.
I patched 5.6.2, not master, so I had to adapt the patch. Here's the script - https://paste.fedoraproject.org/paste/O8-yMitYt3gZtCu3PgJIhg/ and here's the patch I used - https://paste.fedoraproject.org/paste/dh4GQD~~p3cxmJbKorHzrw/

**Comment by BondiChris** [comment]
Hi nerijus,

What's really strange is that the Sanesecurity patterns are downloaded using rsync and the patch is to cut out unnecessary downloads that use wget or curl.

However, I see your version of the patch has introduced a configuration variable $rsync_address which is not in my version of clamav-unofficial-sigs. I think that may be where the failure is occurring. I don't know what $rsync_address is supposed to do, or what value it may have on your system, so I can't say for sure if that is the problem.

Chris

**Comment by BondiChris** [comment]
More exploration shows that you can also shrnk the HTTP transfer (especially important for the Securite files) by using a "`--compressed`" argument for curl, or adding "`--header 'Accept-Encoding: gzip'`" for wget. Typical compression ratios are above 60%, which is a big speedup.

An extra step is needed for wget to run gunzip on the downloaded data if the sending host has honoured the request to compress.

**Comment by extremeshok** [comment]
@BondiChris pity you did not do a pull request ;/ for the master

**Comment by extremeshok** [comment]
this is completed #88a1307ce075075cf45901ffd62b79e425add94f
compression and time-stamping is used for everything.
