### ISSUE TITLE
YARA.possible_includes_base64_packed_functions.UNOFFICIAL - falsepositive

### ISSUE THREAD

**Issue by Bugscz** [extremeshok/clamav-unofficial-sigs#195]
Hello, I have problem - almost every attachment is falsepositive tagged as spam with rule YARA.possible_includes_base64_packed_functions.UNOFFICIAL. How can I disable this problematic rule? ClamAV version is 0.99.2 and in user.conf is "yararulesproject_dbs_rating="DISABLE"" (previously was ="").

**Comment by Bugscz** [comment]
Tried grep -Ri /path/to/dbs -e 'YARA.possible_includes_base64' but nothing has found in db files...

**Comment by henkdeleeuw** [comment]
Has anyone found a solution yet?
This has such an impact that I consider dropping clamav-unofficial-sigs altogether.

**Comment by extremeshok** [comment]
enable_yararules="no"
