### ISSUE TITLE
remove clamav_ext support

### ISSUE THREAD

**Issue by chrcoluk** [extremeshok/clamav-unofficial-sigs#200]
might be an idea to remove support for this or at least add a warning to the config file comments that its no longer maintained, I was using this list for a while on a commercial malware patrol account I assumed its superior to the basic list.

Then I got some silly false positives.

Did some digging and ended up going to this url, which reports the list is abandoned since 2013

https://users.malwarepatrol.net/cgi/submit?action=list_clamav_ext

as far as I know clamav_basic is still valid

https://users.malwarepatrol.net/cgi/submit?action=list_clamav_basic does not report a discontinued message.

**Comment by kosli** [comment]
@extremeshok: What is the status of this? The (paid) malware patrol still has a clamav_ext list. And in the latest 0.7.1 clamav-unofficial-sigs the clamav_ext seems to work fine for me. What exactly is the difference between the basic and ext versions?
