### ISSUE TITLE
securiteinfo.hdb does not download

### ISSUE THREAD

**Issue by heutger** [extremeshok/clamav-unofficial-sigs#207]
The script hangs at

Checking for updated SecuriteInfo database file: securiteinfo.hdb

without any further response

**Comment by BondiChris** [comment]
@heutger - are you using my patch to only download when the file is newer than the copy you already have? It seems that Securite have done something to their web server that fails only on that file. I got around it be including an explicit "if modified since" header in the request.

I'll see if I can redo the patch...

**Comment by heutger** [comment]
I just found in the log, that the update works, it just takes from 15 up to 30 minutes. As I read something about a timeout and I thought, the script is hanging, I stopped it manually on my first tests via command line, e.g. on checking, how to enforce MalwarePatrol database to be loaded (see my other bug reported on that).

I'm not aware of a patch or on how to add if modified since. Seems to work currently, however, if the script could be updated to fix that, would be fine.

**Comment by securiteinfo** [comment]
Hello heutger,
2 possible ways :

1/ Why don't you use freshclam to download securiteinfo.com files ? More efficient, and avoid this issue : https://github.com/extremeshok/clamav-unofficial-sigs/issues/191

2/ Are you basic subscription ? Professionnal subscription has more bandwith to download files.

**Comment by heutger** [comment]
Hi,

hmmm, need to consider. However, I decided to use this script to avoid using freshclam...

Regards,
Christian

**Comment by securiteinfo** [comment]
This script is good for mbl or sanesecurity sigs but not needed for securiteinfo.com sigs.
