### ISSUE TITLE
MalwarePatrol different product code ignored

### ISSUE THREAD

**Issue by heutger** [extremeshok/clamav-unofficial-sigs#208]
I'm unsure why, but I got product code 32 instead of 8 and set 32 also in the user.conf, which is also finalized and loaded. However the script still tries to download with product code 8 resulting in an error message, resulting in no database get downloaded (just the few bytes of the error message).

**Comment by Jas0n99** [comment]
Me too, it looks like the product_code gets hard coded in the main script to "8" right before it assembles the fetch URL ... Not sure why... Easy enough to change in the script...

**Comment by fluser** [comment]
Please try it with these settings:
```
malwarepatrol_receipt_code="YOUR-RECEIPT-NUMBER"
malwarepatrol_product_code="32"
malwarepatrol_list="clamav_basic" # clamav_basic or clamav_ext
# Set to no to enable the commercial subscription url.
malwarepatrol_free="no"
```

The corresponding code: https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/clamav-unofficial-sigs.sh#L1883

I suggest to add an additional comment on line 86:
https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/config/master.conf#L86

```
# Set to no to enable the commercial subscriptoin url or
# if you have a product code other than 8.
malwarepatrol_free="yes"
```
