### ISSUE TITLE
When add whitelist: configs/monitor-ign.txt: No such file or directory

### ISSUE THREAD

**Issue by alessiocecchi** [extremeshok/clamav-unofficial-sigs#21]
Another small issue when try to add a whitelist:

# clamav-unofficial-sigs.sh -w
======================================================================
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v4.7 (16 October 2015)
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
======================================================================
Loading config: /etc/clamav-unofficial-sigs.conf

Input a third-party signature name that you wish to whitelist due to false-positives
and press enter (do not include '.UNOFFICIAL' in the signature name nor add quote
marks to the input string):
MBL_2904778
chmod: impossibile accedere a `/var/lib/clamav-unofficial-sigs/configs/monitor-ign.txt': No such file or directory
Signature 'MBL_2904778' has been added to my-whitelist.ign2

Problem solved with "touch /var/lib/clamav-unofficial-sigs/configs/monitor-ign.txt"

**Comment by extremeshok** [comment]
Hi

Thanks for reporting, fixed with commit 805b43c

**Comment by extremeshok** [comment]
Fixed in 429db10
