### ISSUE TITLE
clamav-unofficialsigs -w and MalwarePatrol

### ISSUE THREAD

**Issue by falon** [extremeshok/clamav-unofficial-sigs#212]
If I try to whitelist a MalwarePatrol signature (from file **malwarepatrol.db**), then the **my-whitelist.ign2** is bad formatted.

The row should contains the signature name only, it contains the entire hash instead.

For instance, if I whitelist the signature

`MBL_7271851`

then in the **my-whitelist.ign2** I will see

`MBL_7271851=65696361722e6f72672f646f776e6c6f6164`

in place of

`MBL_7271851`

The **malwarepatrol.db** contains the row

`MBL_7271851=65696361722e6f72672f646f776e6c6f6164`

so the entire row is taken, instead of the signature name only.

**Comment by extremeshok** [comment]
fixed: 9c2d28b
