### ISSUE TITLE
Cron email: /usr/local/bin/clamav-unofficial-sigs.sh: line 1090: service: command not found

### ISSUE THREAD

**Issue by jobst** [extremeshok/clamav-unofficial-sigs#214]
Hi
Getting the subject error message send in an email to account clam
Never looked at the mail box {clam} before, but it started on June 20 and happens every two hours.

Looking at the line:
`$clamd_restart_opt > /dev/null`
Tried to figure out where this is defined, do not know.
Seems to be defined externally but I do not know.

Now do I need to define this and if so where do I do that?
thanks

**Comment by Lynnwood** [comment]
I'm getting the same cron email referencing the same line. Can't seem to find cause. Just started getting these within last week.

**Comment by ERauch** [comment]
I was getting a related error on OSX.  Check your OS' .conf file.  There was an additional about 6 months ago for "clamd_restart_opt".  Evidently some OS flavors use a system service utility to restart clam, but others (including OSX) call clamscan directly.  On the systems where it gets called directly, many of the OS .conf files are missing the path to 'clamscan' in the 'clamd_restart_opt' variable's value (though they have it correctly in their 'clamscan_bin' assignment).
OSX:
  clamscan_bin="/usr/local/bin/clamscan"
  clamd_restart_opt="clamdscan --reload"
Should be:
  clamscan_bin="/usr/local/bin/clamscan"
  clamd_restart_opt="/usr/local/bin/clamdscan --reload"

If that's not it, than odds are it is that your system uses a different 'service' manager than what you os.conf file indicates (or else it just needs an explicit path added so the script can find it). 

Hmm... <This rabbit hole is dark and has many twists and branches the deeper I go...>
  Thinking on it a bit more: You may need to grant the script user/group access to your services manager, or change your PATH so it can be found, or...

**Comment by extremeshok** [comment]
fixed bb63206

**Comment by reubenjackson** [comment]
On my debian stretch installation the bin path is not local... possible typo above...

#Default Binaries & Commands
clamd_reload_opt="/usr/bin/clamdscan --reload"
uname_bin=$(which uname)
clamscan_bin=$(which clamscan)
rsync_bin=$(which rsync)
