### ISSUE TITLE
Cron email: Interrupted 

### ISSUE THREAD

**Issue by takenek** [extremeshok/clamav-unofficial-sigs#215]
Hello
I just install and i get e-mail with some errors:
/usr/local/sbin/clamav-unofficial-sigs.sh: line 2741: 56929 Interrupted               $clamscan_bin --quiet -d "$work_dir_yararulesproject/$db_file" "$work_dir_work_configs/scan-test.txt" 2> /dev/null
/usr/local/sbin/clamav-unofficial-sigs.sh: line 2741: 57116 Interrupted               $clamscan_bin --quiet -d "$work_dir_yararulesproject/$db_file" "$work_dir_work_configs/scan-test.txt" 2> /dev/null

Best Regards
TaKeN

**Comment by HansVanEijsden** [comment]
I have the same problem:

```
/usr/local/sbin/clamav-unofficial-sigs.sh: line 2741: 29110 Aborted                 $clamscan_bin --quiet -d "$work_dir_yararulesproject/$db_file" "$work_dir_work_configs/scan-test.txt" 2> /dev/null
```

For many months already, every 24 hours a cron error mail.
Debian Stretch, 64 bit.

**Comment by AndreaLeidi** [comment]
I also have this issue on Debian Stretch 64.
every day clamav-unofficial-sigs.log states:

> Oct 20 22:08:40 Yara-Rules Database File Updates
> Oct 20 22:08:40 Checking for yararulesproject updates...
> Oct 20 22:08:40 Checking for updated yararulesproject database file: antidebug_antivm.yar
> Oct 20 22:08:40 Testing updated yararulesproject database file: antidebug_antivm.yar
> Oct 20 22:08:40 Clamscan reports yararulesproject antidebug_antivm.yar database integrity tested BAD
> Oct 20 22:08:40 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-yara/antidebug_antivm.yar
> Oct 20 22:08:40 No updated yararulesproject antidebug_antivm.yar database file found`

**Comment by IsamuD** [comment]
Exact same problem here. Running clamav 0.100.2+dfsg-0+deb9u1 on Debian Stretch 64.

**Comment by AndreaLeidi** [comment]
Waiting for a fix, my workaround is simple and brutal: avoid the use of the whole yararules set.
In /etc/clamav-unofficial-sigs/user.conf
```
yararulesproject_enabled="no" 
enable_yararules="no"
```

**Comment by extremeshok** [comment]
#203
