### ISSUE TITLE
Feature "restart ClamD if detected not running" not works

### ISSUE THREAD

**Issue by alessiocecchi** [extremeshok/clamav-unofficial-sigs#22]
Hi,
sometimes clamd exit with an error during the database reload:

Thu Nov 12 18:33:18 2015 -> SelfCheck: Database modification detected. Forcing reload.
Thu Nov 12 18:33:18 2015 -> Reading databases from /var/lib/clamav
Thu Nov 12 18:33:35 2015 -> ERROR: reload db failed: Malformed database
Thu Nov 12 18:33:36 2015 -> Terminating because of a fatal error.
Thu Nov 12 18:33:36 2015 -> Pid file removed.
Thu Nov 12 18:33:36 2015 -> --- Stopped at Thu Nov 12 18:33:36 2015
Thu Nov 12 18:33:36 2015 -> Socket file removed.

In clamav-unofficial-sigs script there is a feature that can (should) solve this problem:

============
 If running clamd in "LocalSocket" mode (*NOT* in TCP/IP mode), and
 either "SOcket Cat" (socat) or the "IO::Socket::UNIX" perl module
 are installed on the system, and you want to report whether clamd
 is running or not, uncomment the "clamd_socket" variable below (you
 will be warned if neither socat nor IO::Socket::UNIX are found, but
 the script will still run).  You will also need to set the correct
 path to your clamd socket file (if unsure of the path, check the
 "LocalSocket" setting in your clamd.conf file for socket location).
clamd_socket="/tmp/clamd.socket"
clamd_socket="/var/run/clamav/clamd.sock"

 If you would like to attempt to restart ClamD if detected not running,
 uncomment the next 2 lines.  Enter the clamd service stop and  start command
 for your particular distro for the "start_clamd" "stop_clamd" variables
 (the sample start command shown below should work for most linux distros).
 NOTE: these 2 variables are dependant on the "clamd_socket" variable
 shown above - if not enabled, then the following 2 variables will be
 ignored, whether enabled or not.
clamd_start="service clamd start"
clamd_stop="service clamd stop"
============

but when clamd is not running clamav-unofficial-sigs return this error to stdout:

=================================================
Update(s) detected, reloaded ClamAV databases
=================================================
ERROR: Could not connect to clamd on 127.0.0.1: Connection refused

and in the log file log nothing:
[...]
nov 13 09:11:30 INFO - Update(s) detected, reloaded ClamAV databases

If I comment out in clamd.conf TCPAddr e TCPSocket the error is:

=================================================
Update(s) detected, reloaded ClamAV databases
=================================================
ERROR: Could not lookup : Servname not supported for ai_socktype

My SO is Centos 6 and I have installed socat and perl-IO-Socket-Timeout (from epel).

Can you check why this feature does not works?
Thanks

**Comment by extremeshok** [comment]
Busy working on a solution

**Comment by extremeshok** [comment]
Set the following config option, to solve your issue.
````
reload_opt="service clamd restart"
````
I'm working on adding  detection if the reload command fails.

**Comment by extremeshok** [comment]
New reload code in version 4.9
