### ISSUE TITLE
[MacOS] ClamAV not using signatures 

### ISSUE THREAD

**Issue by RhymeGuy** [extremeshok/clamav-unofficial-sigs#221]
Hi,

So I followed your instruction and I have successfully installed `clamav-unofficial-sigs`. However once I hit freshclam only the default signatures (from clamav server) gets updated. There is no sign of unofficial signatures.

I have tried to change DatabaseDirectory to point to `DatabaseDirectory /private/var/db/clamav-unofficial-sigs` but that didn't help.

IMHO, adding databases line by line is terrible idea, is there a better way maybe?
Am I missing something?

**Comment by extremeshok** [comment]
Ill have to test an OSX, can you point me to the guide you used to install clamav

**Comment by extremeshok** [comment]
Please follow these : https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/INSTALL

Re-open the issue if there is an issue afterwards
