### ISSUE TITLE
Malware Patrol link format changed

### ISSUE THREAD

**Issue by IulianStan** [extremeshok/clamav-unofficial-sigs#226]
Dears, 
Download link format for malware patrol change from:
https://lists.malwarepatrol.net/cgi/getfile?product=8&list=clamav_basic&receipt=xxxxx
to
https://lists.malwarepatrol.net/cgi/getfile?receipt=xxxxx&product=32&list=clamav_basic

Also the product code is hardcoded to 8 instead talking the value from config( in this case 32)

**Comment by extremeshok** [comment]
getfile?receipt=xxxxx&product=32&list=clamav_basic
is the same as 
getfile?product=32&list=clamav_basic&receipt=xxxxx

.. the malwarepatrol_product_code is ONLY hardcoded to 8, when malwarepatrol_free = "yes" or when malwarepatrol_product_code is empty

**Comment by IulianStan** [comment]
Dear, 
Thanks in the first place for the good job that you made with this script. 

Unfortunately for malwarepatrol_free the product code is no longer 8 but 32. Plus there is no reason to be hard-coded.(anyone can see it in the download link)
Please contact them or create an account yourself in order to see the situation.
