### ISSUE TITLE
typo bug in /usr/local/sbin/clamav-unofficial-sigs.sh

### ISSUE THREAD

**Issue by dominicraf** [extremeshok/clamav-unofficial-sigs#227]
Mis-spelling of $wget_compression in variable name:
[diff.txt](https://github.com/extremeshok/clamav-unofficial-sigs/files/3434909/diff.txt)

**Comment by Jas0n99** [comment]
I was just about to report this same bug!

Line 291: "$wget_compressionion" should be "$wget_compression"

Been reading over all the new updates. Lots and lots of little changes!
