### ISSUE TITLE
proxy for dig

### ISSUE THREAD

**Issue by almaz-free** [extremeshok/clamav-unofficial-sigs#230]
please, add "proxy" for dig utility to master.conf file, to allow bypass /etc/resolv.conf

something like:
```
dig_proxy_server="192.168.10.2"
dig_proxy_port="5353"
```

and in clamav-unofficial-sigs.sh
```
... dig ... @$dig_proxy_server -p $dig_proxy_port ...
```

**Comment by extremeshok** [comment]
Good idea, is a dig/dns proxy usually port 5353 ? 

I will also have to see if host support a proxy as well.

I will update the dev branch, but i dont want to push a another update to close to v6 until I know the bugs are fixed.

**Comment by almaz-free** [comment]
No, as far as i know, there is no 'proxy usually port' for dig.
From man dig:
```
dig [@server] ... [-p port#] ...

server      is the name or IP address of the name server to query.
            ...
            If no server argument is provided, dig consults /etc/resolv.conf
            ...

-p port     Send the query to a non-standard port on the server, instead of the default port 53.
```
But in my network configurations DNS server (proxy resolver) work on this port, and clamav-unofficial-sigs.sh not work until i manually add proxy for dig.

Also, from man host:
```
host ... {name} [server]

server      is an optional argument which is either the name or IP address of the name server that
            host should query instead of the server or servers listed in /etc/resolv.conf.
```

But i dont know, what about nonstandard port for host.

I run this:
host rsync.sanesecurity.net 192.168.10.2:5353

and got error:
host: couldn't get address for '192.168.10.2:5353': not found

**Comment by extremeshok** [comment]
done
