### ISSUE TITLE
Cron email about rfxn.ndb

### ISSUE THREAD

**Issue by HansVanEijsden** [extremeshok/clamav-unofficial-sigs#231]
First of all, thanks for the 6 update. I upgraded yesterday, first 6.0.0 then 6.0.1. All seems to work well.
I just received an email through cron though, with the following message:

Subject: 
`Cron <clamav@vps> [ -x /usr/local/sbin/clamav-unofficial-sigs.sh ] && /bin/bash /usr/local/sbin/clamav-unofficial-sigs.sh > /dev/null`

Content: 
```
2019-08-01 12:59:39 URL:http://cdn.rfxn.com/downloads/rfxn.ndb [451444/451444] -> "rfxn.ndb" [1]
2019-08-01 12:59:40 URL:http://cdn.rfxn.com/downloads/rfxn.hdb [851339/851339] -> "rfxn.hdb" [1]
```

Should I be worried? Or is everything fine?
If all is fine, is there a way to disable this particular cron email?

```
$ uname -a
Linux vps 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-4~bpo9+1 (2019-06-19) x86_64 GNU/Linux

# clamav-unofficial-sigs.sh --version
################################################################################
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v6.0.1 (2019-07-30)
 Required Configuration Version: v75
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################

# clamscan --version
ClamAV 0.100.3/25528/Thu Aug  1 10:29:44 2019
```

Thanks!

**Comment by extremeshok** [comment]
All good, unless its spamming the logs, there are no issues.
