### ISSUE TITLE
LOWMEDIUMONLY (winnow_phish_complete_url.ndb) isn't being processed...

### ISSUE THREAD

**Issue by Jas0n99** [extremeshok/clamav-unofficial-sigs#233]
I just noticed that I'm not downloading **winnow_phish_complete_url.ndb**, which is tagged as **LOWMEDIUMONLY** even though I'm using the MEDIUM setting. It looks like the tests in the main script is only comparing against the phrase **LOWMEDIUM**.

Actually the following 3 phrases look like there is no logic test for them: LOWMEDIUMONLY | MEDIUMHIGHONLY | HIGHONLY.

Anyhow, when changing the tests in clamav-unofficial-sigs.sh (Lines 413 & 417) from LOWMEDIUM to LOWMEDIUMONLY, then when the update is ran it includes **winnow_phish_complete_url.ndb** as expected.

**Comment by extremeshok** [comment]
thank you, will push a v6.0.2 update with the fixes.. Just waiting too see if there are more bug reports to fix
