### ISSUE TITLE
Unneeded messages mailed by cron (CentOS 7).

### ISSUE THREAD

**Issue by whataboutpereira** [extremeshok/clamav-unofficial-sigs#234]
I'm getting these messages mailed to me by the cron script, which it probably shouldn't, because there simply aren't any updates?

2019-08-04 10:22:59 URL:http://cdn.rfxn.com/downloads/rfxn.ndb [451444/451444] -> "rfxn.ndb" [1]
2019-08-04 10:22:59 URL:http://cdn.rfxn.com/downloads/rfxn.hdb [851339/851339] -> "rfxn.hdb" [1]

The corresponding log entries are:

Aug 04 10:22:59 linuxmalwaredetect Database File Updates
Aug 04 10:22:59 Checking for linuxmalwaredetect updates...
Aug 04 10:22:59 Checking for updated linuxmalwaredetect database file: rfxn.ndb
Aug 04 10:22:59 No updated linuxmalwaredetect rfxn.ndb database file found
Aug 04 10:22:59 ---
Aug 04 10:22:59 Checking for updated linuxmalwaredetect database file: rfxn.hdb
Aug 04 10:22:59 No updated linuxmalwaredetect rfxn.hdb database file found
Aug 04 10:22:59 No linuxmalwaredetect database file updates found

**Comment by whataboutpereira** [comment]
Now after 10 days I can say that I get mail from cron due to these errors 2-3 times a day.

**Comment by extremeshok** [comment]
should be sorted in next release

**Comment by whataboutpereira** [comment]
Should this fix be in the dev branch as well? Cron mails still contain these with the dev branch:

2019-08-20 09:58:38 URL:https://www.securiteinfo.com/get/signatures/<code>/securiteinfo.hdb [22193010/22193010] -> "securiteinfo.hdb" [1]
2019-08-20 09:59:32 URL:https://www.securiteinfo.com/get/signatures/<code>/javascript.ndb [16764303/16764303] -> "javascript.ndb" [1]
2019-08-20 10:00:31 URL:https://www.securiteinfo.com/get/signatures/<code>/securiteinfoascii.hdb [6846197/6846197] -> "securiteinfoascii.hdb" [1]

**Comment by whataboutpereira** [comment]
Now using the dev branch from yesterday and these messages still persist. The hourly version mismatch is now nicely gone though. :)

**Comment by extremeshok** [comment]
Any idea if the script is using curl or wget ?

**Comment by whataboutpereira** [comment]
I have both installed, but I suspect it's wget.
Manual wget displays: 2019-09-01 01:18:07 (6.21 MB/s) - ‘rfxn.hdb.1’ saved [851688/851688]
The significant bit: [851688/851688]. I don't see that notation with curl at all.

**Comment by extremeshok** [comment]
Could you please check the latest dev.

**Comment by whataboutpereira** [comment]
Updated to new dev version now, thanks.

**Comment by whataboutpereira** [comment]
So far so good. :)
