### ISSUE TITLE
Use more securiteinfo signatures

### ISSUE THREAD

**Issue by extremeshok** [extremeshok/clamav-unofficial-sigs#235]
@dominicraf

Can the script be adapted to also update/use the following securiteinfo files

spam_marketing.ndb

securiteinfoascii.hdb

securiteinfoandroid.hdb

securiteinfopdf.hdb
--

references https://github.com/extremeshok/spamassassin-extremeshok_fromreplyto/issues/11

**Comment by extremeshok** [comment]
This is all done by default, when a user adds the 
``` 
securiteinfo_authorisation_signature="YOUR-SIGNATURE-NUMBER"
```
to the user.conf

**Comment by dominicraf** [comment]
Actually spam_marketing.ndb is not obtained/updated by the script, and it turns out to be pretty good. I now update it using freshclam.

**Comment by extremeshok** [comment]
> Actually spam_marketing.ndb is not obtained/updated by the script, and it turns out to be pretty good. I now update it using freshclam.

6.1 should fix all the database update issues. Please check and open a new issue if there is still a bug
