### ISSUE TITLE
curl should have '--fail' in the command lines for proper error handling...

### ISSUE THREAD

**Issue by Jas0n99** [extremeshok/clamav-unofficial-sigs#236]
I actually discovered this issue with one of my own scripts...

You should include the **--fail** option in the curl command lines, otherwise curl doesn't return and error code (return value) for HTTP non-200 responses!

Here's their logic:
https://curl.haxx.se/docs/faq.html#curl_doesn_t_return_error_for_HT

Because cURL has to be extravagant and tick you off with their million command line switches....

**Comment by extremeshok** [comment]
thanks for this .. wow would of assumed default behavior would be to fail on non http 200... ;/
