### ISSUE TITLE
malwarepatrol receipt codes that contain a # break the script

### ISSUE THREAD

**Issue by dave64** [extremeshok/clamav-unofficial-sigs#24]
The first sed command here:

clean_config=`command sed -e 's/#.*$//' -e '/^\s*$/d' "$config_source"`

attempts to strip all the comments from the config file.  If the malwarepatrol receipt code happens to contain a #, it causes everything after that in the receipt code to be stripped, including the closing quote, which then causes the check for an even number of quotes to fail.

**Comment by extremeshok** [comment]
This will take allot of time to code/test a new regex.

I can code a small work around to sort the issue, could you please send me your receipt code to test with ? admin@extremeshok.com

**Comment by extremeshok** [comment]
Fixed in : fe8d84ecc74fb44d4f38022e05fde4599b79de8c

Completely new regex.
