### ISSUE TITLE
Script permissions in dev branch CentOS7 guide.

### ISSUE THREAD

**Issue by whataboutpereira** [extremeshok/clamav-unofficial-sigs#240]
I noticed the CentOS7 (guides/centos7.md) guide suggests setting world writable permissions on the script where 755 should suffice:

chmod 777 /usr/local/bin/clamav-unofficial-sigs.sh

**Comment by extremeshok** [comment]
Thanks, I rekon im ready to accept the pull , aka 6.1.0
