### ISSUE TITLE
selecting wrong os.conf

### ISSUE THREAD

**Issue by Stevehans** [extremeshok/clamav-unofficial-sigs#242]
The new code selects the wrong os.conf

find "/etc/clamav-unofficial-sigs" -type f -iname "os.conf" -o -iname "os.*.conf" | tail -n1
/etc/clamav-unofficial-sigs/os.centos6.conf

 ls /etc/clamav-unofficial-sigs/os*conf
/etc/clamav-unofficial-sigs/os.archlinux.conf        /etc/clamav-unofficial-sigs/os.macosx.conf
/etc/clamav-unofficial-sigs/os.centos6.conf          /etc/clamav-unofficial-sigs/os.openbsd.conf
/etc/clamav-unofficial-sigs/os.centos6-cpanel.conf   /etc/clamav-unofficial-sigs/os.opensuse.conf
/etc/clamav-unofficial-sigs/os.centos7-atomic.conf   /etc/clamav-unofficial-sigs/os.osx.conf
/etc/clamav-unofficial-sigs/os.centos7.conf          /etc/clamav-unofficial-sigs/os.pfsense.conf
/etc/clamav-unofficial-sigs/os.conf                  /etc/clamav-unofficial-sigs/os.raspbian.conf
/etc/clamav-unofficial-sigs/os.debian7.conf          /etc/clamav-unofficial-sigs/os.slackware.conf
/etc/clamav-unofficial-sigs/os.debian8.conf          /etc/clamav-unofficial-sigs/os.solaris10.conf
/etc/clamav-unofficial-sigs/os.debian8.systemd.conf  /etc/clamav-unofficial-sigs/os.solaris11.conf
/etc/clamav-unofficial-sigs/os.debian9.conf          /etc/clamav-unofficial-sigs/os.ubuntu.conf
/etc/clamav-unofficial-sigs/os.freebsd.conf          /etc/clamav-unofficial-sigs/os.zimbra.conf
/etc/clamav-unofficial-sigs/os.gentoo.conf

For now I'll just delete all the os*conf apart from os.conf

**Comment by extremeshok** [comment]
You should only have a single os.conf or the one which applies to your system in your /etc/clamav-unofficial-sigs/ dir.

ie. for debian 9 it would be "os.debian9.conf"

Script does not don't have os detection

**Comment by Stevehans** [comment]
Not if you follow the readme, you'll end up with all the confs and one renamed to os.conf?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by extremeshok** [comment]
Hi thanks for bringing that to my attention, I have redone all the docs will merger them soon
