### ISSUE TITLE
Default downloader_max_time too short for free securiteinfoold.hdb file

### ISSUE THREAD

**Issue by HansVanEijsden** [extremeshok/clamav-unofficial-sigs#249]
A free SecuriteInfo account can download with 300 kB/s. The securiteinfoold.hdb database is more than 300 MB, so it takes more than 15 minutes to download.
Now, the download always timeouts at 66%, because downloader_max_time has been set to 600 seconds by default.
My suggestion is to raise the default value to something like 1500, to give the download enough time to finish.

for me, putting this in user.conf was the solution:
`downloader_max_time="1500"`

Thanks!

**Comment by extremeshok** [comment]
securiteinfoold.hdb .. any idea if they allow mirroring of this file ?

**Comment by HansVanEijsden** [comment]
> securiteinfoold.hdb .. any idea if they allow mirroring of this file ?

When you go to https://www.securiteinfo.com/clients/customers/account and then, after login, click on FAQ, they say this:

```
Can I do mirorring of your signatures on my network server ?
Yes you can. But public mirroring of our signatures is prohibited !
```

So, I'm afraid not..

**Comment by extremeshok** [comment]
completed in the latest dev and the next version

**Comment by rajivml** [comment]
thanks @HansVanEijsden , I have also ran into the same issue
