### ISSUE TITLE
Documentation: Upgrading

### ISSUE THREAD

**Issue by ulab** [extremeshok/clamav-unofficial-sigs#250]
What is the "correct" way to upgrade the script? 
Is it necessary to remove everything first before installing an upgrade?
Is it enough to just replace the script?

**Comment by whataboutpereira** [comment]
Since there are only 4 pertinent files, it should be safe to replace them. Afterwards run the script one as a superuser and then with --install-all in case the script wants to install cron etc. differently.

**Comment by extremeshok** [comment]
replace the script
replace master.conf

Afterwards run the script one as a superuser and then with --install-all in case the script wants to install cron etc. differently.

**Comment by extremeshok** [comment]
I will add some docs

**Comment by ulab** [comment]
> Afterwards run the script one as a superuser and then with --install-all in case the script wants to install cron etc. differently.

That's why I was wondering if I was supposed to run it with --remove-script before replacing to make sure that there is no "different cron, etc" left.

**Comment by extremeshok** [comment]
btw, 6.2 will able to upgrade itself with 1 command.

**Comment by extremeshok** [comment]
dev branch contains the new docs as well as --upgrade support

All versions v6.2.0+ will have --upgrade support.

**Comment by oktayaa** [comment]
While you're at it please document on that page that the current upgrade instructions are for 6..2.0+ and earlier versions need to do it manually.
