### ISSUE TITLE
v6.1.1 ignores /etc/clamav-unofficial-sigs/os.conf

### ISSUE THREAD

**Issue by Th-Barth** [extremeshok/clamav-unofficial-sigs#251]
Hello,
since script version 6.1.1 the os.conf is being ignored on a debian 10 system. 

Here on debian 10 with new script

`
clamav-unofficial-sigs.sh --check-clamav
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v6.1.1 (2019-09-02)
 Required Configuration Version: v76
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com

Loading config: /etc/clamav-unofficial-sigs/master.conf
Loading config: /etc/clamav-unofficial-sigs/os.debian8.conf
Loading config: /etc/clamav-unofficial-sigs/user.conf
`

Here on debian 10 system with older script
`clamav-unofficial-sigs.sh --check-clamav

 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v6.0.1 (2019-07-30)
 Required Configuration Version: v75
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com

Loading config: /etc/clamav-unofficial-sigs/master.conf
Loading config: /etc/clamav-unofficial-sigs/os.conf
Loading config: /etc/clamav-unofficial-sigs/user.conf
`

I copied os.debian9.conf to /etc/clamav-unofficial-sigs/os.conf. So I decided to copy it into /etc/clamav-unofficial-sigs/os.debian8.conf as well. It s not a real problem, because debian 9/10 can also handle the clamd_restart_opt for debian 8. But I had to set the variable clamd_socket too.

**Comment by extremeshok** [comment]
os.***.conf takes precedence over os.conf.

This was done, so the rename of os.*.conf to os.conf is no longer needed.

**Comment by Th-Barth** [comment]
The older concept was better. So when I delete all os.*.conf files, the script will use os.conf again?

**Comment by extremeshok** [comment]
Yes

**Comment by extremeshok** [comment]
the latest dev and the next version will make os.conf take preference over os.*.conf
