### ISSUE TITLE
How to reduce reloading the databases?

### ISSUE THREAD

**Issue by Th-Barth** [extremeshok/clamav-unofficial-sigs#252]
Hi there,

where can change the value for reloading the databases? On my new server (debian 10) the databases are being reloaded every two hour. That takes up to two minutes and it often comes to a talking timeout to postfix when an email arrives or a client tries to send an email! The timeout of Postfix is 2 minutes! Clamav blocks everythings because it doesnt support multiple threads for reloading databases and scanning emails at the same time. 
On my older server (debian 9) the databases were downloaded once a day only with fewer signatures. I would like to disable the reloadings during business time. Is this possible?

less /var/log/clamav/clamav.log
Wed Sep  4 18:09:33 2019 -> Reading databases from /var/lib/clamav
Wed Sep  4 18:11:36 2019 -> Database correctly reloaded (10966428 signatures)
Wed Sep  4 20:06:03 2019 -> Reading databases from /var/lib/clamav
Wed Sep  4 20:08:00 2019 -> Database correctly reloaded (10966699 signatures)
Wed Sep  4 22:05:12 2019 -> Reading databases from /var/lib/clamav
Wed Sep  4 22:06:54 2019 -> Database correctly reloaded (10966733 signatures)
...

**Comment by extremeshok** [comment]
edit your frashclam configs and the cronjob to run once every 24hours.

Reloads are only done when there are database updates.

Best way to mitigate this entirely is to increase the server resources.

**Comment by extremeshok** [comment]
set these in your user conf for once per a day
```
sanesecurity_update_hours="24" 
securiteinfo_update_hours="24" 
linuxmalwaredetect_update_hours="24"
malwarepatrol_update_hours="24"
yararulesproject_update_hours="24" 
additional_update_hours="24"
```

**Comment by Th-Barth** [comment]
Yes, meanwhile I ve already found out that these are the settings to control the reloads. I ve got two master.conf for the standard and reduced reloadings. 

cronjobs
30 18 * * 1-5	cp -a /etc/clamav-unofficial-sigs/master.fast.conf /etc/clamav-unofficial-sigs/master.conf
30 7 * * 1-5	cp -a /etc/clamav-unofficial-sigs/master.slow.conf /etc/clamav-unofficial-sigs/master.conf

fast contains the standard settings and slow the reduced settings for business time range :-)

**Comment by extremeshok** [comment]
bad idea replacing or customizing master.conf
set your user.conf with the options, and replace as needed

**Comment by Th-Barth** [comment]
Ok! I wasnt sure  if I can overwrite all variables of the master.conf in user.conf.
