### ISSUE TITLE
Add URLhaus signatures

### ISSUE THREAD

**Issue by micah** [extremeshok/clamav-unofficial-sigs#256]
URLhaus provides signatures: https://urlhaus.abuse.ch/api/#clamav

they have a script that will automatically download them: https://github.com/abusech/urlhaus/blob/master/clamav.sh

it would be nice if this was integrated into clamav-unofficial-sigs so there wasn't a need for two scripts!

**Comment by extremeshok** [comment]
completed, please test the latest dev branch
