### ISSUE TITLE
SecuriteInfo initial download times out

### ISSUE THREAD

**Issue by micah** [extremeshok/clamav-unofficial-sigs#257]
The default timeout set for downloading wont let you actually download the SecuriteInfo files, because they cap the download speed at 349k and the securiteinfoold.hdb is 307M which takes about 15minutes to download at that speed. So you are only able to get about 66% of the file before the timeout kicks in.

I changed my local timeout to be increased for that so I can get past it, but maybe for new users, it might be good to have this timeout be higher.

**Comment by extremeshok** [comment]
i am working on a solution for the initial run
