### ISSUE TITLE
is my mirror still needed?

### ISSUE THREAD

**Issue by thetuxinator** [extremeshok/clamav-unofficial-sigs#259]
Hi everybody,

I could not find any mirror list in the code, so i ask here, i am the guy who early begun to mirror this service back in the days, as i want to migrate my server to a new one, i wanted to check if my mirror is somewhere in the code.

However i found nothing.

Any thought's?

kind regards, Mike aka tuxinator

**Comment by extremeshok** [comment]
What is the mirror ?

**Comment by thetuxinator** [comment]
somehost.tuxinator.org

**Comment by thetuxinator** [comment]
srv4.tuxinator.org or f171.tuxinator.org

**Comment by extremeshok** [comment]
Not needed, push a pull request if you ever want to enable it
