### ISSUE TITLE
Wrong clamav user in logrotate file for Debian based systems

### ISSUE THREAD

**Issue by reneschuster** [extremeshok/clamav-unofficial-sigs#26]
On Debian based systems the logrotate will not work, because the user clam does not exist (line 23). On Debian it's the user clamav.

**Comment by extremeshok** [comment]
added a comment to the log-rotate file ..

Im considering adding an option to generate the logrotate and cron entries directly via the script with a command.

**Comment by extremeshok** [comment]
7ebde7a65e248f152edace2fa55cba81f6c2a0be
