### ISSUE TITLE
/usr/sbin/clamav-unofficial-sigs.sh: line 2917: 27708 Aborted

### ISSUE THREAD

**Issue by takenek** [extremeshok/clamav-unofficial-sigs#262]
Hello,
I got many errors on e-mail like this:
/usr/local/sbin/clamav-unofficial-sigs.sh: linia 2917: 27708 Przerwane               $clamscan_bin --quiet -d "${work_dir_yararulesproject}/${db_file}" "${work_dir_work_configs}/scan-test.txt" 2> /dev/null

Anyone know what is wrong? I use last version of this script.

root@POCZTA:/usr/local/sbin# md5sum clamav-unofficial-sigs.sh
22dfc4fd2a41b2aa7785e0c8edf287be  clamav-unofficial-sigs.sh

**Comment by extremeshok** [comment]
any more information ?

**Comment by extremeshok** [comment]
please open if you still have an issue

**Comment by maurodeca** [comment]
I also have the same error daily by email:
`/usr/local/sbin/clamav-unofficial-sigs.sh: line 3241: 12225 Aborted                 $clamscan_bin --quiet -d "${work_dir_yararulesproject}/${db_file}" "${work_dir_work_configs}/scan-test.txt" 2>&10`

script version is 7.0.1
ClamAV 0.100.2
