### ISSUE TITLE
Featurerequest: os.alpine.conf

### ISSUE THREAD

**Issue by odo2063** [extremeshok/clamav-unofficial-sigs#263]
Hi!

Since clamav is supported in Nextcloud and many Nextcloud-Container are build up on Alpinelinux it would be nice to have your great work in those containers without hassle.

**Comment by extremeshok** [comment]
On my list of things todo... 

https://hub.docker.com/u/extremeshok

**Comment by odo2063** [comment]
Thank you very much!
