### ISSUE TITLE
systemd.timer .... for people who dont like Mr cron 

### ISSUE THREAD

**Issue by skywatcher78** [extremeshok/clamav-unofficial-sigs#264]
Hi,
after installing on Ubuntu 18.04 the script doesn't start automatically after booting.
Neither clamav-unofficial-sigs.service nor clamav-unofficial-sigs.timer gets startet. Both give this output when asking the system for the status:

```
systemctl status clamav-unofficial-sigs.service
● clamav-unofficial-sigs.service - Clamav Unofficial Sigs Update service
   Loaded: loaded (/etc/systemd/system/clamav-unofficial-sigs.service; static; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:clamav-unofficial-sigs(8)
```

```
systemctl status clamav-unofficial-sigs.timer
● clamav-unofficial-sigs.timer - Clamav Unofficial Sigs Update timer
   Loaded: loaded (/etc/systemd/system/clamav-unofficial-sigs.timer; enabled; vendor preset: enabled)
   Active: inactive (dead)
  Trigger: n/a
     Docs: man:clamav-unofficial-sigs(8)
```

 ```
ps fax | grep unoff
 2343 pts/0    S+     0:00  |       \_ grep --color=auto unoff
```

Trying to enable both both services with systemctl gives this feedback from cli:

```
systemctl enable clamav-unofficial-sigs.service
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.
```

Enabling the timer service gives no feedback at all.

`systemctl enable clamav-unofficial-sigs.timer`

What am I doing wrong?
Would be very cool if anyone could help. ;-)

Michael

**Comment by dominicraf** [comment]
I have it running on Ubuntu 18.04 (v6.3.0) but it does not use systemctl at all, instead it is triggered by `/etc/cron.d/clamav-unofficial-sigs`

**Comment by extremeshok** [comment]
alas..systemd... why or why is it everywhere ... to promore alpine linux..that is why....

**Comment by extremeshok** [comment]
busy coding a fix...

**Comment by extremeshok** [comment]
fixed in dev

**Comment by amishmm** [comment]
As per [man systemd.special](https://www.freedesktop.org/software/systemd/man/systemd.special.html). Applications using timer should use timers.target in `WantedBy=`

This target is specifically made for timers.

So you might want to change `clamav-unofficial-sigs.timer` file to use `WantedBy=timers.target`
