### ISSUE TITLE
curl: (16) Error in the HTTP2 framing layer

### ISSUE THREAD

**Issue by fgrosswig** [extremeshok/clamav-unofficial-sigs#266]
Hello,
what beheavior might cause thise issue?

> curl: (16) Error in the HTTP2 framing layer
> [ -x /usr/local/sbin/clamav-unofficial-sigs.sh ] && /usr/bin/bash /usr/local/sbin/clamav-unofficial-sigs.sh

i cant find any insight of this but the error raises every 4 hours with the update intervall.

**Comment by RobbieTheK** [comment]
Also seeing this intermittently on Fedora 31:
```
curl: (28) Operation timed out after 600001 milliseconds with 214323200 out of
320502224 bytes received
curl: (16) Error in the HTTP2 framing layer
```

**Comment by extremeshok** [comment]
looks like connection issues. If you have more info to suggest this is not the case, please reopen
