### ISSUE TITLE
linuxmalwaredetect rfxn databases are not updated.

### ISSUE THREAD

**Issue by cotelo** [extremeshok/clamav-unofficial-sigs#269]
what is said in the title, linux malwaredetec databases have not been updated for a few weeks.

OS: Ubuntu 16:04.6 LTS X86_64
Kernel: 4.4.0-170-generic #199-Ubuntu SMP x86_64 GNU/Linux
Clamav && freshclam version: ClamAV 0.102.1/25663/Sat Dec 14 10:52:10 2019
#####################################################################
eXtremeSHOK.com ClamAV Unofficial Signature Updater
Version: v6.1.1 (2019-09-02)
Required Configuration Version: v76
Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
#####################################################################
dic 14 12:00:02 Preparing Databases
dic 14 12:00:02 sat dic 14 12:00:02 CET 2019 - Pausing database file updates for 235 seconds...
dic 14 12:03:57 sat dic 14 12:03:57 CET 2019 - Pause complete, checking for new database files...
dic 14 12:03:57 Sanesecurity Database & GPG Signature File Updates
dic 14 12:03:57 Checking for Sanesecurity updates...
dic 14 12:03:57 Sanesecurity mirror site used: spamexperts3-mirror.sanesecurity.com 185.95.29.15
dic 14 12:04:03 Testing updated Sanesecurity database file: jurlbl.ndb
dic 14 12:04:05 Clamscan reports Sanesecurity jurlbl.ndb database integrity tested good
dic 14 12:04:05 Successfully updated Sanesecurity production database file: jurlbl.ndb
dic 14 12:04:05 Testing updated Sanesecurity database file: rogue.hdb
dic 14 12:04:05 Clamscan reports Sanesecurity rogue.hdb database integrity tested good
dic 14 12:04:05 Successfully updated Sanesecurity production database file: rogue.hdb
dic 14 12:04:05 Testing updated Sanesecurity database file: blurl.ndb
dic 14 12:04:06 Clamscan reports Sanesecurity blurl.ndb database integrity tested good
dic 14 12:04:06 Successfully updated Sanesecurity production database file: blurl.ndb
dic 14 12:04:06 Testing updated Sanesecurity database file: jurlbla.ndb
dic 14 12:04:06 Clamscan reports Sanesecurity jurlbla.ndb database integrity tested good
dic 14 12:04:06 Successfully updated Sanesecurity production database file: jurlbla.ndb
dic 14 12:04:06 Testing updated Sanesecurity database file: porcupine.ndb
dic 14 12:04:07 Clamscan reports Sanesecurity porcupine.ndb database integrity tested good
dic 14 12:04:07 Successfully updated Sanesecurity production database file: porcupine.ndb
dic 14 12:04:07 Testing updated Sanesecurity database file: phishtank.ndb
dic 14 12:04:07 Clamscan reports Sanesecurity phishtank.ndb database integrity tested good
dic 14 12:04:07 Successfully updated Sanesecurity production database file: phishtank.ndb
dic 14 12:04:07 Testing updated Sanesecurity database file: porcupine.hsb
dic 14 12:04:07 Clamscan reports Sanesecurity porcupine.hsb database integrity tested good
dic 14 12:04:07 Successfully updated Sanesecurity production database file: porcupine.hsb
dic 14 12:04:07 linuxmalwaredetect Database File Updates
dic 14 12:04:07 Checking for linuxmalwaredetect updates...
dic 14 12:04:07 Checking for updated linuxmalwaredetect database file: rfxn.ndb
dic 14 12:04:13 No updated linuxmalwaredetect rfxn.ndb database file found
dic 14 12:04:13 ---
dic 14 12:04:13 Checking for updated linuxmalwaredetect database file: rfxn.hdb
dic 14 12:04:19 No updated linuxmalwaredetect rfxn.hdb database file found
dic 14 12:04:19 No linuxmalwaredetect database file updates found
dic 14 12:04:19 Checking for MalwarePatrol updates...
dic 14 12:04:19 MalwarePatrol Database File Update
dic 14 12:04:20 MalwarePatrol signature database (malwarepatrol.db) did not change - skipping
dic 14 12:04:20 Update(s) detected, reloading ClamAV databases
dic 14 12:04:20 ClamAV databases Reloaded
dic 14 12:04:20 Issue tracker : https://github.com/extremeshok/clamav-unofficial-sigs/issues
dic 14 12:04:27 Powered By https://eXtremeSHOK.com
################################
linuxmalwaredetect Database File Updates
################################
Checking for linuxmalwaredetect updates...
Checking for updated linuxmalwaredetect database file: rfxn.ndb
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- 0:00:05 --:--:-- 0
No updated linuxmalwaredetect rfxn.ndb database file found
Checking for updated linuxmalwaredetect database file: rfxn.hdb
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
No updated linuxmalwaredetect rfxn.hdb database file found
No linuxmalwaredetect database file updates found

**Comment by extremeshok** [comment]
they chnaged the way the databases are hosted, i am busy coding support..

**Comment by cotelo** [comment]
Ok. Thank you very much.

**Comment by extremeshok** [comment]
fixed in dev
3d82a786f42a505c0a53649f4c71094ca4b8860e
