### ISSUE TITLE
command not found while running. 

### ISSUE THREAD

**Issue by thctlo** [extremeshok/clamav-unofficial-sigs#272]
Hai, when i run` /usr/local/sbin/clamav-unofficial-sigs.sh `
Im getting : 
```
################################################################################
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v6.1.1 (2019-09-02)
 Required Configuration Version: v76
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
Loading config: /etc/clamav-unofficial-sigs/master.conf
/usr/local/sbin/clamav-unofficial-sigs.sh: line 1810: ===: command not found
Loading config: /etc/clamav-unofficial-sigs/os.conf
Loading config: /etc/clamav-unofficial-sigs/user.conf
===================
Preparing Databases
===================

```

**Comment by thctlo** [comment]
note, : 
type gpg
gpg is /usr/bin/gpg

type gpg2
gpg2 is /usr/bin/gpg2

i dont see why im getting the command not found message.
Code looks fine to me.

**Comment by extremeshok** [comment]
Could you please try the dev version and let me know if you have the error

**Comment by billmaidment** [comment]
I had ir: command not found messages. The dev version resolved that for me.

**Comment by thctlo** [comment]
Hai, sorry for the late reply. 

 i updated to latest version and i noticed packages clamav itself was missing. 
updated and installed the packages and works fine now.
