### ISSUE TITLE
malwarepatrol_reloaded wrong codes

### ISSUE THREAD

**Issue by dominicraf** [extremeshok/clamav-unofficial-sigs#274]
Thanks for the latest update (master branch:  v6.3.0), but I believe there remains a bug in lines 2892 and 2894 where the codes set for malwarepatrol_reloaded should be respectively 0 and 1, not 1 and 2.

**Comment by dominicraf** [comment]
another thing: the $curl_bin calls at lines 329 and 333 need 2>/dev/null at end.

**Comment by extremeshok** [comment]
can you check the dev branch please

**Comment by dominicraf** [comment]
both bugs apply to the dev branch and to exactly the same line numbers (at time of writing)

**Comment by extremeshok** [comment]
Updated the dev branch... want to test ? 

lines 2955 to 2991 are never run, as nothing has malwarepatrol_reloaded  set to 2

So im wondering if its legacy code.

**Comment by dominicraf** [comment]
Yes that seems to fix both bugs, thanks

> lines 2955 to 2991 are never run, as nothing has malwarepatrol_reloaded set to 2

agreed, maybe it was some earlier kludge that is no longer needed?

**Comment by extremeshok** [comment]
any other bugs or things i need to chnage / add to dev ? its going to be released soon

**Comment by dominicraf** [comment]
I added one about text/log message.

**Comment by extremeshok** [comment]
the entire malware patrol logic needs to be redone, busy with it

**Comment by extremeshok** [comment]
new malwarepatrol logic in the dev branch, please test

0f6869b8047f7ef8baa945a922b4e144efc7e3b7

**Comment by extremeshok** [comment]
should be perfect ;-P 

open an issue if the dev branch has issues
