### ISSUE TITLE
'Databases reloaded' text not correct

### ISSUE THREAD

**Issue by dominicraf** [extremeshok/clamav-unofficial-sigs#276]
Wherever in the code (master or dev) the 'databases reloaded' message is output or logged (upper/lower case varies) it should really say 'databases reload**_ing_**' because it triggers clamav to start reloading but this process takes time - can be several minutes on slower system. Clamav itself makes a log entry when the reload is complete.

To correct the text I modify clamav-unofficial-sigs thus:

    sed 's/databases reloaded\.\?/databases reloading/i'

HTH

**Comment by dominicraf** [comment]
(By the way, in general I find it rather too 'noisy' in logs so I remove all the lines with '===' and '---' and some others too.)

**Comment by extremeshok** [comment]
all done, any more suggestions etc, please post
