### ISSUE TITLE
Logging Disabled

### ISSUE THREAD

**Issue by bobcatos** [extremeshok/clamav-unofficial-sigs#279]
Just installed clamav-unofficial-sigs on up-to-date CentOS 6 server.  Followed the directions for installing.  Now it's reporting
WARNING: Logging Disabled, as file not writable: /var/log/clamav-unofficial-sigs/clamav-unofficial-sigs.log
The log and its parent directory are owned by clam-update:clam-update and perms are 640  and 755 respectively.
BTW, in the instructions, "purge" is not a valid yum operation, but "erase" works.

**Comment by extremeshok** [comment]
needs to writable by the user running clamav-unofficial-sigs 

please test the dev branch

**Comment by bobcatos** [comment]
On Thu, Jan 23, 2020 at 05:19:12PM -0800, eXtremeSHOK wrote:
> needs to writable by the user running clamav-unofficial-sigs

Thank you.

> please test the dev branch

It's working now.  I'd rather not muck with it on a production
server.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*

Cheers,
-- 
Bob McClure, Jr.             Bobcat Open Systems, Inc.
bob@bobcatos.com             http://www.bobcatos.com
As water reflects the face, so one’s life reflects the heart.
Proverbs 27:19
