### ISSUE TITLE
clamd restart - line error

### ISSUE THREAD

**Issue by si458** [extremeshok/clamav-unofficial-sigs#28]
cat: clamd_pid: No such file or directory
/usr/local/bin/clamav-unofficial-sigs.sh: line 636: =: command not found
/usr/local/bin/clamav-unofficial-sigs.sh: line 637: kill: /var/mailcleaner/run/clamav/clamspamd.pid: arguments must be process or job IDs

lines should read
LINE 636: `` $mypid = `cat $clamd_pid` ``
LINE 637: ` kill -USR2 $mypid `

**Comment by extremeshok** [comment]
Thanks, fixed 705ffc9b999a60aae2b0d45a1d5ed8b060d97ddd
