### ISSUE TITLE
Multiple emails that new version available, but no new release found.

### ISSUE THREAD

**Issue by ondrejj** [extremeshok/clamav-unofficial-sigs#281]
Yesterday started to receive message every hour, that new version is available:

```
Actual results:
***********************************************************************************
ALERT: New version : v6.3.0 @ https://github.com/extremeshok/clamav-unofficial-sigs
***********************************************************************************
***************************************************************************************
ALERT: New config version : v81 @ https://github.com/extremeshok/clamav-unofficial-sigs
***************************************************************************************
```

Please, make it possible to hide these messages, send them to log file and allow logwatch or similar scripts to gather them. No need to send message every hour.

Also there is no newer release in github page. Please make official release too and may be only check if there is an official release.

Some info on redhat bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1794506

**Comment by extremeshok** [comment]
thanks for the info. If possible please can you test the latest dev version.

I will also push a fix to it to prevent the version notice from appearing more than once every 24hours

**Comment by extremeshok** [comment]
This should stop the notices 
09122d1e2da94f46323e86e4d368147662b4bcb3

**Comment by ondrejj** [comment]
Thanks for quick reply.
I can't test dev version now. Can test stable, if you publish them.

**Comment by extremeshok** [comment]
plan is for today, just making sure all the bugs are gone

**Comment by robert-scheck** [comment]
No, 09122d1 does not stop the notices.

```
***************************************************************************************
ALERT: New config version : v81 @ https://github.com/extremeshok/clamav-unofficial-sigs
***************************************************************************************
```

**Comment by robert-scheck** [comment]
> I will also push a fix to it to prevent the version notice from appearing more than once every 24hours

Could you please introduce an option for downstreams (aka Linux distributions that ship your software), that the message just gets logged rather spewed to STDOUT? As a user of a Linux distribution, I trust my distribution and its packagers that they're updating the package as needed.

**Comment by extremeshok** [comment]
@robert-scheck 
Add and customize the following in the os.conf

# Enable support for script and master.conf upgrades
# enbles the --upgrade command line option
# packagers, if required please disable or set this option to no in the os.conf
allow_upgrades="yes"

# Enable support for script and master.conf update checks
# packagers, if required please disable or set this option to no in the os.conf
allow_update_checks="yes"

# How often the script should check for updates
update_check_hours="12"# Default is 12 hours (2 checks  daily).

**Comment by robert-scheck** [comment]
@ondrejj, can you please set both parameters to "no" when doing the updated Fedora/EPEL packages? Thank you :)

**Comment by extremeshok** [comment]
Maybe I should add a os.config with defaults for packaging.

**Comment by extremeshok** [comment]
config/os/os.recommended-packaging-defaults.conf

**Comment by extremeshok** [comment]
fixed in dev

**Comment by anatolinicolae** [comment]
How soon is it coming to package managers? 🤔

**Comment by extremeshok** [comment]
FOR PACKAGE MAINTAINERS / PACKAGERS
Please use the os.recommended-packaging-defaults.conf as a base for your os.conf, this will disable automatic updates, update notifications and the uninstallation feature. 

https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/config/os/os.recommended-packaging-defaults.conf

**Comment by ondrejj** [comment]
Thanks for release. I am building Fedora/CentOS/RHEL packages now.
Not sure, which os/conf to use in CentOS 6 (still should be supported). Currently I use os/centos6.conf with disabled check and upgrades.
Also please change systemctl restart to systemctl try-restart to avoid starting of clamav daemon when it's not started in any future releases.
