### ISSUE TITLE
Ir: command not found

### ISSUE THREAD

**Issue by Consequator** [extremeshok/clamav-unofficial-sigs#283]
Getting the following after updating yesterday:
/usr/sbin/clamav-unofficial-sigs.sh: line 1945: ir: command not found

Not sure what it's trying to do or what it's missing
OS is Centos 7

################################################################################
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v6.3.0 (2019-09-02)
 Required Configuration Version: v80
 Copyright (c) Adrian Jon Kriel :: **
################################################################################
Loading config: /etc/clamav-unofficial-sigs/master.conf
/usr/sbin/clamav-unofficial-sigs.sh: line 1945: ir: command not found
Loading config: /etc/clamav-unofficial-sigs/os.conf
Loading config: /etc/clamav-unofficial-sigs/user.conf

**Comment by andybeesee** [comment]
Same here - just updated this morning, also running CentOS 7.

**Comment by extremeshok** [comment]
#752 
fixed in dev, will release soon
