### ISSUE TITLE
Duplicate yara definitions in LOW category

### ISSUE THREAD

**Issue by dominicraf** [extremeshok/clamav-unofficial-sigs#285]
I'm working with latest dev master.conf. Adding all the LOW yara databases gives rise to many duplicate definitions which cause ClamAV to generate error messages and, at least sometimes, fatal failure. The following files are I believe now fully duplicated in rfxn.yara and so should be removed from master.conf:
EK_Angler.yar
EK_Blackhole.yar
EK_Crimepack.yar
EK_Eleonore.yar
EK_Fragus.yar
EK_Phoenix.yar
EK_Sakura.yar
EK_ZeroAcces.yar
EK_Zerox88.yar
EK_Zeus.yar
WShell_APT_Laudanum.yar
Wshell_ChineseSpam.yar
Wshell_fire2013.yar
WShell_PHP_Anuna.yar
WShell_PHP_in_images.yar
WShell_THOR_Webshells.yar

which leaves only these 3:
EK_BleedingLife.yar
WShell_ASPXSpy.yar
WShell_Drupalgeddon2_icos.yar

here is some testing code which identifies all rules in .yar file, checks for which ones are duplicated in rfxn.yara, then shows the name of the rules that are *not* duplicated.:
`
grep -ah "^rule " /var/lib/clamav/*.yar|cut -d: -f1 >/tmp/rules; while read RULE; do grep -qF "$RULE" /var/lib/clamav/rfxn.yara||echo $RULE; done</tmp/rules`

And this does the same check but outputs the names of the .yar files where the non-duplicated rules are found:
`grep -ah "^rule " /var/lib/clamav/*.yar|cut -d: -f1 >/tmp/rules; while read RULE; do grep -qF "$RULE" /var/lib/clamav/rfxn.yara||echo $RULE; done</tmp/rules|grep -Ff- /var/lib/clamav/*.yar
`

**Comment by extremeshok** [comment]
Maybe rxfn.yar should be disabled ? Any idea if there are any rules remaining once the duplicates are removed from it ?

thanks for the command, will look at adding them to the travis-ci

**Comment by dominicraf** [comment]
rxfn.yar is a big file with lots of rules the others are very small. So I
would keep rxfn and drop the others.

**Comment by extremeshok** [comment]
I cant decide if i want to filter them out when rxfn.yara is enabled or remove them...

**Comment by extremeshok** [comment]
quick update to master.conf to resolve the issue
