### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by extremeshok** [extremeshok/clamav-unofficial-sigs#286]
@ondrejj

> Thanks for release. I am building Fedora/CentOS/RHEL packages now.Not sure, which os/conf to use in CentOS 6 (still should be supported). Currently I use os/centos6.conf with disabled check and upgrades.Also please change systemctl restart to systemctl try-restart to avoid starting of clamav daemon when it's not started in any future releases.

This should be better, then you can submit pr's to keep them as required.

6128adcfd0fa8da3b78188ca984aa222238ecad0
cd15c216c98c1204de894121d444c58ba548a1d9

--

https://github.com/extremeshok/clamav-unofficial-sigs/tree/master/config/packaging

**Comment by ondrejj** [comment]
For centos6 there is no systemd, but sysvinit scripts, which don't know about try-restart and should use "condrestart". Please fix.
