### ISSUE TITLE
Update process does not appear to work.

### ISSUE THREAD

**Issue by wborrelli** [extremeshok/clamav-unofficial-sigs#287]
CentOS 7
I have been getting emails from contab that new versions are available.
I execute

[wborrelli@grimrod KMSAuto Net 2015 v1.3.8 Portable]$ sudo clamav-unofficial-sigs.sh --upgrade
[sudo] password for wborrelli:
################################################################################
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v6.1.1 (2019-09-02)
 Required Configuration Version: v76
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
Loading config: /etc/clamav-unofficial-sigs/master.conf
Loading config: /etc/clamav-unofficial-sigs/os.conf
Loading config: /etc/clamav-unofficial-sigs/user.conf
===================
Preparing Databases
===================
==================================
Sanesecurity Database File Updates
==================================
2 hours have not yet elapsed since the last Sanesecurity update check
------------------------------------------
No update check was performed at this time
------------------------------------------
Next check will be performed in approximately 1 hour(s), 38 minute(s)
========================================
linuxmalwaredetect Database File Updates
========================================
6 hours have not yet elapsed since the last linuxmalwaredetect update check
------------------------------------------
No update check was performed at this time
------------------------------------------
Next check will be performed in approximately 1 hour(s), 36 minute(s)
=================================
Setting permissions and ownership
=================================
===========================================================
Database reload has been disabled in the configuration file
===========================================================
----------------------------------------------------------------------------
Issue tracker : https://github.com/extremeshok/clamav-unofficial-sigs/issues
----------------------------------------------------------------------------
***********************************************************************************
ALERT: New version : v7.0.1 @ https://github.com/extremeshok/clamav-unofficial-sigs
***********************************************************************************
***************************************************************************************
ALERT: New config version : v91 @ https://github.com/extremeshok/clamav-unofficial-sigs
***************************************************************************************
##############################################
      Powered By https://eXtremeSHOK.com
##############################################

And I execute (per the instructions)

_[wborrelli@grimrod KMSAuto Net 2015 v1.3.8 Portable]$ sudo clamav-unofficial-sigs.sh --force
################################################################################
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v6.1.1 (2019-09-02)
 Required Configuration Version: v76
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
Loading config: /etc/clamav-unofficial-sigs/master.conf
Loading config: /etc/clamav-unofficial-sigs/os.conf
Loading config: /etc/clamav-unofficial-sigs/user.conf
+++++++++++++++++++++++
NOTICE: forcing updates
+++++++++++++++++++++++
===================
Preparing Databases
===================
==================================================
Sanesecurity Database & GPG Signature File Updates
==================================================
Checking for Sanesecurity updates...
Sanesecurity mirror site used:  46.21.115.195
receiving file list ...
94 files to consider
-------------------------------------------
No Sanesecurity database file updates found
-------------------------------------------
========================================
linuxmalwaredetect Database File Updates
========================================
Checking for linuxmalwaredetect updates...
Checking for updated linuxmalwaredetect database file: rfxn.ndb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
No updated linuxmalwaredetect rfxn.ndb database file found
---
Checking for updated linuxmalwaredetect database file: rfxn.hdb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
No updated linuxmalwaredetect rfxn.hdb database file found
-------------------------------------------------
No linuxmalwaredetect database file updates found
-------------------------------------------------
=================================
Setting permissions and ownership
=================================
===========================================================
Database reload has been disabled in the configuration file
===========================================================
----------------------------------------------------------------------------
Issue tracker : https://github.com/extremeshok/clamav-unofficial-sigs/issues
----------------------------------------------------------------------------
***********************************************************************************
ALERT: New version : v7.0.1 @ https://github.com/extremeshok/clamav-unofficial-sigs
***********************************************************************************
***************************************************************************************
ALERT: New config version : v91 @ https://github.com/extremeshok/clamav-unofficial-sigs
***************************************************************************************
##############################################
      Powered By https://eXtremeSHOK.com
##############################################_

And neither process appears to actually update the config files. 

Also, the message Database reload has been disabled in the configuration file is wrong, as the config file is set to Y for Database reload.

**Comment by wborrelli** [comment]
Ignore Database reload. I found that setting in the OS config file. It is set to no, and I see why.

**Comment by steffen-kdab** [comment]
I have exactly the same problem.
```
# clamav-unofficial-sigs.sh --upgrade
# clamav-unofficial-sigs.sh --force
```
seems to have no effect upgrading from `v6.1.1 (2019-09-02)`.

```
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core
```

**Comment by extremeshok** [comment]
... https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/guides/centos7.md

--upgrade is only available in v7
