### ISSUE TITLE
i keep having ALERT: New version : v7.0.1 @ https://github.com/extremeshok/clamav-unofficial-sigs

### ISSUE THREAD

**Issue by bitit-it** [extremeshok/clamav-unofficial-sigs#293]
Hi , i have a centos6.x  an a centos7.x with rpm  clamav-unofficial-sigs 6.x installed
have make the simple upgrade procedure :

`wget https://raw.githubusercontent.com/extremeshok/clamav-unofficial-sigs/master/clamav-unofficial-sigs.sh -O /usr/local/sbin/clamav-unofficial-sigs.sh && chmod 755 /usr/local/sbin/clamav-unofficial-sigs.sh
wget https://raw.githubusercontent.com/extremeshok/clamav-unofficial-sigs/master/config/master.conf -O /etc/clamav-unofficial-sigs/master.conf
/usr/local/sbin/clamav-unofficial-sigs.sh --force
`
in the command # clamav-unofficial-sigs -V
i have this output : 
` eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v7.0.1 (2020-01-25)
 Required Configuration Version: v91
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
`
but keep to having back the message : ALERT: New version : v7.0.1 @ https://github.com/extremeshok/clamav-unofficial-sigs

maybe I shouldn't upgrade but remove everything to make a new installation?

Enrico

**Comment by Fonant** [comment]
Check your `/etc/cron.d/clamav-unofficial-sigs` - it seems that the script has moved from `/usr/sbin/` to `/usr/local/sbin` but the cron job still points to the older one.

**Comment by nerijus** [comment]
You should not upgrade rpm installation. Either wait for updated rpm package, or uninstall rpm and install manually.

**Comment by bitit-it** [comment]
After changing the cron job I no longer have the warning message; it is not enough to delete the old file in /usr/sbin/ ?
