### ISSUE TITLE
Problem with restarting clamd

### ISSUE THREAD

**Issue by jobst** [extremeshok/clamav-unofficial-sigs#294]
In the os.conf file for CentOS only ONE rule is specified for

`clamd_restart_opt="systemctl restart sendmail-clamd.service"`

In systemd terms this leads to a problem when clamd is dead.
systemctl will fail as it WILL NOT restart not start clamd as its dead.

So rather have one rule there should be two:

`clamd_restart_opt="systemctl restart sendmail-clamd.service"`
`clamd_start_opt="systemctl start sendmail-clamd.service"`

And when the damon needs to be started/restarted a check like this should be done:

`#!/bin/bash`
`if ! systemctl is-active clamd >/dev/null ; then`
`   $clamd_start_opt`
`else`
`   $clamd_restart_opt`
` fi`

I sometimes end up with 

`Failed to restart clamd.service: Interactive authentication required.`
`See system logs and 'systemctl status clamd.service' for details.`

as systemctl simply refuses to do the restart if clamd is dead.
If you have two option, you can bypass that by allowing systemctl to START if dead and RESTART if not dead. Note that I have 

`Restart=always`

in the systemctl script for clamd, but that does not always work.

**Comment by extremeshok** [comment]
clamd_restart_opt="systemctl restart sendmail-clamd.service" this line is not in this library.

So i will assume that was added from a specific package
