### ISSUE TITLE
Wrong name for extended MalwarePatrol database

### ISSUE THREAD

**Issue by orlitzky** [extremeshok/clamav-unofficial-sigs#300]
In the script, there's some code to pick a database name:

```sh
if [ $malwarepatrol_list == "clamav_basic" ] ; then
  malwarepatrol_db="malwarepatrol.db"
else
  malwarepatrol_db="malwarepatrol.ndb"
fi
```

I'm not sure when/if this changed, but I noticed it failing today. The extended signatures that they offer are the exact same format as the basic ones. And the test scan will fail and reject the database if it has the `ndb` suffix instead of `db`. Editing the script to make it say "db" instead of "ndb" fixed the problem. For the record, here are my other settings:

```sh
malwarepatrol_receipt_code="my-receipt-code"
malwarepatrol_product_code="15"
malwarepatrol_list="clamav_ext" # clamav_basic or clamav_ext
malwarepatrol_free="no"
```

**Comment by extremeshok** [comment]
if the bug persists in the latest version which will be released soon.

Please make a new Issue (do not reopen this)
