### ISSUE TITLE
multiple issues on macOS

### ISSUE THREAD

**Issue by tiiiecherle** [extremeshok/clamav-unofficial-sigs#305]
Hey,

first of all thanks for this great project, it makes clamav so much better.

I took some time go over the macOS installation and build a small .app which asks for a directory to scan, and then runs a shell script that installs and configures everything and then scans the selected directory.

I'm using the latest macOS 10.15.3 and installed clamav via homebrew.

While doing that I encountered a few problems, mainly with permissions and sudo. After following the instructions [here](https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/guides/macosx.md) I could not use `clamav-unofficial-sigs.sh --force` without sudo due to permission issues. Running `sudo clamav-unofficial-sigs.sh --force` it messed up permissions so that freshclam and clamdscan/clamd were no longer working correctly.

I then decided to install everything in /usr/local. I don't know if I solved things correctly but after the following changes everything is working correctly. If what I did is right it would be good to change a few things in the project, if not, it's up to me to change my script ;)

**Changes**
```
HOMEBREW_PATH=$(brew --prefix)

mkdir -p "$HOMEBREW_PATH"/etc/clamav-unofficial-sigs

curl -s https://raw.githubusercontent.com/extremeshok/clamav-unofficial-sigs/master/config/master.conf --output "$HOMEBREW_PATH"/etc/clamav-unofficial-sigs/master.conf
curl -s https://raw.githubusercontent.com/extremeshok/clamav-unofficial-sigs/master/config/os/os.macosx.conf --output "$HOMEBREW_PATH"/etc/clamav-unofficial-sigs/os.conf
curl -s https://raw.githubusercontent.com/extremeshok/clamav-unofficial-sigs/master/config/user.conf --output "$HOMEBREW_PATH"/etc/clamav-unofficial-sigs/user.conf

sed -i '' 's|^clam_dbs=.*|clam_dbs="'"$HOMEBREW_PATH"'/var/homebrew/linked/clamav/share/clamav"|g' "$HOMEBREW_PATH"/etc/clamav-unofficial-sigs/os.conf
sed -i '' 's|^work_dir=.*|work_dir="'"$HOMEBREW_PATH"'/var/db/clamav-unofficial-sigs"|g' "$HOMEBREW_PATH"/etc/clamav-unofficial-sigs/os.conf
sed -i '' 's|^log_file_path=.*|log_file_path="'"$HOMEBREW_PATH"'/var/log"|g' "$HOMEBREW_PATH"/etc/clamav-unofficial-sigs/os.conf
```

After the above changes everything works well without sudo.

When updating the sigs, I ran into issue [#303](https://github.com/extremeshok/clamav-unofficial-sigs/issues/303) which I solved by installing gtar via homebrew and adding:
```
HOMEBREW_PATH=$(brew --prefix)
HOMEBREW_BIN_PATH=""$HOMEBREW_PATH"/bin"

if command -v gtar &> /dev/null
then
	# installed
	sed -i '' 's/command -v tar/command -v gtar/g' ""$HOMEBREW_BIN_PATH"/clamav-unofficial-sigs.sh"
else
	# not installed
	:
fi
```

Thanks for any feedback in advance.

Kind regards

**Comment by extremeshok** [comment]
fixed 552a147a114151baa57ea07dda284a91c15d43ca and dd48c01854788f5d3279756fe726d080e70f9ed2
