### ISSUE TITLE
Trust of the project

### ISSUE THREAD

**Issue by thobach** [extremeshok/clamav-unofficial-sigs#306]
Hi eXtremeSHOK team,
We're interested in using your scripts in a commercial service. How do you ensure the security of the scripts you provide?
E.g. how are changes tested before release, how are commits approved, how many people can approve changes and how are they checked for trust-worthiness?
Thanks!

**Comment by thobach** [comment]
Friendly reminder, thanks!

**Comment by arafatx** [comment]
Same question on this.

**Comment by julian70400** [comment]
Well, it seem that the project is dead..

**Comment by shawniverson** [comment]
If maintainer doesn't respond, I will consider forking this and maintaining it.

**Comment by amishmm** [comment]
People here may want to check this alternate project.

https://rseichter.github.io/fangfrisch/

**Comment by extremeshok** [comment]
I have multiple VM;s which are used for testing quality.
All code is reviewed by me and only I approve it.
Each pull request is manually tested, etc.
I browse forks and import changes etc.

**Comment by julian70400** [comment]
> I have multiple VM;s which are used for testing quality.
> All code is reviewed by me and only I approve it.
> Each pull request is manually tested, etc.
> I browse forks and import changes etc.
> Project is not dead, unfortunately I have to prioritize work which keeps my rent paid.
> I generally work with my private repo and push changes here when I am happy with them.

Well, still alive, that's the sign we were waiting 👍
