### ISSUE TITLE
securiteinfo premium signatures not working

### ISSUE THREAD

**Issue by jengels** [extremeshok/clamav-unofficial-sigs#311]
Hi, i've activated the option securiteinfo_premium as follows:

grep -i premium /etc/clamav-unofficial-sigs/*conf
/etc/clamav-unofficial-sigs/master.conf:securiteinfo_premium="yes"
/etc/clamav-unofficial-sigs/master.conf:declare -a securiteinfo_dbs_premium=( #START SECURITEINFO DATABASES
/etc/clamav-unofficial-sigs/user.conf:securiteinfo_premium="yes"

I have of course a premium account at SecuriteInfo and I've also checked that I can download the files manually using the SecuriteInfo URLs:
https://www.securiteinfo.com/get/signatures/MYKEY/securiteinfo0hour.hdb
https://www.securiteinfo.com/get/signatures/MYKEY/securiteinfo.mdb

But it seems this functionality is still missing in the clamav-unofficial-sigs.sh script...

grep -i premium /usr/sbin/clamav-unofficial-sigs.sh
*no results*

**Comment by extremeshok** [comment]
fixed: cd5b8ba
