### ISSUE TITLE
after reboot /var/run/clamav does not exist, ERROR chdir failed (/var/run/clamav): No such file or directory

### ISSUE THREAD

**Issue by RobbieTheK** [extremeshok/clamav-unofficial-sigs#315]
On Fedora/CentOS, after a reboot,` /var/run/clamav` [gets erased](https://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html#VARRUNRUNTIMEVARIABLEDATA). 

So these errors start to appear:

`ERROR chdir failed (/var/run/clamav): No such file or directory`

Would it be better to [place a configuration file](https://www.freedesktop.org/software/systemd/man/systemd-tmpfiles.html) in `/usr/lib/tmpfiles.d`?

Also this entry:
```
# Set path to clamd.pid file (see clamd.conf for path location).
#clamd_pid="/var/run/clamav/clamd.pid"
```
The pid file and/or conf file can be in a different place. Would it be possible to get this from a `ps `command?

For example, on our Fedora 32:
```
ps -auwx|grep clamd
clamav     98547  0.0  1.1 2303684 1534908 ?     Ssl  May23   2:59 /usr/sbin/clamd -c /etc/clamd.d/scan.conf
```
Note in the `/etc/clamd.d/scan.conf` file the default for the PID is disabled:

```
# This option allows you to save a process identifier of the listening
# daemon (main thread).
# Default: disabled
#PidFile /var/run/clamd.scan/clamd.pid
```

**Comment by RobbieTheK** [comment]
There are some workarounds in [this thread](https://bugzilla.redhat.com/show_bug.cgi?id=1312035#c2).

[Comment 6 ](https://bugzilla.redhat.com/show_bug.cgi?id=1312035#c6)has  this:

> 1.) Make sure that there's no "--nofork=yes" option set in /lib/systemd/system/clamd.service
> 
> 2.) Create a /etc/tmpfiles.d/clamav.conf file with the below content:
> 
> d /var/run/clamav 0755 clam clam
> 
> 3.) Reboot.

**Comment by extremeshok** [comment]
Feel free to submit a PR to fix this, not sure what needs to be done as its more or a clamav config causing the issue
