### ISSUE TITLE
Feature Request: Update without overwriting .conf file

### ISSUE THREAD

**Issue by dmb-ts** [extremeshok/clamav-unofficial-sigs#32]
I have a feature request, nothing too important but it would be nice to have:

When updating clamav-unofficial-sigs you currently have to overwrite your .conf file when the conf version gets increased. I have lots of changes the .conf file (I use different clamav-DBs, my api keys for the services, etc...) so it is always a hassle to update the .conf and it needs testing afterwards to ensure I didn't fuck anything up.

Thanks and keep up the good work :)

**Comment by nerijus** [comment]
I make a copy of original clamav-unofficial-sigs.conf as clamav-unofficial-sigs.conf.orig, and after changing config file I do
diff -u clamav-unofficial-sigs.conf.orig clamav-unofficial-sigs.conf > clamav-unofficial-sigs.conf.diff

After config file update I do
patch < clamav-unofficial-sigs.conf.diff
and apply failed hunks manually.

**Comment by extremeshok** [comment]
Add support for the user defined config option override file: clamav-unofficial-sigs.conf.override

8bdaddb280eeeae5dcb396cc65da952cdc322ad9
