### ISSUE TITLE
malware.expert broken

### ISSUE THREAD

**Issue by thend20** [extremeshok/clamav-unofficial-sigs#321]
The links to the malware expert definitions are only populated with a single rule.  Either they have stopped providing free definitions, or someone from the malware.expert team screwed up a deployment.

**Comment by Gazoo** [comment]
It looks like they went paid subscription only :( Look at the signature name:

```
# cat malware.expert.ndb
{HEX}Malware.Expert.buy.subscription:0:*:62757920737562736372697074696f6e2066726f6d2068747470733a2f2f6d616c776172652e657870657274
```

**Comment by extremeshok** [comment]
url syntax : http://signatures.malware.expert/serial_key_here/malware.expert.ndb

**Comment by extremeshok** [comment]
work in progress.

**Comment by extremeshok** [comment]
71efd84
