### ISSUE TITLE
disable email notification 

### ISSUE THREAD

**Issue by frompani** [extremeshok/clamav-unofficial-sigs#325]
Is it possible to add some parameter to disable email notification of new version?
we 're not ready to upgrade in production enviroment and these email are annoying 
I 've already modify MAILTO=   in cron but it would be better have the ability to disable **only** new  version notifications

thank's 
fabrizio

> ***********************************************************************************
> ALERT: New version : v7.0.1 @
> https://github.com/extremeshok/clamav-unofficial-sigs
> ***********************************************************************************
> ***************************************************************************************
> ALERT: New config version : v91 @
> https://github.com/extremeshok/clamav-unofficial-sigs
> ***************************************************************************************

**Comment by extremeshok** [comment]
with the to be released new version, reuinstall the cron.
````
bash clamav-unofficial-sigs.sh --install-cron
````

Otherwise disable the line "MAILTO: root" in the cron

**Comment by frompani** [comment]
Thank's for your replay .
In that way , are disable new version notification ONLY  or all possible notification? 
It would be great to disable _only_ new version notification.
thank's 
rf
