### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by thefiredragon** [extremeshok/clamav-unofficial-sigs#327]
Dear @extremeshok
is this project dead ? noticed some issues and would like to know if you will work in future on this project, We use this for our systems and like it, also with malewarepatrol,
best Regards

**Comment by amishmm** [comment]
Have you checked this alternate project?

https://rseichter.github.io/fangfrisch/

**Comment by shawniverson** [comment]
If maintainer doesn't respond, I will consider forking this and maintaining it.

**Comment by thefiredragon** [comment]
This would be nice ;)

**Comment by extremeshok** [comment]
Project is not dead, unfortunately I have to prioritize work which keeps my rent paid. 
I generally work with my private repo and push changes here when I am happy with them.
