### ISSUE TITLE
Yara Rules Have New Sub Categorys

### ISSUE THREAD

**Issue by spec1re** [extremeshok/clamav-unofficial-sigs#33]
eg.

malicious_document.yar → Malicious_Documents/malicious_document.yar

yararules_url="https://raw.githubusercontent.com/Yara-Rules/rules/master/"

result in malicious_document.yar  → Not Found

https://github.com/Yara-Rules/rules/commit/c7bee0f8d638c327db9d0ae5e02f89baa4f0b71a

Regards

**Comment by kionez** [comment]
also antidebug.yar is renamed to antidebug_antivm.yar

https://github.com/Yara-Rules/rules/commit/4740135a3c5b14ff4ba285b5e780a2b238fa23e6

**Comment by falon** [comment]
When a file is not found, a file with
`Not Found`
content is created. So now I have a malicious_document.yar containing only "Not Found".
I think it's better to delete at all the files not found.

**Comment by extremeshok** [comment]
I will add a sanity check to check the rule files contain more than a few lines and then handle them accordingly

**Comment by extremeshok** [comment]
Added Option: remove_bad_database
# When a database integrity has tested BAD, the failed database will be removed.
remove_bad_database="no"
