### ISSUE TITLE
$curl_bin is used before the config files are parsed

### ISSUE THREAD

**Issue by SlothOfAnarchy** [extremeshok/clamav-unofficial-sigs#341]
I'm using this tool on NixOS and would like to specify paths to `curl`, `dig` etc. in the configuration.
I get the error `ERROR: both wget and curl commands are missing, One of them is required` although I defined `curl_bin` in my `os.conf`.
It seems to me that the problem is with the execution order in the startup part of the script. The error is thrown in https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/clamav-unofficial-sigs.sh#L1685 but the configuration is parsed after that, in https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/clamav-unofficial-sigs.sh#L1862

Therefore the variables are empty at the time they're checked.

Can the config parsing be moved up in the script? Or the variable checks moved down?

**Comment by extremeshok** [comment]
Could you send me an os.nixos.conf please ?

I will upload a fix to the dev branch

**Comment by SlothOfAnarchy** [comment]
Thanks! I don't think a static os.nixos.conf makes sense, because it includes paths like `curl_bin="/nix/store/61q8a5j9sg98f5g8h0ianqyxb2crz5g6-curl-7.72.0-bin/bin/curl"` which are generated during the build.

I will ping you once I finish a PR against the nixpkgs repo so that others can use it.

**Comment by extremeshok** [comment]
let me know what fixes and changes nixos requires (send a PR against the dev branch) and i will try and push a 7.2.1 for compatibility

**Comment by extremeshok** [comment]
fixed with 1606d5ae

**Comment by SlothOfAnarchy** [comment]
Hi, thanks for the fix! I think there is one instance of `grep_bin` being used before the definition/detection in the new version from https://github.com/extremeshok/clamav-unofficial-sigs/commit/1606d5ae268b1e704000a236caa05b5a5a535c7f

`$grep_bin` is used in https://github.com/extremeshok/clamav-unofficial-sigs/blob/dev/clamav-unofficial-sigs.sh#L1788 but only assigned in https://github.com/extremeshok/clamav-unofficial-sigs/blob/dev/clamav-unofficial-sigs.sh#L2017 which leads to an error when running the script (`line 1788: -c: command not found`).
