### ISSUE TITLE
sponsors link error

### ISSUE THREAD

**Issue by msimerson** [extremeshok/clamav-unofficial-sigs#343]
Visiting your sponsors page reveals:

<img width="381" alt="Screen Shot 2020-12-09 at 10 15 38 PM" src="https://user-images.githubusercontent.com/261635/101728921-21084080-3a6c-11eb-9e64-e77776c6ea3c.png">

And if I follow the link to donate via PayPal, there's a $0.99 fee. For a no-product item like a donation, I was expecting a way to send money using PayPal's (or any other) free tier.

**Comment by extremeshok** [comment]
Alas ;/ not much I can do regarding payment fees. 

not sure if one can add amazon egift carda

I have enrolled for github, but I think that is going to take a long tome.
