### ISSUE TITLE
RFE: Disable Yaraproject Email_generic_phishing.yar by default

### ISSUE THREAD

**Issue by siebenmann** [extremeshok/clamav-unofficial-sigs#344]
This rule has an extremely high level of false positives for email in our environment (and probably in many others) because of how general it is. It should probably be disabled by default.

(It would also be nice to have some documentation on how to disable a specific database file out of a set of them, instead of disabling all of the Yaraproject rules.)

**Comment by extremeshok** [comment]
I will fix this in the 7.2.1 update, in the mean time 

in your master.conf
edit 
```
email/Email_generic_phishing.yar|MEDIUM
```
to
```
email/Email_generic_phishing.yar|HIGH
```
