### ISSUE TITLE
/usr/local/sbin/clamav-unofficial-sigs.sh: line 2891: -t: command not found

### ISSUE THREAD

**Issue by brettco** [extremeshok/clamav-unofficial-sigs#346]
Hi
I'm on CentOS 7 with most recent clamav-unofficial-sigs (Dec 7, 2020)
I see this email from and to clamupdate@localhost 
/usr/local/sbin/clamav-unofficial-sigs.sh: line 2891: -t: command not found
Nothing to help is seen in clamav-unofficial-sigs.log and a google search shows me nothing about this
Thank you

**Comment by extremeshok** [comment]
Please send me the output of 
```
host --help
```

-t specifies the query type

**Comment by brettco** [comment]
bash: host: command not found
I installed bind-utils and I'm good now.  I'm not sure how I missed that step.
Sorry for the noise and thank you for the help  :)
