### ISSUE TITLE
Removing unused file: dbs-lmd/rfxn.yara

### ISSUE THREAD

**Issue by ondrejj** [extremeshok/clamav-unofficial-sigs#355]
After update to 7.2 and also 7.2.1 I am getting this mesage from cron:

```
Subject: Cron <root@work> [ -x /usr/sbin/clamav-unofficial-sigs.sh ] &&         
        /bin/bash /usr/sbin/clamav-unofficial-sigs.sh                           

Removing unused file: /var/lib/clamav-unofficial-sigs/dbs-lmd/rfxn.yara
```

Removal od dbs-lmd-rfxn.* files doesn't help.

I am using clamav-unofficial-sigs-7.2.1-1.fc33.noarch Fedora package (I am maintainer of this package).

How can this message be silenced?

**Comment by extremeshok** [comment]
Few questions, 
is yara enabled in clamav ?, if not then it is correct for the yara file to be removed.

Im considering only displaying the removal messages if debug="yes"

**Comment by ondrejj** [comment]
> is yara enabled in clamav ?

In clamav or in clamav-unofficial-sigs? In both I use default settings.

> if not then it is correct for the yara file to be removed.

OK, should be removed once, but even if I remove all rfxn.* files, this message is after some time displayed again. Not sure how often, aprox. 1-2 times weekly.

> Im considering only displaying the removal messages if debug="yes"

+1 for this, mostly useless message
And possibly should go to logs, not mailed to user.

**Comment by extremeshok** [comment]
please can you test the latest dev branch

**Comment by ondrejj** [comment]
OK, testing vesion 7.2.2, but I am unable to reproduce daily, so not sure when I finish.
