### ISSUE TITLE
Removing unused file: /var/lib/clamav/spam_marketing.ndb every 2 hours

### ISSUE THREAD

**Issue by archifishaldev** [extremeshok/clamav-unofficial-sigs#356]
Following on from issue #342 ... So the cron job runs every hour. In the first hour, it successfully deletes the /var/lib/clamav/spam_marketing.ndb file (The Removing unused file message above), then the next hour it seems to redownload it again. And this repeats every 2 hours.

I've attached my os.conf and user.conf files (removing the malwarepatrol_receipt_code)
[os.conf.txt](https://github.com/extremeshok/clamav-unofficial-sigs/files/5708364/os.conf.txt)
[user.conf.txt](https://github.com/extremeshok/clamav-unofficial-sigs/files/5708378/user.conf.txt)

 - I'm not sure if it relates to securiteinfo_premium being disabled? As spam_marketing.ndb|HIGH seems to be mentioned in that section in master.conf .

**Comment by extremeshok** [comment]
Busy checking this, 

just some observations, your  default_dbs_rating is MEDIUM (default from master.conf)

So it should not be re-downloading the spam_marketing.ndb|HIGH

**Comment by WalterHof** [comment]
I see this error also with v7.2.1:

Removing unused file: /var/lib/clamav/spam_marketing.ndb
***********************************************************************************
ALERT: New version : v7.2.2 @ https://github.com/extremeshok/clamav-unofficial-sigs
***********************************************************************************

**Comment by archifishaldev** [comment]
Actually I don't think I've seen this issue since updating to 7.2.2 - was anything fixed relating to this in that version?

**Comment by extremeshok** [comment]
A few fixes were done
