### ISSUE TITLE
clamav-unofficial-sigs.sh needs root?

### ISSUE THREAD

**Issue by Utini2000** [extremeshok/clamav-unofficial-sigs#36]
I just installed this very great script on Arch via the AUR:
https://aur.archlinux.org/packages/clamav-unofficial-sigs/

It seems like everytime I want to update (run the "clamav-unofficial-sigs.sh") it would require root?

`/usr/bin/clamav-unofficial-sigs.sh
################################################################################
eXtremeSHOK.com ClamAV Unofficial Signature Updater
Version: v4.9.2 (02 December 2015)
Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
================================================
Loading config: /etc/clamav-unofficial-sigs.conf
================================================
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs': Permission denied
chmod: cannot access '/var/lib/clamav-unofficial-sigs/gpg-key': No such file or directory
curl: (23) Failed writing body (0 != 1762)
*****************************************************
ALERT: Could not download Sanesecurity public GPG key
*****************************************************
/usr/bin/clamav-unofficial-sigs.sh: line 81: /var/log/clamav/clamav-unofficial-sigs.log: Permission denied`

`

......@_____:~$ sudo mkdir /var/lib/clamav-unofficial-sigs/
[sudo] password for ......:
.....@_____:~$ /usr/bin/clamav-unofficial-sigs.sh
################################################################################
eXtremeSHOK.com ClamAV Unofficial Signature Updater
Version: v4.9.2 (02 December 2015)
Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
================================================
Loading config: /etc/clamav-unofficial-sigs.conf
================================================
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs/dbs-si': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs/dbs-mbl': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs/dbs-lmd': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs/dbs-ss': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs/configs': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs/gpg-key': Permission denied
mkdir: cannot create directory '/var/lib/clamav-unofficial-sigs/dbs-add': Permission denied
chmod: cannot access '/var/lib/clamav-unofficial-sigs/gpg-key': No such file or directory
curl: (23) Failed writing body (0 != 1762)
*****************************************************
ALERT: Could not download Sanesecurity public GPG key
*****************************************************
/usr/bin/clamav-unofficial-sigs.sh: line 81: /var/log/clamav/clamav-unofficial-sigs.log: Permission denied`

**Comment by extremeshok** [comment]
That's correct, as clamav usually requires root permissions to test the integrity of the rules

**Comment by Utini2000** [comment]
Hmm so how can I automate this on a laptop? Manually run the script as root after every reboot?

**Comment by extremeshok** [comment]
Use the crontab, it's designed to run at specific intervals

**Comment by Utini2000** [comment]
Hmm but does crontab run things as root e.g. the script?

**Comment by nerijus** [comment]
lmgtfy.com/?q=does+crontab+run+things+as+root

**Comment by Utini2000** [comment]
Alright and one more question:

Is there a way to verify that ClamAV uses all those signatures?

**Comment by extremeshok** [comment]
clamscan --debug 2>&1 /dev/null | grep "loaded"
``
LibClamAV debug: /var/lib/clamav/sanesecurity.ftm loaded
LibClamAV debug: /var/lib/clamav/winnow_malware_links.ndb loaded
LibClamAV debug: /var/lib/clamav/securiteinfopdf.hdb loaded
LibClamAV debug: /var/lib/clamav/rogue.hdb loaded
LibClamAV debug: /var/lib/clamav/winnow_extended_malware.hdb loaded
LibClamAV debug: /var/lib/clamav/blurl.ndb loaded
LibClamAV debug: /var/lib/clamav/securiteinfohtml.hdb loaded
LibClamAV debug: /var/lib/clamav/rfxn.hdb loaded
LibClamAV debug: /var/lib/clamav/malwarepatrol.db loaded
LibClamAV debug: /var/lib/clamav/scam.ndb loaded
LibClamAV debug: /var/lib/clamav/porcupine.ndb loaded
LibClamAV debug: /var/lib/clamav/phishtank.ndb loaded
LibClamAV debug: /var/lib/clamav/spamattach.hdb loaded
LibClamAV debug: /var/lib/clamav/winnow.attachments.hdb loaded
LibClamAV debug: /var/lib/clamav/bofhland_malware_attach.hdb loaded
LibClamAV debug: /var/lib/clamav/malwarehash.hsb loaded
LibClamAV debug: /var/lib/clamav/bofhland_phishing_URL.ndb loaded
LibClamAV debug: /var/lib/clamav/spamimg.hdb loaded
LibClamAV debug: /var/lib/clamav/javascript.ndb loaded
LibClamAV debug: /var/lib/clamav/crdfam.clamav.hdb loaded
LibClamAV debug: /var/lib/clamav/hackingteam.hsb loaded
LibClamAV debug: /var/lib/clamav/winnow_malware.hdb loaded
LibClamAV debug: /var/lib/clamav/bofhland_cracked_URL.ndb loaded
LibClamAV debug: /var/lib/clamav/phish.ndb loaded
LibClamAV debug: /var/lib/clamav/bofhland_malware_URL.ndb loaded
LibClamAV debug: /var/lib/clamav/rfxn.ndb loaded
LibClamAV debug: /var/lib/clamav/securiteinfo.hdb loaded
LibClamAV debug: /var/lib/clamav/porcupine.hsb loaded
``
