### ISSUE TITLE
ClamAV crashed afer update to v7.2.2 (2020-12-20)

### ISSUE THREAD

**Issue by KumoCosmo** [extremeshok/clamav-unofficial-sigs#361]
OS:  Ubuntu 20.04.1 LTS

LibClamAV Error: yyerror(): /var/lib/clamav/EMAIL_Cryptowall.yar line 34 duplicate identifier "CryptoWall_Resume_phish"
LibClamAV Warning: cli_loadyara: failed to parse or load 1 yara rules from file /var/lib/clamav/EMAIL_Cryptowall.yar, successfully loaded 1 rules.

(!!)TROUBLE in child_init_hook: BDB can't connect db env. at /var/lib/amavis/db: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery, No such file or directory. at (eval 92) line 338.
(!)_DIE: Suicide in child_init_hook: BDB can't connect db env. at /var/lib/amavis/db: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery, No such file or directory. at (eval 92) line 338.

**Comment by extremeshok** [comment]
Remove all the database files and run the script with --force

**Comment by KumoCosmo** [comment]
I did. The duplicate comes back with next update 24h later.

 

It’s a duplicate rule name: CryptoWall_Resume_phish

 

In /var/lib/clamav/EMAIL_Cryptowall.yar and /var/lib/clamav/winnow_malware.yara

 

 

Von: eXtremeSHOK <notifications@github.com> 
Gesendet: Donnerstag, 14. Januar 2021 12:54
An: extremeshok/clamav-unofficial-sigs <clamav-unofficial-sigs@noreply.github.com>
Cc: Jörg Sitek <Joerg.Sitek@cortado.com>; Author <author@noreply.github.com>
Betreff: Re: [extremeshok/clamav-unofficial-sigs] ClamAV crashed afer update to v7.2.2 (2020-12-20) (#361)

 

Remove all the database files and run the script with --force

**Comment by KumoCosmo** [comment]
Hi,

 

is there any fix planed in the near future?

 

Best regards

Jörg 

 

Von: Jörg Sitek 
Gesendet: Donnerstag, 14. Januar 2021 13:11
An: 'extremeshok/clamav-unofficial-sigs' <reply@reply.github.com>; extremeshok/clamav-unofficial-sigs <clamav-unofficial-sigs@noreply.github.com>
Cc: Author <author@noreply.github.com>
Betreff: AW: [extremeshok/clamav-unofficial-sigs] ClamAV crashed afer update to v7.2.2 (2020-12-20) (#361)

 

I did. The duplicate comes back with next update 24h later.

 

It’s a duplicate rule name: CryptoWall_Resume_phish

 

In /var/lib/clamav/EMAIL_Cryptowall.yar and /var/lib/clamav/winnow_malware.yara

 

 

Von: eXtremeSHOK <notifications@github.com <mailto:notifications@github.com> > 
Gesendet: Donnerstag, 14. Januar 2021 12:54
An: extremeshok/clamav-unofficial-sigs <clamav-unofficial-sigs@noreply.github.com <mailto:clamav-unofficial-sigs@noreply.github.com> >
Cc: Jörg Sitek <Joerg.Sitek@cortado.com <mailto:Joerg.Sitek@cortado.com> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [extremeshok/clamav-unofficial-sigs] ClamAV crashed afer update to v7.2.2 (2020-12-20) (#361)

 

Remove all the database files and run the script with --force
