### ISSUE TITLE
Correct the urlhaus db dir

### ISSUE THREAD

**Issue by willdoicu** [extremeshok/clamav-unofficial-sigs#363]
Please correct the(actual) line 642 in master.conf from:
urlhausy_dir="dbs-uh"        # urlhaus sub-directory
to:
urlhaus_dir="dbs-uh"        # urlhaus sub-directory

**Comment by perplexityjeff** [comment]
I created a simple pull request to fix this. 

https://github.com/extremeshok/clamav-unofficial-sigs/pull/368
