### ISSUE TITLE
ScamNailer needs to be removed

### ISSUE THREAD

**Issue by randyleiker** [extremeshok/clamav-unofficial-sigs#365]
The ScamNailer database is no longer maintained and should be removed from clamav-unofficial-sigs per this message at http://www.scamnailer.info:

Sorry, but this service (ScamNailer / ClamNailer) has been closed down.

Please remove any scripts called either ScamNailer or ClamNailer from your email servers, and output files which might be any of

    /etc/mail/spamassassin/ScamNailer.cf
    /var/cache/ScamNailer/
    /var/lib/clamav/scamnailer.ndb
    /var/cache/clamnailer

Sorry that this has happened, but various donated services that I relied upon have been withdrawn by their owners.

**Comment by perplexityjeff** [comment]
I created a simple pull request to fix this hopefully the developer picks up on this. I think for users that now need to disable it

Search for scamnailer in the master.conf and change MEDIUM to DISABLED.
