### ISSUE TITLE
Question: Is rsync really mandatory?

### ISSUE THREAD

**Issue by sbcgm** [extremeshok/clamav-unofficial-sigs#366]
Hi everyone!

I would assume that you could download the signatures with http(s) instead of rsync, yet I haven't found anything that would suggest you could configure clamav-unofficial-sigs in a way so it would download via https only.

Are those signature dbs really available via rsync only?

Thanks

**Comment by perplexityjeff** [comment]
I think the actual downloading it seems that curl is used and not rsync? rsync seems to be used to sync permissions as far as I can read the script maybe I am wrong here. Take a look into the `xshok_file_download()` function.

**Comment by extremeshok** [comment]
YES...
rsync used for sanesecurity signatures, yes there are ways around this, but its not what they want.
rsync is also used as a more efficient method than copy, to sync the reqwuired downloaded databases with clamav.
