### ISSUE TITLE
yara github url

### ISSUE THREAD

**Issue by freeblue** [extremeshok/clamav-unofficial-sigs#37]
Hi, it seems the url provided for yararuls in  clamav-unofficial-sigs.conf doesn't work anymore : 
https://raw.githubusercontent.com/Yara-Rules/

when i connect directly via my browser, it gives : 400: Invalid request

regards,
alexandre R

**Comment by extremeshok** [comment]
The url is part of a pattern, it's just a suffix for the actual irk

**Comment by freeblue** [comment]
Thanks for your answer.
Anyway, even if yara rules are enable in configuration file, nothing is downloaded. I Will try tu use latest revision of the script and configuration file.
Actually, I am using revision #50
Regards,
Alexandre R.

**Comment by freeblue** [comment]
Version #53 fixed the problem. Thanks
