### ISSUE TITLE
urlhaus updates fail on new Ubuntu install

### ISSUE THREAD

**Issue by CacheMinimal** [extremeshok/clamav-unofficial-sigs#385]
I have recently followed the instructions in guides/ubuntu-debian.md to install release 7.2.5 on a fresh Ubuntu Server 20.04 LTS (AMD64) installation.  Every hour the following urlhaus error is logged (this one with debug enabled):

```
Apr 05 18:02:52 Checking for urlhaus updates...
Apr 05 18:02:52 Checking for updated urlhaus database file: urlhaus.ndb
Apr 05 18:02:52 url: https://urlhaus.abuse.ch/downloads/urlhaus.ndb >> outputfile: /var/lib/clamav-unofficial-sigs/dbs-uh/urlhaus.
ndb | 
Apr 05 18:02:52 WARNING: Failed connection to https://urlhaus.abuse.ch/downloads - SKIPPED urlhaus urlhaus.ndb update
Apr 05 18:02:52 No updated urlhaus urlhaus.ndb database file
Apr 05 18:02:52 No urlhaus database file updates
```

The error is not quite as it seems because the URL is reachable and the system can download the file.  What is missing is the output directory /var/lib/clamav-unofficial-sigs/dbs-uh.  This is not created during the initial `clamav-unofficial-sigs.sh --force` run.  Once created manually with the following, updates succeed:

```
mkdir /var/lib/clamav-unofficial-sigs/dbs-uh
chown clamav:clamav /var/lib/clamav-unofficial-sigs/dbs-uh
```

I am wondering whether this may be related to this typo where a bonus `t` has crept in?

https://github.com/extremeshok/clamav-unofficial-sigs/blob/ececc4b53286666d9bb65336a9ab079c804b28a6/clamav-unofficial-sigs.sh#L1923

**Comment by perplexityjeff** [comment]
I created a simple pull request to possibly fix this

https://github.com/extremeshok/clamav-unofficial-sigs/pull/386

**Comment by MASHtm** [comment]
I think there is the mkdir call missing as well
```
--- clamav-unofficial-sigs.sh	(revision 5031)
+++ clamav-unofficial-sigs.sh	(working copy)
@@ -2763,6 +2763,7 @@
 xshok_mkdir_ownership "$work_dir_securiteinfo"
 xshok_mkdir_ownership "$work_dir_work_configs"
 xshok_mkdir_ownership "$work_dir_yararulesproject"
+xshok_mkdir_ownership "$work_dir_urlhaus"
 
 # Set secured access permissions to the GPG directory
 perms chmod -f 0700 "${work_dir_gpg}"
```

**Comment by MASHtm** [comment]
I add this here as well since this topic is urlhaus related only anyway. --force doesn't affect urlhaus since this part is missing:
```
--- clamav-unofficial-sigs.sh	(revision 5033)
+++ clamav-unofficial-sigs.sh	(working copy)
@@ -2174,6 +2174,7 @@
   malwareexpert_update_hours="0"
   malwarepatrol_update_hours="0"
   yararulesproject_update_hours="0"
+  urlhaus_update_hours="0"
   additional_update_hours="0"
 fi
```

**Comment by perplexityjeff** [comment]
Hi @MASHtm thanks for looking into the code for the fix, always good to have more eyes to make the whole project better. I created a pull request for this https://github.com/extremeshok/clamav-unofficial-sigs/pull/390.

I implemented all fixes on my side as well and can confirm that they seem to work.

**Comment by extremeshok** [comment]
thanks will push a new version soon

**Comment by kristous** [comment]
Just wondering when the new version will be pushed
