### ISSUE TITLE
Use MD5 with MalwarePatrol

### ISSUE THREAD

**Issue by olivier2557** [extremeshok/clamav-unofficial-sigs#40]
When one has a commercial subscription to MalwarePatrol, the script can use the MD5 to check whether the signature file has changed or not.

This is a good way to save some download time (and check that the signature file downloaded OK at the end).

**Comment by extremeshok** [comment]
Unfortunately I do not have a commercial subscription, so I can't code the md5 checks.

**Comment by olivier2557** [comment]
I am trying to integrate the test for MD5 signatures, but I have a bit of a hard time understanding the logic of the script, I am stuck around line 1365:

    if ! cmp -s $malwarepatrol_dir/$malwarepatrol_db $clam_dbs/$malwarepatrol_db 
    then
      if [ "$?" = "0" ] ; then

I don't see what can trigger the second test to be false. (I don't see either what is that part executed when the test is false, the whitelist stuff, but I guess it is not as important).

So, if you can shed some light on that part of the code, I think I can come up with a patch.

**Comment by extremeshok** [comment]
First I check for a false of the running command, the false can be generated by a broken command or missing dependency.  then I evaluate the actual return code for the command which ran i.e. The command can fail, but the exit code would be different to 0. 

Basically extra check logic

**Comment by olivier2557** [comment]
In the zip file there are the patch for the script and the configuration. There are few things that I changed in the configuration because MalwarePatrol is a tad bit complicated:

- you have free subscription of paying subscription
- you have product code (8 for free, other, 7, 15... for paying)
- you have the file to download (clamav_basic for free, clamav_basic or clamav_ext for paying, one should avoid the advanced files)
- you have the receipt code
- with paying subscription, you are welcome to download every hour

Also clamav_basic is of type .db while clamav_ext is of type .ndb

Because there are so many more options, I added a block toward the top of the script to check the validity of the various options. It is needed at the top because other variables are build from these options (namely malwarepatrol_url and malwarepatrol_db).

I redid all the indentation of the MalwarePatrol part, primarily to clean the thing in my head, to be able to find the beginning and end of each if then else. I also tried to keep the logic the same for the free subscription, with the double if that I mentioned yesterday. I tried to add comments when it would make sense.

[patch.zip](https://github.com/extremeshok/clamav-unofficial-sigs/files/177511/patch.zip)

**Comment by extremeshok** [comment]
Awesom will check out it later

Thanks

**Comment by nerijus** [comment]
Could you please change the patch, so that the free remains as default?
Now it makes commercial default:
```
+malwarepatrol_receipt_code="con-msncdjsuee-8291039"
+malwarepatrol_product_code="7"; # or empty for free users
+malwarepatrol_list="clamav_ext"; # or empty for free users
 # Set to no to enable the commercial subscription url.
-malwarepatrol_free="yes"
+malwarepatrol_free="no"
```

**Comment by extremeshok** [comment]
I will sort it out, so free is default. expect a new release tomorrow or Saturday. Depends what bugs I encounter during testing.

**Comment by olivier2557** [comment]
It was evening time so I went home.

I also noticed I forgot to remove my own receipt code from the patch.conf...

**Comment by extremeshok** [comment]
removed zip due to subscription code Busy integrating the changes.

**Comment by extremeshok** [comment]
Thanks, this is will be released with v5.

Free will be made the default
