### ISSUE TITLE
systemd integration

### ISSUE THREAD

**Issue by falon** [extremeshok/clamav-unofficial-sigs#41]
Hello,

 if you have RH7/systemd you could replace crontab with systemd timer.

I attach an example of systemd timer integration. It works for me.

You have to add

`Wants=clamav-unofficial-sigs.timer`

in **clamd[at]scan.service** to execute it at boot.

[clamd@scan.service.txt](https://github.com/extremeshok/clamav-unofficial-sigs/files/152510/clamd.scan.service.txt)
[clamav-unofficial-sigs.timer.txt](https://github.com/extremeshok/clamav-unofficial-sigs/files/152511/clamav-unofficial-sigs.timer.txt)
[clamav-unofficial-sigs.service.txt](https://github.com/extremeshok/clamav-unofficial-sigs/files/152512/clamav-unofficial-sigs.service.txt)

(I renamed the file as txt to let github uploads).
Best Regards

**Comment by extremeshok** [comment]
Can you please give me the full file path of each file on a RHEL/systemd ?

**Comment by falon** [comment]
I have placed all files in _/usr/lib/systemd/system/_

**Comment by prupert** [comment]
Hi,

Only packages should install files in /usr/lib/systemd. You can place your own files in /etc/systemd. 

On a related note: it would be awesome if somebody would take the task of maintaining RPM packages of the extremeshok version of clamav-unofficial-sigs. 

Pim

**Comment by extremeshok** [comment]
packages will be done with v5

I have .rpm and .deb build servers.

**Comment by extremeshok** [comment]
added systemd files
1031a27a51eeacbd914498d38cf3200907636c50
