### ISSUE TITLE
Conf file changes for CentOS7

### ISSUE THREAD

**Issue by maayant** [extremeshok/clamav-unofficial-sigs#45]
The following changes to clamav-unofficial-sigs.conf required for clamav-unofiicial-sigs to work correctly under CentOS7:
```
clam_user="clamupdate"
clam_group="clamupdate"
 
clamd_restart_opt="systemctl restart clamd@scan"
```

**Comment by extremeshok** [comment]
Thanks added to the config 5c7013f5e64a63ffa79799fb04115493dc1ff036
