### ISSUE TITLE
Error from CRON execution

### ISSUE THREAD

**Issue by Mattyx** [extremeshok/clamav-unofficial-sigs#47]
Hi,
I received the following error:

> /usr/local/bin/clamav-unofficial-sigs.sh: line 1197: [: missing `]'

The script version is 5.0.0

Of course, I haven't edited this file.

**Comment by extremeshok** [comment]
Version 5 ?

**Comment by Mattyx** [comment]
Yes, I downloaded it about 6 hours ago

**Comment by extremeshok** [comment]
Can you please paste lines 1195 -> 1200 ?

**Comment by sakkask** [comment]
Line 1098
` if [ "$remove_bad_database" == "yes" ] ; then`

Space missing before closing `]`

**Comment by extremeshok** [comment]
fixed in 5.0.2

thanks for the heads up
