### ISSUE TITLE
max connections (20) reached

### ISSUE THREAD

**Issue by takenek** [extremeshok/clamav-unofficial-sigs#48]
Hey
I just get error in e-mail:
@ERROR: max connections (20) reached -- try again later rsync error: error starting client-server protocol (code 5) at main.c(1653) [Receiver=3.1.1]

I am not sure how to understand this error....

Thanks

**Comment by extremeshok** [comment]
once off error ?

**Comment by takenek** [comment]
For now only 1 time got this.. next time was ok... strange...

**Comment by extremeshok** [comment]
I know the mirrors rate limit and ip limit.

So it could of been that.

**Comment by takenek** [comment]
I don`t force - he run script from crontab mayby i change a little script because now everyone who use Your script connect to mirrors every hour 45 :-)
45 * * * *
If You know what i mean...?
