### ISSUE TITLE
Silent the curl log for malwarepatrol

### ISSUE THREAD

**Issue by alessiocecchi** [extremeshok/clamav-unofficial-sigs#50]
Hi, I enabled malwarepatrol signature but every time the sig is updated i receive via email the output of curl download:

From: "Cron Daemon" <root@mx02>
To: root@mx02
Subject: Cron <root@mx02> /bin/bash /usr/local/bin/clamav-unofficial-sigs.sh  > /dev/null
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
102  1025    0  1025    0     0    402      0 --:--:--  0:00:02 --:--:--  1370
100 5359k    0 5359k    0     0  1524k      0 --:--:--  0:00:03 --:--:-- 3126k
100 6914k    0 6914k    0     0  1894k      0 --:--:--  0:00:03 --:--:-- 3741k

Can be silent?
Thanks

**Comment by extremeshok** [comment]
latest version ?

**Comment by alessiocecchi** [comment]
No: Version: v4.9.2 (02 December 2015)
I see now the update version.
