### ISSUE TITLE
clamav-unofficial-sigs.log mnot generated

### ISSUE THREAD

**Issue by clamal** [extremeshok/clamav-unofficial-sigs#51]
Hi,
I installed the last version, the program runs but doesn't generate the log in the directory.
In the master.comf I have:

# Log update information to '$log_file_path/$log_file_name'.
enable_logging="yes"
log_file_path="/usr/local/etc/clamav-log/"
log_file_name="clamav-unofficial-sigs.log"

Best Regards.

**Comment by extremeshok** [comment]
the directory needs to exist and be writable /usr/local/etc/clamav-log/

The script will check the dir exists and it will attempt to create the log_file_name, after that it will check the file is writable.

If those fail, logging will be disabled.

**Comment by clamal** [comment]
Yes, the directory exists and it is writable. I upgraded from the december version that could write in this directory. I've changed to 777, but the log isn't created.

**Comment by smwardle** [comment]
I also have this problem on Linux and OS X since updating to version 5.0.2.
5.0.0 was generating logs correctly.

**Comment by smwardle** [comment]
It uses logging_enabled in the script and enable_logging in the conf.

**Comment by clamal** [comment]
Yes, this was the problem. I added it in master.
Best Regards.

**Comment by extremeshok** [comment]
Thanks, will push a fix soon

**Comment by extremeshok** [comment]
226e4a7e4c88493a557e3185e4dcdce2d7490ed3
