### ISSUE TITLE
Bring back the reload_opt option

### ISSUE THREAD

**Issue by Gazoo** [extremeshok/clamav-unofficial-sigs#54]
In Centos 7 the default clamav configuration file from the EPEL repo is located at /etc/clamd.d/scan.conf not /etc/clamd.conf. This allows you to run multiple clamav instances.

This code will always fail as it doesn't specify the config file to use:
```
myresult=`clamdscan --reload 2>&1`
```
Previously you could set config option "reload_opt" but this option is now missing:
```
reload_opt="clamdscan --config-file=/etc/clamd.d/scan.conf --reload"
```
Here is an example as to how Clamav is setup on Centos 7:
https://ismailyenigul.wordpress.com/2015/01/05/install-clamav-on-centos-7/

**Comment by Gazoo** [comment]
I guess creating a symlink would fix this also:
`ln -s /etc/clamd.d/scan.conf /etc/clamd.conf`

**Comment by extremeshok** [comment]
Please test with https://github.com/extremeshok/clamav-unofficial-sigs/tree/dev

Reload option added in 6030a8f87723d36ab0f07ab6e714fbe53e4d0df1

**Comment by Gazoo** [comment]
I noticed you changed the centos 7 restart to:
```
clamd_restart_opt="systemctl restart clamd"
```
Unfortunately that won't work as there is no clamd service file. Here are the default locations for the Centos 7 ClamAV packages from EPEL:
```
clamd_restart_opt="systemctl restart clamd@scan"
clamd_pid="/var/run/clamd.scan/clamd.pid"
clamd_socket="/var/run/clamd.scan/clamd.sock"
clamd_reload_opt="clamdscan --config-file=/etc/clamd.d/scan.conf --reload"
```
Thanks again for all your work. The new version looks great!

**Comment by extremeshok** [comment]
Fixed in 2afe3fcf7e6ef28c6c360f638ed6e7b7f3e8549b

Is clam_dbs="/var/lib/clamav" correct ? My centos 7 vm only goes online on 1 April

**Comment by nerijus** [comment]
Correct.

**Comment by extremeshok** [comment]
thanks
