### ISSUE TITLE
Hide CURL connection problems errors.

### ISSUE THREAD

**Issue by takenek** [extremeshok/clamav-unofficial-sigs#55]
hey
Today morning i get e-mail with:
curl: (28) Connection timed out after 30001 milliseconds
curl: (28) Connection timed out after 30001 milliseconds
curl: (28) Connection timed out after 30001 milliseconds
curl: (28) Connection timed out after 30000 milliseconds
curl: (28) Connection timed out after 30001 milliseconds
curl: (28) Connection timed out after 30001 milliseconds

Mayby hide this information or do something else with this :-)
Thanks!

**Comment by extremeshok** [comment]
Possible fix in 232cb2e4837613e826f4d8883057585c4f05d2b9
