### ISSUE TITLE
logrotate error: clamav-unofficial-sigs:24 unknown user 'clam'

### ISSUE THREAD

**Issue by Gazoo** [extremeshok/clamav-unofficial-sigs#56]
The clamav-unofficial-sigs cron mails out this error when logrotate is run because the clam user doesn't exist when using the Centos 7 EPEL clamav packages.

Here are the users added and used by the EPEL clamav packages:
```
grep clam /etc/passwd
clamupdate:x:987:989:Clamav database update user:/var/lib/clamav:/sbin/nologin
clamscan:x:986:988:Clamav scanner user:/:/sbin/nologin
```
clamscan is the user used by clamav and clamupdate is used by freshclam.

**Comment by extremeshok** [comment]
55befe3cb945ec585fed5674be850c0354486f87
