### ISSUE TITLE
log_file_path is not correctly used

### ISSUE THREAD

**Issue by IdahoPL** [extremeshok/clamav-unofficial-sigs#57]
OS: FreeBSD 10.2

There's log_file_path defined in my os.conf:

 # grep log_file_path /usr/local/etc/clamav-unofficial-sigs/os.conf
log_file_path="/var/log/clamav"`

Script is throwing warning that log file is not writable (notice wrong log_file_path):

 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v5.0.3 (27 March 2016)
 Required Configuration Version: v55
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com

Loading config: /usr/local/etc/clamav-unofficial-sigs/master.conf
Loading config: /usr/local/etc/clamav-unofficial-sigs/os.conf
Warning: Logging Disabled, as file not writable: /var/log/clamav-unofficial-sigs/clamav-unofficial-sigs.log
Loading config: /usr/local/etc/clamav-unofficial-sigs/user.conf
Sanesecurity Database & GPG Signature File Updates

**Comment by twouters** [comment]
You can work around this by setting `logging_enabled=true` in your os.conf or user.conf

**Comment by IdahoPL** [comment]
Not reallly. Script checks if log file is readable after every config file load. So if I set logging_enabled=true in os.conf the warning will appear after reading master.conf.

In master.conf logging_enabled variable is set to "yes" by default. If I set it to true the warning will be masked as you said, but this change should go to master.conf.

**Comment by extremeshok** [comment]
Basically it does this.
if logging_enabled=true and logfile writable enable loggin else disable logging
The config where the custom logfile is specified will also need the logging_enabled varible.

The 3 variables should be specified in the config you want to use.
$logging_enabled="yes" 
$log_file_path
$log_file_name

In v5.04 im thinking of moving these options into the os.xxxx.conf files or into the user.conf file.
And have logging disabled in the master.conf

**Comment by extremeshok** [comment]
This should be fixed with 2ca2d88f827872c845263db0a8641d81b1038184

**Comment by IdahoPL** [comment]
I'm afraid that this fix introduced another bug. With default master.conf and default os.conf for FreeBSD script first creates default log directory /var/log/clamav-unofficial-sigs, then reads log_file_path from os.conf and then uses /var/log/clamav:

 # ls /var/log/clamav-unofficial-sigs /var/log/clamav
ls: /var/log/clamav-unofficial-sigs: No such file or directory
/var/log/clamav:

 # clamav-unofficial-sigs.sh
<output removed>

 # ls /var/log/clamav-unofficial-sigs /var/log/clamav
/var/log/clamav:
clamav-unofficial-sigs.log

/var/log/clamav-unofficial-sigs:
clamav-unofficial-sigs.log

**Comment by extremeshok** [comment]
Thanks for finding it, will edit the code later.

**Comment by extremeshok** [comment]
fixed in 7c55bf80c15d5128daec56c4b1917d939a76a082
