### ISSUE TITLE
work_dir variable is used too early

### ISSUE THREAD

**Issue by IdahoPL** [extremeshok/clamav-unofficial-sigs#62]
os.freebsd.conf changes work_dir to /var/db/clamav-unofficial-sigs. Default work_dir in master.conf is set to /var/lib/clamav-unofficial-sigs. Both directories are created and used.

work_dir should not be used before reading all config files.

**Comment by extremeshok** [comment]
I disagree.

Configs are initialized and loaded way before the workdir varible is used.

**Comment by IdahoPL** [comment]
Well, I disagree to your disagree ;)

 # grep -E ^work_dir= /usr/local/etc/clamav-unofficial-sigs/*.conf
/usr/local/etc/clamav-unofficial-sigs/master.conf:work_dir="/var/lib/clamav-unofficial-sigs"   #Top level working directory
/usr/local/etc/clamav-unofficial-sigs/os.conf:work_dir="/var/db/clamav-unofficial-sigs"

 # ls /var/lib/clamav-unofficial-sigs
ls: /var/lib/clamav-unofficial-sigs: No such file or directory

 # ls /var/db/clamav-unofficial-sigs
ls: /var/db/clamav-unofficial-sigs: No such file or directory

 # clamav-unofficial-sigs.sh

[ output removed ]

 # ls /var/lib/clamav-unofficial-sigs
configs         dbs-add         dbs-lmd         dbs-mbl         dbs-si          dbs-ss          dbs-yara        gpg-key

 # ls /var/db/clamav-unofficial-sigs

**Comment by extremeshok** [comment]
AAH i see what u mean, will code a fix shortly.

master.conf sets the varibles.
sanesecurity_dir="$work_dir/dbs-ss"        # Sanesecurity sub-directory
securiteinfo_dir="$work_dir/dbs-si"        # SecuriteInfo sub-directory 
linuxmalwaredetect_dir="$work_dir/dbs-lmd"      # Linux Malware Detect sub-directory 
malwarepatrol_dir="$work_dir/dbs-mbl"      # MalwarePatrol sub-directory 
yararules_dir="$work_dir/dbs-yara"      # Yara-Rules sub-directory 
work_dir_configs="$work_dir/configs"   # Script configs sub-directory
gpg_dir="$work_dir/gpg-key"      # Sanesecurity GPG Key sub-directory
add_dir="$work_dir/dbs-add"      # User defined databases sub-directory

so if the work_dir is set in os.conf the add_dir will be invalid.

**Comment by extremeshok** [comment]
fixed in b462643e6e7682276c6fc355254320d447be3440
