### ISSUE TITLE
unary operator expected

### ISSUE THREAD

**Issue by jayharland** [extremeshok/clamav-unofficial-sigs#70]
It's probably something I'm doing wrong, but here are the steps I took to get this installed/running and where I'm stuck:

1. I followed the quick install guide on the homepage
2. Once completed, I execute clamav-unofficial-sigs.sh
3. Initially, it threw an error because my directories weren't set right
4. After that was fixed, I try again but the execution just hangs for a couple minutes then nothing, no output
5. I see no databases downloaded into the clamav db directory so I assume it did not work
6. I try executing again like this: clamav-unoffical-sigs.sh -c /path/to/user.conf

That gives me this:

> /usr/local/bin/clamav-unofficial-sigs.sh: line 283: [: -lt: unary operator expected
> mkdir: cannot create directory `': No such file or directory
> mkdir: cannot create directory `': No such file or directory
> mkdir: cannot create directory `': No such file or directory
> mkdir: cannot create directory `': No such file or directory
> mkdir: cannot create directory `': No such file or directory
> mkdir: cannot create directory `': No such file or directory
> mkdir: cannot create directory `': No such file or directory
> mkdir: cannot create directory `': No such file or directory
> mkdir: cannot create directory `': No such file or directory
> chmod: cannot access `': No such file or directory
> curl: option --connect-timeout: expected a proper numerical parameter
> curl: try 'curl --help' or 'curl --manual' for more information

Any help out there?

**Comment by jayharland** [comment]
Just an update,

**Comment by extremeshok** [comment]
save the configs to /etc/clamav-unofficial-sigs/

replace your master.conf with the one from the script https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/config/master.conf

rename the os.youros.conf to os.conf ( https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/config/os.slackware.conf ) where youros = your OS (eg. debian/ubuntu/centos)

edit/set your values in user.conf

then run 
````
bash clamav-unofficial-sigs.sh
````

It will work

**Comment by extremeshok** [comment]
Added an error check to prevent issues : f780d92daf41b3000404cf87b62c9d00a38e35ef
