### ISSUE TITLE
database integrity tested BAD CENTOS 6.7

### ISSUE THREAD

**Issue by jayharland** [extremeshok/clamav-unofficial-sigs#71]
Hello,

So I've followed the set up guide, but when I run clamav-unofficial-sigs.sh the log file indicates that every database has failed the integrity test. I've included the log file output at the end as well as the clamav-unofficial-sigs information.

It was recommended that it's either "a permission issue or an invalid setting".

I'm looking for help getting it working. Which permissions should I check? Otherwise, the only setting I changed in the os.conf file was the directory to clamav databases. Since I'm trying to set this up on a VPS, I found the databases stored in: "/usr/local/cpanel/3rdparty/share/clamav"

Thanks

> *** SCRIPT VERSION ***
> clamav-unofficial-sigs.sh 5.0.4 (31 March 2016)
> *** SYSTEM INFORMATION ***
> Linux XXXXXXXXXXXXXXXXXXXX 2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
> *** CLAMSCAN LOCATION & VERSION ***
> which: no clamscan in (/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin)
> clamav-unofficial-sigs.sh: line 396: --version: command not found
> 
> *** RSYNC LOCATION & VERSION ***
> /usr/bin/rsync
> rsync  version 3.0.6  protocol version 30
> *** CURL LOCATION & VERSION ***
> /usr/bin/curl
> curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> *** GPG LOCATION & VERSION ***
> /usr/bin/gpg
> gpg (GnuPG) 2.0.14
> *** SCRIPT WORKING DIRECTORY INFORMATION ***
> drwxr-xr-x 10 root root 4096 Feb 24 14:40 /var/lib/clamav-unofficial-sigs
> /var/lib/clamav-unofficial-sigs:
> drwxr-xr-x 2 root root 4096 Mar 31 12:08 configs
> drwxr-xr-x 2 root root 4096 Feb 24 14:40 dbs-add
> drwxr-xr-x 2 root root 4096 Mar 31 07:47 dbs-lmd
> drwxr-xr-x 2 root root 4096 Mar 31 12:08 dbs-mbl
> drwxr-xr-x 2 root root 4096 Mar 31 10:24 dbs-si
> drwxr-xr-x 2 root root 4096 Mar 31 12:08 dbs-ss
> drwxr-xr-x 2 root root 4096 Feb 24 14:40 dbs-yara
> drwx------ 2 root root 4096 Mar 31 12:08 gpg-key
> 
> /var/lib/clamav-unofficial-sigs/configs:
> -rw-r--r-- 1 root root 5318 Mar 31 12:08 current-dbs.txt
> -rw-r--r-- 1 root root    0 Mar 31 10:38 db-changes.txt
> -rw-r--r-- 1 root root   11 Mar 31 07:47 last-linuxmalwaredetect-update.txt
> -rw-r--r-- 1 root root   11 Mar 31 12:08 last-mbl-update.txt
> -rw-r--r-- 1 root root   11 Mar 31 10:23 last-si-update.txt
> -rw-r--r-- 1 root root 5318 Mar 31 12:08 previous-dbs.txt
> -rw-r--r-- 1 root root 6312 Mar 31 12:08 purge.txt
> -rw-r--r-- 1 root root   34 Feb 24 14:53 scan-test.txt
> -rw-r--r-- 1 root root  990 Mar 31 12:08 ss-include-dbs.txt
> 
> /var/lib/clamav-unofficial-sigs/dbs-add:
> 
> /var/lib/clamav-unofficial-sigs/dbs-lmd:
> 
> /var/lib/clamav-unofficial-sigs/dbs-mbl:
> 
> /var/lib/clamav-unofficial-sigs/dbs-si:
> 
> /var/lib/clamav-unofficial-sigs/dbs-ss:
> -rw-r--r-- 1 root root 72 Mar 31 01:02 badmacro.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:56 blurl.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 31 09:56 bofhland_cracked_URL.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 31 06:56 bofhland_malware_URL.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 28 22:55 bofhland_malware_attach.hdb.sig
> -rw-r--r-- 1 root root 72 Mar 31 03:56 bofhland_phishing_URL.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 31 02:55 crdfam.clamav.hdb.sig
> -rw-r--r-- 1 root root 72 Aug  7  2015 hackingteam.hsb.sig
> -rw-r--r-- 1 root root 72 Mar 31 01:02 junk.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:56 jurlbl.ndb.sig
> -rw-r--r-- 1 root root 72 Nov 27  2014 malwarehash.hsb.sig
> -rw-r--r-- 1 root root 72 Mar 31 08:09 phish.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:56 phishtank.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:56 porcupine.hsb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:56 porcupine.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:56 rogue.hdb.sig
> -rw-r--r-- 1 root root 72 Mar  9 00:56 sanesecurity.ftm.sig
> -rw-r--r-- 1 root root 72 Mar 27 02:52 scam.ndb.sig
> -rw-r--r-- 1 root root 72 Mar 14 04:52 sigwhitelist.ign2.sig
> -rw-r--r-- 1 root root 72 Jan 15 02:58 spamattach.hdb.sig
> -rw-r--r-- 1 root root 72 Dec 24 08:50 spamimg.hdb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:45 winnow.attachments.hdb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:45 winnow_bad_cw.hdb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:45 winnow_extended_malware.hdb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:45 winnow_malware.hdb.sig
> -rw-r--r-- 1 root root 72 Mar 31 11:56 winnow_malware_links.ndb.sig
> 
> /var/lib/clamav-unofficial-sigs/dbs-yara:
> 
> /var/lib/clamav-unofficial-sigs/gpg-key:
> -rw-r--r-- 1 root root 1762 Feb  7  2012 publickey.gpg
> -rw-r--r-- 1 root root    0 Feb 24 14:40 secring.gpg
> -rw-r--r-- 1 root root 1205 Feb 24 14:40 ss-keyring.gpg
> -rw-r--r-- 1 root root    0 Feb 24 14:40 ss-keyring.gpg~
> -rw-r--r-- 1 root root 1200 Feb 24 14:40 trustdb.gpg
> *** CLAMAV DIRECTORY INFORMATION ***
> drwxrwxr-x 3 root root 4096 Mar 30 12:28 /usr/local/cpanel/3rdparty/share/clamav
> -rw-r--r-- 1 root root     68379 Mar 17 12:35 bytecode.cvd
> -rw-r--r-- 1 root root     14905 Nov 19 12:10 copyright
> -rw-r--r-- 1 root root   6493184 Mar 30 12:28 daily.cld
> -rw-r--r-- 1 root root 109143933 Mar 17 12:35 main.cvd
> -rw-r--r-- 1 root root      1144 Mar 30 12:28 mirrors.dat
> *** SCRIPT CONFIGURATION SETTINGS ***

> Mar 31 10:45:03 Loading config: /etc/clamav-unofficial-sigs/os.conf
> Mar 31 10:45:03 Loading config: /etc/clamav-unofficial-sigs/user.conf
> Mar 31 10:45:03 Thu Mar 31 10:45:03 PDT 2016 - Pausing database file updates for 94 seconds...
> Mar 31 10:46:37 Thu Mar 31 10:46:37 PDT 2016 - Pause complete, checking for new database files...
> Mar 31 10:46:37 Sanesecurity Database & GPG Signature File Updates
> Mar 31 10:46:37 Sanesecurity mirror site used: web.virusfree.cz 212.24.139.164
> Mar 31 10:46:44 Testing updated Sanesecurity database file: sanesecurity.ftm
> Mar 31 10:46:44 Clamscan reports Sanesecurity sanesecurity.ftm database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/sanesecurity.ftm
> Mar 31 10:46:44 Testing updated Sanesecurity database file: sigwhitelist.ign2
> Mar 31 10:46:44 Clamscan reports Sanesecurity sigwhitelist.ign2 database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/sigwhitelist.ign2
> Mar 31 10:46:44 Testing updated Sanesecurity database file: junk.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity junk.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/junk.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: jurlbl.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity jurlbl.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/jurlbl.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: phish.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity phish.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/phish.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: rogue.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity rogue.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/rogue.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: scam.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity scam.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/scam.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: spamimg.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity spamimg.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/spamimg.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: spamattach.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity spamattach.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/spamattach.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: blurl.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity blurl.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/blurl.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: badmacro.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity badmacro.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/badmacro.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: malwarehash.hsb
> Mar 31 10:46:44 Clamscan reports Sanesecurity malwarehash.hsb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/malwarehash.hsb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: winnow.attachments.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity winnow.attachments.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/winnow.attachments.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: winnow_malware.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity winnow_malware.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/winnow_malware.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: winnow_malware_links.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity winnow_malware_links.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/winnow_malware_links.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: winnow_extended_malware.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity winnow_extended_malware.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/winnow_extended_malware.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: winnow_bad_cw.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity winnow_bad_cw.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/winnow_bad_cw.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: bofhland_cracked_URL.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity bofhland_cracked_URL.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/bofhland_cracked_URL.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: bofhland_malware_URL.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity bofhland_malware_URL.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/bofhland_malware_URL.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: bofhland_phishing_URL.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity bofhland_phishing_URL.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/bofhland_phishing_URL.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: bofhland_malware_attach.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity bofhland_malware_attach.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/bofhland_malware_attach.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: hackingteam.hsb
> Mar 31 10:46:44 Clamscan reports Sanesecurity hackingteam.hsb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/hackingteam.hsb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: crdfam.clamav.hdb
> Mar 31 10:46:44 Clamscan reports Sanesecurity crdfam.clamav.hdb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/crdfam.clamav.hdb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: porcupine.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity porcupine.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/porcupine.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: phishtank.ndb
> Mar 31 10:46:44 Clamscan reports Sanesecurity phishtank.ndb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/phishtank.ndb
> Mar 31 10:46:44 Testing updated Sanesecurity database file: porcupine.hsb
> Mar 31 10:46:44 Clamscan reports Sanesecurity porcupine.hsb database integrity tested BAD
> Mar 31 10:46:44 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-ss/porcupine.hsb
> Mar 31 10:46:44 No Sanesecurity database file updates found
> Mar 31 10:46:44 SecuriteInfo Database File Updates
> Mar 31 10:46:44 4 hours have not yet elapsed since the last SecuriteInfo update check
> Mar 31 10:46:44 No update check was performed at this time
> Mar 31 10:46:44 Next check will be performed in approximately 3 hour(s), 37 minute(s)
> Mar 31 10:46:44 linuxmalwaredetect Database File Updates
> Mar 31 10:46:44 6 hours have not yet elapsed since the last linux malware detect update check
> Mar 31 10:46:44 No update check was performed at this time
> Mar 31 10:46:44 Next check will be performed in approximately 3 hour(s), 1 minute(s)
> Mar 31 10:46:44 Checking for MalwarePatrol updates...
> Mar 31 10:46:44 MalwarePatrol  Database File Update
> Mar 31 10:46:45 Testing updated MalwarePatrol database file: malwarepatrol.db
> Mar 31 10:46:45 Clamscan reports MalwarePatrol malwarepatrol.db database integrity tested BAD
> Mar 31 10:46:45 Removed invalid database: /var/lib/clamav-unofficial-sigs/dbs-mbl/malwarepatrol.db
> Mar 31 10:46:45 No updates detected, ClamAV databases were not reloaded
> Mar 31 10:46:45 Issue tracker : https://github.com/extremeshok/clamav-unofficial-sigs/issues
> Mar 31 10:46:45       Powered By https://eXtremeSHOK.com

**Comment by jayharland** [comment]
> *** CLAMSCAN LOCATION & VERSION ***
> which: no clamscan in (/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin)
> clamav-unofficial-sigs.sh: line 396: --version: command not found

Well if it can't find clamscan then it won't work I'm guessing. I'm not seeing anywhere to update that though...  I know where it's located.

**Comment by jayharland** [comment]
I got it working. This link helped me: https://encylia.com/2014/03/18/clamav-installed-but-not-working-on-the-command-line-and-appears-to-not-be-installed/

Once I made a symlink to clamscan and related files inside usr/local/bin the databases tested good, etc.

**Comment by extremeshok** [comment]
Are the following settings correct for centos 6 + cpanel
````
# RHEL/CentOS 6 with cPanel
clam_user="clam"
clam_group="clam"

clam_dbs="/usr/local/cpanel/3rdparty/share/clamav"

clamd_pid="/var/run/clamav/clamd.pid"

clamd_restart_opt="service clamd restart"

#clamd_socket="/var/run/clamd.socket"

clamscan_bin="/usr/local/cpanel/3rdparty/bin/clamscan"
````

**Comment by extremeshok** [comment]
Please test with the latest "DEV" version

**Comment by jayharland** [comment]
Those settings are correct.
