### ISSUE TITLE
cronjob as clamav user

### ISSUE THREAD

**Issue by reneschuster** [extremeshok/clamav-unofficial-sigs#87]
Latest version is using clamav as cronjob user.
But that will fail to update the databases because of missing permissions if the cronjob was running before as root or if the user has run the script once manually as root. The same also with the log directory and logfiles.

I changed the permissions on my systems but other users will also get this problems.

Cron error mail:
chown: changing ownership of ‘/var/lib/clamav/rfxn.ndb’: Operation not permitted
chown: changing ownership of ‘/var/lib/clamav/rfxn.hdb’: Operation not permitted
chmod: changing permissions of ‘/var/lib/clamav/rfxn.ndb’: Operation not permitted
chmod: changing permissions of ‘/var/lib/clamav/rfxn.hdb’: Operation not permitted

**Comment by extremeshok** [comment]
When the script is run as root, the correct ownership/perms should be set. So that when its run as cron, the perms are correct.

I dont want to run the cron as the root user.

Will push a fix

**Comment by smwardle** [comment]
I my case maldetect is being used to update /var/lib/clamav/rfxn.ndb and /var/lib/clamav/rfxn.hdb and leaves the owner as root.
The cronjob runs as user clam and attempts a blanket change of ownership to clam which shows the error messages.

**Comment by extremeshok** [comment]
should be fixed in the latest dev branch

**Comment by reneschuster** [comment]
Log directory and file are still created as root:

```
root@test ~ # ls -ld /var/log/clamav-unofficial-sigs/
drwxr-xr-x 2 root root 4,0K Apr 12 00:09 /var/log/clamav-unofficial-sigs/
root@test ~ # ls -l /var/log/clamav-unofficial-sigs/*
-rw-r--r-- 1 root root 16K Apr 12 00:09 /var/log/clamav-unofficial-sigs/clamav-unofficial-sigs.log
```

**Comment by extremeshok** [comment]
should be fixed with 798a70e2c443b52d57ca4bfdcd79e0fa2ab3d96a

**Comment by reneschuster** [comment]
Thanks, but I don't know if you have seen that I edited my previous comment and also added the info about `/var/lib/clamav-unofficial-sigs/` directory.

**Comment by extremeshok** [comment]
Please test with 97f540307e916584cc57e164a9cc5150657848cf

**Comment by reneschuster** [comment]
Log directory and file is ok and also all directories in `/var/lib/clamav-unofficial-sigs/` but the databases are still on root user and group.

```
-rw-r--r-- 1 root root  11K Mär  9 09:56 /var/lib/clamav-unofficial-sigs/dbs-ss/sanesecurity.ftm
-rw-r--r-- 1 root root   72 Mär  9 09:56 /var/lib/clamav-unofficial-sigs/dbs-ss/sanesecurity.ftm.sig
-rw-r--r-- 1 root root 1,5K Jul  1  2015 /var/lib/clamav-unofficial-sigs/dbs-ss/Sanesecurity_sigtest.yara
-rw-r--r-- 1 root root   72 Jul  1  2015 /var/lib/clamav-unofficial-sigs/dbs-ss/Sanesecurity_sigtest.yara.sig
-rw-r--r-- 1 root root 1,3K Feb 22 13:21 /var/lib/clamav-unofficial-sigs/dbs-ss/Sanesecurity_spam.yara
-rw-r--r-- 1 root root   72 Feb 22 13:54 /var/lib/clamav-unofficial-sigs/dbs-ss/Sanesecurity_spam.yara.sig
-rw-r--r-- 1 root root  14M Apr 12 00:45 /var/lib/clamav-unofficial-sigs/dbs-ss/scamnailer.ndb
-rw-r--r-- 1 root root   72 Apr 11 18:55 /var/lib/clamav-unofficial-sigs/dbs-ss/scamnailer.ndb.sig
-rw-r--r-- 1 root root 1,8M Apr  3 19:57 /var/lib/clamav-unofficial-sigs/dbs-ss/scam.ndb
-rw-r--r-- 1 root root   72 Apr  3 19:57 /var/lib/clamav-unofficial-sigs/dbs-ss/scam.ndb.sig

```

**Comment by reneschuster** [comment]
And please don't change the owner and group of `cron.d` and `logrotate.d`

```
root@test ~ # ls -ld /etc/cron.d/ /etc/logrotate.d/
drwxr-xr-x 2 clamav clamav 4,0K Apr 12 01:06 /etc/cron.d/
drwxr-xr-x 2 clamav clamav 4,0K Apr 12 01:06 /etc/logrotate.d/
```

**Comment by extremeshok** [comment]
Dirs : 9de35b37f59f312c0e2b3f558c7d7c0a5aea62d9

**Comment by reneschuster** [comment]
Log should stay on clamav

```
root@test ~ # ls -ld /var/log /var/log/clamav-unofficial-sigs/
drwxr-xr-x 20 root   root    36K Apr 12 01:30 /var/log
drwxr-xr-x  2 clamav clamav 4,0K Apr 12 01:30 /var/log/clamav-unofficial-sigs/
```

**Comment by extremeshok** [comment]
going to break logging on some platforms that use /var/log/mylog.log, as it will chown the /var/log

**Comment by extremeshok** [comment]
files fixed in 21e5439d06c7989d8749ed7b1057b6cf02bdc03e

**Comment by reneschuster** [comment]
Now it looks good and all is working as suspected. 

You should mention that the script has to be run once as root, to set all the permissions.

Or just create a --install option, which has to be executed once where all directories with the permissions are created and also the cron, logrotate and log files.

**Comment by extremeshok** [comment]
?? 

### First Usage
* Run the script once as your superuser to set all the permissions and create the relevant directories

**Comment by reneschuster** [comment]
That's fine for me.
