### ISSUE TITLE
databases unexpectedly deleted from /var/lib/clamav

### ISSUE THREAD

**Issue by stewardle** [extremeshok/clamav-unofficial-sigs#88]
I automatically change setting securiteinfo_enabled="yes" to securiteinfo_enabled="no" to prevent large downloads at certain times of day.
Now when clamav-unofficial-sigs.sh runs it deletes those databases.
This is not expected.
It's a download tool not a database management tool.
It is also trying to change permissions in the clamav database directory which causes errors.

**Comment by extremeshok** [comment]
Commit fe6b0b8 will fix this, please test with the latest dev

Added the config option remove_disabled_databases # Default is "no", if enabled when a database is disabled we will remove the associated database files.

**Comment by extremeshok** [comment]
check 5.2.2 please

**Comment by stewardle** [comment]
On Mon, 18 Apr 2016 01:44:17 -0700
eXtremeSHOK <notifications@github.com> wrote:

> check 5.2.2 please
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/extremeshok/clamav-unofficial-sigs/issues/88#issuecomment-211274277

Still broken in 5.2.2

Also typos lines 1526 & 2225, "$yararulesproject_enabledd".

Steve

**Comment by reneschuster** [comment]
@extremeshok 

Do you know http://www.shellcheck.net?
Could help you to eliminate typos and also some bugs.
