### ISSUE TITLE
sanesecurity_dbs in master.conf out of step with http://sanesecurity.com/usage/signatures/

### ISSUE THREAD

**Issue by stewardle** [extremeshok/clamav-unofficial-sigs#90]
Minor niggle. Different risk levels and foxhole_js.cdb missing.

In master.conf 
#foxhole_generic.cdb #MED See Foxhole page for more details
#foxhole_filename.cdb #MED See Foxhole page for more details

At http://sanesecurity.com/usage/signatures
/foxhole_generic.cdb 	See Foxhole page for more details 	Low
foxhole_filename.cdb 	See Foxhole page for more details 	Low
foxhole_js.cdb 	See Foxhole page for more details 	Med

**Comment by extremeshok** [comment]
Thanks, fixed with d18fd3295014cfb08d14b88b1eab10505f36efa7
