### ISSUE TITLE
work_dir_configs cannot be configured outside work-dir

### ISSUE THREAD

**Issue by sts** [extremeshok/clamav-unofficial-sigs#94]
Working on a up to date Debian package for clamav-unofficial-sigs and it looks like one was previously able to configure work_dir_configs outside of work_dir.

Debian by splits up the work_dir from work_dir_configs into /var/cache/clamav-unofficial-sigs and /var/lib/clamav-unofficial-sigs respectively.

Is it possible to make work_dir_configs configurable again?

**Comment by extremeshok** [comment]
Packages will come once Ive completed a few things with the script

Whats the reason for splitting up the dirs to /var/cache and /var/lib?
Because the generated "config" and the gpg are program extras not libraries 

work_dir : /var/cache/clamav-unofficial-sigs/ 
holds the database (dbs-ss, dbl, yara.....)

work_dir_configs : /var/lib/clamav-unofficial-sigs
holds (config, gpg)

**Comment by sts** [comment]
Hi, I'm not the official Debian maintainer, but I would like to get a working package online, and I'm almost finished. I don't exactly know why they split it up in the past, but I assume its a FHS thing:

#### ```/var/lib``` : Variable state information
Holds dynamic data libraries/files like the rpm/dpkg database and game scores. Furthermore, this hierarchy holds state information pertaining to an application or the system. State information is data that programs modify while they run, and that pertains to one specific host. Users shouldn't ever need to modify files in /var/lib to configure a package's operation. State information is generally used to preserve the condition of an application (or a group of inter-related applications) between invocations and between different instances of the same application. An application (or a group of inter-related applications) use a subdirectory of /var/lib for their data. There is one subdirectory, /var/lib/misc, which is intended for state files that don't need a subdirectory; the other subdirectories should only be present if the application in question is included in the distribution. /var/lib/'name' is the location that must be used for all distribution packaging support. Different distributions may use different names, of course.

### ```/var/cache``` : Application cache data
Is intended for cached data from applications. Such data is locally generated as a result of time-consuming I/O or calculation. This data can generally be regenerated or be restored.  Unlike /var/spool, files here can be deleted without data loss. This data remains valid between invocations of the application and rebooting of the system. The existence of a separate directory for cached data allows system administrators to set different disk and backup policies from other directories in /var.

**Comment by extremeshok** [comment]
Interesting ..
Will add support

BTW you can fork and create pull requests and code improvements/suggestions are always welcome.

**Comment by extremeshok** [comment]
this has been completed in the latest dev.
