### ISSUE TITLE
Configuration variables not respected by install_logrotate() function

### ISSUE THREAD

**Issue by markonjezic** [extremeshok/clamav-unofficial-sigs#95]
These configuration variables are not actually used by install_logrotate() function:

logrotate_user
logrotate_group
logrotate_log_file_full_path

Additionally, in code that checks if configuration variables are set, you'll notice that logrotate_user is being set twice (first to clam_user, then to clam_group).

**Comment by extremeshok** [comment]
Thanks for the heads up, Appears my commit didn't push ;/

**Comment by extremeshok** [comment]
4d5be3a5d094167252893fb1607b62d20eb58709
