### ISSUE TITLE
 Function remove_script() doesn't remove cron and logrotate files anymore

### ISSUE THREAD

**Issue by markonjezic** [extremeshok/clamav-unofficial-sigs#96]
Function remove_script() uses hardcoded path values to the cron and logrotate files, which are no longer correct (there is no filename suffix on auto generated files). Instead of hardcoded values it should use "$cron_dir/$cron_filename" and "$logrotate_dir/$logrotate_filename" for the locations.

**Comment by extremeshok** [comment]
thanks, will fix this shortly

**Comment by extremeshok** [comment]
4d5be3a5d094167252893fb1607b62d20eb58709
